let self = [
  "## Hazel language guide",
  "",
  "Hazel is a typed, live functional programming language with structure-aware editing.",
  "Every edit state maintains a valid AST. Typed holes (`?`) represent missing code and still typecheck/evaluate.",
  "",
  "## Critical Syntax Rules",
  "",
  "1. **Function application** ALWAYS uses parentheses: `f(x)`, `g(x, y)`. NEVER use space-separated application.",
  "2. **Function parameters** are comma-separated: `fun x, y -> expr`. NEVER space-separate parameters.",
  "3. **Named functions** — PREFERRED: parameters on the let, return type after the parens: `let f(x, y) = expr in ...`, `let f(x: Int, y: Int): Int = expr in ...`. Equivalent to `let f = fun x, y -> expr in ...`; keep `fun` for anonymous lambdas.",
  "4. **Recursion** needs NO `rec` keyword. `let f(n) = ... f(n - 1) ... in ...` works directly, annotated or not.",
  "5. **Pattern matching** uses `case expr | p1 => e1 | p2 => e2 end`. MUST end with `end`. NO `of`, `with`, `switch`, or `match` keywords.",
  "6. **Type aliases**: `type Name = definition in body`.",
  "7. **Sum types** (ADTs): `+ Ctor1 + Ctor2(Type)`. Each constructor prefixed with `+`.",
  "8. **List types**: `[Int]`, `[String]`.",
  "9. **Tests**: `test bool_expr end`. MUST end with `end`. Chain with `;`.",
  "10. **Comments**: `# text #`. MUST have BOTH opening AND closing `#`. Cannot span multiple lines.",
  "11. **No dot-accessor** on plain tuples — use destructuring: `let (a, b) = tuple in ...`. Labeled-tuple/module fields DO use `.` (see Modules).",
  "12. **FORBIDDEN keywords**: `rec`, `switch`, `match`, `with`, `of`. NEVER use them.",
  "13. **Reserved words** — these lex as keyword forms and can NEVER be variable/function names (e.g. `eval` becomes the eval-filter keyword and misparses): `case`, `debug`, `eval`, `fix`, `forall`, `fun`, `hide`, `hint`, `if`, `in`, `let`, `module`, `pause`, `test`, `theorem`, `type`, `typfun`, `use` (also `proof_object` and the `of_*` prover forms). Common traps: `eval`, `test` — name things `evaluate`, `run_tests`, etc. `true`/`false`/`undefined`/`_` are literals/wildcard, equally unusable. `rec` and `poly` are reserved only in TYPE positions (recursive/polymorphic types — there is no let-rec). Proof-syntax delimiters (`val`, `valid`, `consistent`, `matched_*`) and trailing delimiters (`end`, `then`, `else`, `with`) DO parse as ordinary names, but avoid them for clarity.",
  "14. **No modulo operator** `%`. Use the `int_mod(a, b)` builtin instead.",
  "15. **Modules**: `{ let x = 1; let y = 2 }` — curly braces, semicolon-separated items. Use `module M = { ... }` for capitalized names.",
  "",
  "## Types",
  "",
  "```",
  "Int, Float, Bool, String                  # Primitives #",
  "(Int, String)                             # Tuple #",
  "[Int]                                     # List #",
  "Int -> Bool                               # Function #",
  "(Int, Int) -> Int                         # Multi-param function #",
  "+ None + Some(Int)                        # Sum type #",
  "poly A -> A -> A                          # Polymorphic #",
  "```",
  "",
  "## Operators",
  "",
  "```",
  "+, -, *, /, **     # Int arithmetic #",
  "+., -., *., /., **.   # Float arithmetic (dotted ops required) #",
  "==, !=, <, >, <=, >=  # Comparison (result is Bool) #",
  "==., !=., <., >., <=., >=.  # Float comparison #",
  "&&, ||, !          # Boolean logic #",
  "++                 # String concatenation #",
  "::                 # List cons (prepend) #",
  "@                  # List append #",
  "|>                 # Pipeline: x |> f is f(x) #",
  "```",
  "",
  "## Let Bindings",
  "",
  "```",
  "let x = 42 in",
  "let y : Int = x + 1 in",
  "let greeting = \"hello\" in",
  "y",
  "```",
  "",
  "Bindings can be chained. The final expression is the program's result.",
  "",
  "## Functions",
  "",
  "```",
  "# Anonymous function #",
  "fun x -> x + 1",
  "",
  "# Multi-parameter #",
  "fun x, y -> x + y",
  "",
  "# Named function (preferred) #",
  "let add(x, y) = x + y in",
  "add(3, 4)",
  "",
  "# With type annotations #",
  "let add(x: Int, y: Int): Int = x + y in",
  "add(3, 4)",
  "",
  "# Equivalent explicit form #",
  "let add : (Int, Int) -> Int = fun x, y -> x + y in",
  "add(3, 4)",
  "",
  "# Recursive (no rec keyword needed) #",
  "let factorial(n) =",
  "  if n <= 1 then 1 else n * factorial(n - 1)",
  "in",
  "factorial(5)",
  "```",
  "",
  "## Algebraic Data Types and Pattern Matching",
  "",
  "```",
  "# Define a sum type #",
  "type Shape =",
  "  + Circle(Int)",
  "  + Rect(Int, Int)",
  "in",
  "",
  "# Pattern match with case...end #",
  "let describe(s) =",
  "  case s",
  "  | Circle(r) => \"circle\"",
  "  | Rect(w, h) => \"rectangle\"",
  "  end",
  "in",
  "describe(Circle(5))",
  "```",
  "",
  "## Lists",
  "",
  "```",
  "let xs = [1, 2, 3] in",
  "let ys = 0 :: xs in",
  "",
  "# Process with pattern matching #",
  "let length(xs: [Int]): Int =",
  "  case xs",
  "  | [] => 0",
  "  | _ :: tl => 1 + length(tl)",
  "  end",
  "in",
  "length(ys)",
  "```",
  "",
  "## Tuples",
  "",
  "```",
  "let point : (Int, Int) = (3, 4) in",
  "let (x, y) = point in",
  "x + y",
  "```",
  "",
  "## Conditionals",
  "",
  "```",
  "if x > 0 then \"positive\" else \"non-positive\"",
  "```",
  "",
  "## Polymorphism",
  "",
  "```",
  "# Type function with poly annotation #",
  "let id : poly A -> A -> A =",
  "  typfun A -> fun x : A -> x",
  "in",
  "id@<Int>(42)",
  "",
  "# Polymorphic map #",
  "let map : poly A -> poly B -> ((A -> B), [A]) -> [B] =",
  "  typfun A -> typfun B -> fun f, xs ->",
  "    case xs",
  "    | [] => []",
  "    | hd :: tl => f(hd) :: map@<A>@<B>(f, tl)",
  "    end",
  "in",
  "map@<Int>@<Bool>(fun n -> n > 1, [1, 2, 3])",
  "```",
  "",
  "## Mutual Recursion (via tuple binding)",
  "",
  "```",
  "let (even : Int -> Bool, odd : Int -> Bool) =",
  "  (fun n -> if n == 0 then true else odd(n - 1),",
  "   fun n -> if n == 0 then false else even(n - 1))",
  "in",
  "even(4)",
  "```",
  "",
  "## Modules",
  "",
  "Modules use curly braces `{ }` with semicolon-separated items. A module is a first-class value whose type is a signature such as `{ let x : Int; type T = Int }`; signatures are distinct from labeled tuple types.",
  "",
  "```",
  "# Basic module #",
  "let m = { let x = 1; let y = true } in m.x",
  "",
  "# With type alias (ascription on right) #",
  "let m = { type T = Int; let x = 5 : T } in m.x",
  "",
  "# The `module` keyword for capitalized names #",
  "module M = { let x = 1; let y = 2 } in M.x + M.y",
  "",
  "# Nested modules (module keyword inside body for capitalized names) #",
  "let m = { module Inner = { let z = 42 }; let r = Inner.z } in m.r",
  "",
  "# Nested with lowercase let #",
  "let outer = { let inner = { let a = 42 } } in outer.inner.a",
  "",
  "# Qualified type access #",
  "module M = { type T = Int } in",
  "let x : M.T = 6 in x",
  "```",
  "",
  "Each item is one of: `let pat = exp`, `type T = typ`, `module M = { ... }` (capitalized names), or a bare expression (e.g. `test ... end`).",
  "Use `module` for capitalized names; lowercase `let` works for module bindings.",
  "",
  "## Tests",
  "",
  "```",
  "test 2 + 2 == 4 end;",
  "test factorial(5) == 120 end;",
  "```",
  "",
  "## Typed Holes",
  "",
  "The `?` symbol is a typed hole — a placeholder for missing code.",
  "Programs with holes still typecheck, evaluate, and provide meaningful feedback.",
  "Use holes as scaffolding when building programs incrementally.",
  "",
  "```",
  "let f : ? -> ? = fun x -> x + 1 in",
  "f(5)",
  "```",
  "",
  "## Complete Example Program",
  "",
  "This program defines an Option type, a list utility, and tests:",
  "```",
  "type Option = + None + Some(Int) in",
  "",
  "let unwrap_or(opt: Option, default: Int): Int =",
  "  case opt",
  "  | None => default",
  "  | Some(x) => x",
  "  end",
  "in",
  "",
  "let sum(xs: [Int]): Int =",
  "  case xs",
  "  | [] => 0",
  "  | hd :: tl => hd + sum(tl)",
  "  end",
  "in",
  "",
  "let safe_head(xs: [Int]): Option =",
  "  case xs",
  "  | [] => None",
  "  | hd :: _ => Some(hd)",
  "  end",
  "in",
  "",
  "test sum([1, 2, 3]) == 6 end;",
  "test unwrap_or(safe_head([10, 20]), 0) == 10 end;",
  "test unwrap_or(safe_head([]), 0) == 0 end;",
  "sum([1, 2, 3, 4, 5])",
  "```",
  "",
];
