coverage:
  status:
    project: # more options at https://docs.codecov.com/docs/commit-status
      default:
        target: auto # Monotonically increasing coverage
        threshold: 0% # Allows coverage to drop by 0%