open Haz3lcore;

let startup: PersistentData.t = {
  scratch: (
    0,
    [("Scratchpad 1", Zipper.init() |> PersistentZipper.persist)],
  ),
  documentation: (
    0,
    [
      BasicReference.out,
      Projectors.out,
      ADTs.out,
      Tuples.out,
      Tables.out,
      Polymorphism.out,
      Cards.out,
      Probes.out,
      Livelits.out,
      B2T2Datasheet.out,
      B2T2ExampleTables.out,
      B2T2TableAPIConstructors.out,
      B2T2TableAPIProperties.out,
      B2T2TableAPIAccessSubcomponents.out,
      B2T2TableAPISubtable.out,
      B2T2TableAPISubtable2.out,
      B2T2TableAPIOrdering.out,
      B2T2TableAPIAggregate.out,
      B2T2TableAPIMissingValues.out,
      B2T2TableAPIDataCleaning.out,
      B2T2TableAPIUtilities.out,
      B2T2TableAPIUtilities2.out,
      B2T2ExampleProgramDotProduct.out,
      B2T2ExampleProgrampHackingHomogeneous.out,
      B2T2ExampleProgrampHackingHeterogeneous.out,
      B2T2ExampleProgramquizScoreFilter.out,
      B2T2ExampleProgramquizScoreSelect.out,
      B2T2ExampleProgramgroupByRetentive.out,
      B2T2ExampleProgramgroupBySubtractive.out,
      GUIDEExpressiveProgramming.out,
      GUIDEComposingExpressions.out,
      GUIDEComputingEquationally.out,
      GUIDEVariables.out,
      GUIDECompositionality.out,
      GUIDEScope.out,
      GUIDEShadowing.out,
      GUIDEBoolsandTypes.out,
      GUIDEConditionals.out,
      GUIDEFunctions.out,
      TESTSTypesandStaticErrors.out,
    ],
  ),
};
