(* Auto-generated by: ./hazel gen-slides -- DO NOT EDIT *)
(* Source: hazel-programs/study/writing/log-cleaner/log-cleaner-solution.hz *)

let out : string * Haz3lcore.PersistentZipper.t =
  ( "Study / writing / log-cleaner / log-cleaner-solution",
    Haz3lcore.PersistentZipper.of_slide_text
      {x|# Moonphase Log Cleaner - Solution #

let clean_entry: String -> String = fun entry ->
let s = string_trim(entry) in
let s = string_replace("[🌕🌑🌓🌗]", s, "") in
let s = string_replace(" *-- *", s, ": ") in
let s = string_replace(" +", s, " ") in
string_trim(s)
in

test
clean_entry("  🌕 Full Moon -- clear skies, planted moonbloom  ")
== "Full Moon: clear skies, planted moonbloom"
end;

test
clean_entry("🌑  New Moon--cloudy,   harvested starfern")
== "New Moon: cloudy, harvested starfern"
end;

test
clean_entry("  🌓 Half Moon -- light rain, pruned duskrose  ")
== "Half Moon: light rain, pruned duskrose"
end;

test
clean_entry("🌗 Crescent--foggy,  checked   moth traps")
== "Crescent: foggy, checked moth traps"
end
|x}
  )
