// Synthesis slicing tests
open Test_Statics_Slicing_Prelude;

let atoms = [
  synthesis_case("int-lit", "1", "Int", "1"),
  synthesis_case("whole-gap", "1 + 2", "?", "?"),
  synthesis_case(~focus=first_int, "focused-gap", "1 + 2", "?", "? + ?"),
  synthesis_case(
    ~focus=e => nth_int(e, 1),
    "focused-gap-middle",
    "1 + 2 + 3",
    "?",
    "? + ? + ?",
  ),
  synthesis_case("bool-lit", "true", "Bool", "true"),
  synthesis_case("string-lit", "\"s\"", "String", "\"s\""),
  synthesis_case("float-lit", "1.0", "Float", "1.0"),
  synthesis_case("hole-pure", "?", "?", "?"),
  synthesis_case(
    ~assumptions=[("x", "Int")],
    "free-var-int",
    "x",
    "Int",
    "x",
  ),
  synthesis_case(
    ~ctx=ctx_var("x", "Int -> Int"),
    ~focus=e => exp_var(e, "x"),
    ~assumptions=[("x", "Int -> Int")],
    "var-assumption-full",
    "x",
    "Int -> Int",
    "x",
  ),
  synthesis_case(
    ~ctx=ctx_var("x", "Int -> Int"),
    ~focus=e => exp_var(e, "x"),
    ~assumptions=[("x", "Int -> ?")],
    "var-assumption-refined",
    "x",
    "Int -> ?",
    "x",
  ),
];

let ctors = [
  synthesis_case(
    ~ctx=prelude_ctx("type T = +A in"),
    ~aliases=[("T", "+A")],
    "ctor-nullary-only",
    "A",
    "T",
    "A",
  ),
  synthesis_case(
    ~ctx=prelude_ctx("type T = A + B in"),
    ~aliases=[("T", "? + B")],
    "ctor-nullary-choice",
    "B",
    "T",
    "B",
  ),
  synthesis_case(
    ~ctx=prelude_ctx("type T = +A(Int) in"),
    ~aliases=[("T", "+A(?)")],
    "ctor-payload-result",
    "A(1)",
    "T",
    "A(?)",
  ),
  synthesis_case(
    ~ctx=prelude_ctx("type T = A(Int) + B(Bool) in"),
    ~aliases=[("T", "A(?) + ?")],
    "ctor-payload-sensitive",
    "A(1)",
    "T",
    "A(?)",
  ),
  synthesis_case(
    ~ctx=prelude_ctx("type T = A(Int) + B(Bool) in"),
    ~aliases=[("T", "A(?) + ?")],
    "ctor-payload-choice",
    "A(1)",
    "T",
    "A(?)",
  ),
];

let wrappers = [
  synthesis_case("ascription-int", "(1 : Int)", "Int", "(? : Int)"),
  synthesis_case(
    "proof-object-dependency",
    "proof_object true end",
    "proof_of true end",
    "proof_object true end",
  ),
  synthesis_case("label-full", "(l=1)", "(l=Int)", "(l=1)"),
  synthesis_case("label-gradual", "(l=1)", "(l=?)", "(l=?)"),
  synthesis_case("explicit-nonlabel", "(~1)", "(~Int)", "(~1)"),
];

let products = [
  synthesis_case("tuple-full", "(1, true)", "(Int, Bool)", "(1, true)"),
  synthesis_case("tuple-left", "(1, true)", "(Int, ?)", "(1, ?)"),
  synthesis_case("tuple-right", "(1, true)", "(?, Bool)", "(?, true)"),
  synthesis_case("tuple-shape-only", "(1, true)", "(?, ?)", "(?, ?)"),
  synthesis_case(
    "tuple-nested",
    "(1, (true, \"s\"))",
    "(?, (Bool, ?))",
    "(?, (true, ?))",
  ),
  synthesis_case("dot-left", "(a=1, b=true).a", "Int", "(a=1, ?).a"),
  synthesis_case(
    "tuple-extension-left",
    "(a=1) ... (b=true)",
    "(a=Int, b=?)",
    "(a=1) ... (b=?)",
  ),
  synthesis_case(
    "tuple-extension-right",
    "(a=1) ... (b=true)",
    "(a=?, b=Bool)",
    "(a=?) ... (b=true)",
  ),
  synthesis_case(
    "tuple-extension-override",
    "(a=1) ... (a=2)",
    "(a=Int)",
    "(a=?) ... (a=2)",
  ),
  synthesis_case(
    "tuple-extension-unlabelled",
    "(1, true) ... (\"s\", 2.0)",
    "(?, Bool, ?, ?)",
    "(?, true) ... (?, ?)",
  ),
  synthesis_case("list-single-full", "[1]", "[Int]", "[1]"),
  synthesis_case("list-single-gradual", "[1]", "[?]", "[?]"),
  synthesis_case("list-empty-gradual", "[]", "[?]", "[]"),
  synthesis_case("list-cons-full", "1 :: []", "[Int]", "1 :: ?"),
  synthesis_case("list-cons-gradual", "1 :: []", "[?]", "? :: ?"),
  synthesis_case("list-concat-full", "[1] @ []", "[Int]", "[1] @ ?"),
  synthesis_case("list-concat-gradual", "[1] @ []", "[?]", "? @ ?"),
  synthesis_case(
    "regression-module-unit-field-query",
    "{ module B = (()) }",
    "(B=(()))",
    "{ module B = (()) }",
  ),
];

let functions = [
  synthesis_case(
    "fun-binder-omit-unused",
    "fun x : String -> 0",
    "String -> Int",
    "fun ? : String -> 0",
  ),
  synthesis_case(
    "fun-binder-omit-annotated",
    "fun (x : Int) -> 0",
    "Int -> Int",
    "fun (? : Int) -> 0",
  ),
  synthesis_case(
    "fun-binder-keep-used",
    "fun (x : Int) -> x",
    "Int -> Int",
    "fun (x : Int) -> x",
  ),
  synthesis_case(
    "fun-binder-partial-use",
    "fun (x : Int) -> fun (y : Int) -> x",
    "Int -> Int -> Int",
    "fun (x : Int) -> fun (? : Int) -> x",
  ),
  synthesis_case(
    "fun-full",
    "fun (x : Int) -> x",
    "Int -> Int",
    "fun (x : Int) -> x",
  ),
  synthesis_case(
    "fun-body-demand",
    "fun (x : Int) -> x",
    "? -> Int",
    "fun (x : Int) -> x",
  ),
  synthesis_case(
    "fun-domain-only",
    "fun (x : Int) -> 1",
    "Int -> ?",
    "fun (? : Int) -> ?",
  ),
  synthesis_case(
    "fun-sugar-domain-only",
    "fun x : String -> 1 + 2",
    "String -> ?",
    "fun ? : String -> ?",
  ),
  synthesis_case(
    ~focus=first_binop,
    "fun-sugar-focused-body-gap",
    "fun x : String -> 1 + 2",
    "?",
    "fun ? -> ?",
  ),
  synthesis_case(
    "fun-sugar-body-only",
    "fun x : String -> 1 + 2",
    "? -> Int",
    "fun ? -> ? + ?",
  ),
  synthesis_case(
    "fun-shape-only",
    "fun (x : Int) -> 1",
    "? -> ?",
    "fun ? -> ?",
  ),
  synthesis_case(
    "fun-unannotated-shape",
    "fun x -> x",
    "? -> ?",
    "fun ? -> ?",
  ),
  synthesis_case(
    "regression-fun-list-param-query",
    "fun [] -> 1",
    "[?] -> ?",
    "fun [] -> ?",
  ),
  synthesis_case(
    "regression-fun-unit-param-query",
    "fun (()) -> 0",
    "(()) -> Int",
    "fun (()) -> 0",
  ),
  synthesis_case(
    "fun-nested-arrow-left",
    "fun (f : Int -> Bool) -> f",
    "(Int -> ?) -> (Int -> ?)",
    "fun (f : Int -> ?) -> f",
  ),
  synthesis_case(
    "fun-nested-arrow-cross",
    "fun (f : Int -> Bool) -> f",
    "(Int -> ?) -> (? -> Bool)",
    "fun (f : Int -> Bool) -> f",
  ),
  synthesis_case(
    ~ctx=ctx_var("f", "Int -> Bool"),
    ~assumptions=[("f", "? -> Bool")],
    "app-free-fn",
    "f(1)",
    "Bool",
    "f(?)",
  ),
  synthesis_case(
    ~ctx=ctx_var("f", "Int -> Bool"),
    ~focus=e => exp_var(e, "f"),
    ~assumptions=[("f", "Int -> Bool")],
    "app-function-focus",
    "f(1)",
    "Int -> Bool",
    "f(?)",
  ),
  synthesis_case(
    "app-inline-id",
    "(fun (x : Int) -> x)(1)",
    "Int",
    "(fun (x : Int) -> x)(?)",
  ),
  synthesis_case(
    "app-inline-const",
    "(fun (x : Int) -> true)(1)",
    "Bool",
    "(fun ? -> true)(?)",
  ),
  synthesis_case(
    ~ctx=ctx_var("add", "(Int, Int) -> Int"),
    ~assumptions=[("add", "(Int, ?) -> Int")],
    "deferred-app",
    "add(_, 1)",
    "Int -> Int",
    "add(_, ?)",
  ),
  synthesis_case(
    ~ctx=ctx_var("f", "(Int, Bool, String) -> Float"),
    ~assumptions=[("f", "(Int, ?, String) -> Float")],
    "deferred-app-multiple",
    "f(_, true, _)",
    "(Int, String) -> Float",
    "f(_, ?, _)",
  ),
  synthesis_case(
    ~ctx=ctx_var("add", "(Int, Int) -> Int"),
    ~focus=
      e => first("deferral", collect_exp_ids(Language.Exp.is_deferral, e)),
    "deferred-app-focus",
    "add(_, 1)",
    "Int",
    "add(_, ?)",
  ),
  synthesis_case(
    ~assumptions=[("string_length", "? -> Int")],
    "builtin-string-length",
    "string_length(\"s\")",
    "Int",
    "string_length(?)",
  ),
  synthesis_case(
    "typabs-value",
    "abs A -> fun (x : A) -> x",
    "poly A -> A -> A",
    "abs A -> fun (x : A) -> x",
  ),
];

let typaps = [
  synthesis_case(
    ~ctx=ctx_var("id", "poly A -> A -> A"),
    ~assumptions=[("id", "poly ? -> ? -> Int")],
    "implicit-poly-id-call",
    "id(1)",
    "Int",
    "id(?)",
  ),
  synthesis_case(
    ~ctx=ctx_var("pair", "poly A, B -> A -> B -> (A, B)"),
    ~assumptions=[("pair", "poly ?, ? -> ? -> ? -> (Int, Bool)")],
    "implicit-poly-pair-call",
    "pair(1)(true)",
    "(Int, Bool)",
    "pair(?)(?)",
  ),
  synthesis_case(
    ~ctx=prelude_ctx("type Option(A) = None + Some(A) in"),
    ~aliases=[("Option", "typfun A -> ? + Some(?)")],
    "implicit-param-option",
    "Some(1)",
    "Option(Int)",
    "Some(?)",
  ),
  synthesis_case(
    ~ctx=prelude_ctx("type Option(A) = None + Some(A) in"),
    ~aliases=[("Option", "typfun A -> ? + Some(?)")],
    "if-explicit-param-option",
    "if ? then Some@<Int>(1) else Some(0)",
    "Option(Int)",
    "if ? then Some@<Int>(?) else ?",
  ),
  synthesis_case(
    ~ctx=prelude_ctx("type Option(A) = None + Some(A) in"),
    "if-explicit-param-sum-query",
    "if ? then Some@<Int>(1) else Some(0)",
    "None + Some(Int)",
    "if ? then Some@<Int>(?) else ?",
  ),
  synthesis_case(
    ~ctx=prelude_ctx("type Option(A) = None + Some(A) in"),
    ~aliases=[("Option", "typfun A -> ? + Some(?)")],
    "if-explicit-param-option-gap",
    "if ? then Some@<Int>(1) else Some(0)",
    "Option(?)",
    "if ? then Some@<?>(?) else ?",
  ),
  synthesis_case(
    ~ctx=ctx_var("id", "poly A -> A -> A"),
    ~assumptions=[("id", "poly A -> ? -> A")],
    "typap-single-call",
    "id@<Int>(1)",
    "Int",
    "id@<Int>(?)",
  ),
  synthesis_case(
    ~ctx=ctx_var("pair", "poly A, B -> A -> B -> (A, B)"),
    ~assumptions=[("pair", "poly A, B -> ? -> ? -> (A, B)")],
    "typap-multi-call",
    "pair@<Int, Bool>(1)(true)",
    "(Int, Bool)",
    "pair@<Int, Bool>(?)(?)",
  ),
  synthesis_case(
    ~ctx=ctx_var("const", "poly A, B -> A -> B -> A"),
    ~assumptions=[("const", "poly A, ? -> A -> ? -> A")],
    "typap-shaped-query",
    "const@<Int, Bool>",
    "Int -> ? -> Int",
    "const@<Int,?>",
  ),
  synthesis_case(
    ~ctx=prelude_ctx("type Option(A) = None + Some(A) in"),
    ~aliases=[("Option", "typfun A -> ? + Some(?)")],
    "param-option-explicit",
    "Some@<Int>(1)",
    "Option(Int)",
    "Some@<Int>(?)",
  ),
  synthesis_case(
    ~ctx=prelude_ctx("type Either(A, B) = Left(A) + Right(B) in"),
    ~aliases=[("Either", "typfun ?, B -> ? + Right(?)")],
    "param-either-explicit",
    "Right@<Int, Bool>(true)",
    "Either(?, Bool)",
    "Right@<?, Bool>(?)",
  ),
  synthesis_case(
    ~ctx=prelude_ctx("type List(A) = Nil + Cons(A, List(A)) in"),
    ~aliases=[("List", "typfun A -> ? + Cons(?)")],
    "param-list-recursive",
    "Cons@<Int>(1, Nil)",
    "List(Int)",
    "Cons@<Int>(?)",
  ),
  synthesis_case(
    ~ctx=prelude_ctx("type Option(A) = None + Some(A) in"),
    ~aliases=[("Option", "typfun A -> ?")],
    "param-option-annotation",
    "(Some(1) : Option(Int))",
    "Option(Int)",
    "(? : Option(Int))",
  ),
  synthesis_case(
    ~ctx=prelude_ctx("type Either(A, B) = Left(A) + Right(B) in"),
    ~aliases=[("Either", "typfun ?, B -> ?")],
    "param-either-annotation",
    "(Right(true) : Either(Int, Bool))",
    "Either(?, Bool)",
    "(? : Either(?, Bool))",
  ),
];

let control = [
  synthesis_case(
    ~ctx=prelude_ctx("type T = A(Int) + B(Int) in"),
    "match-shared-branch-binder",
    "case A(1) | A(x) => (x, ?) | B(x) => (?, x) end",
    "(Int, Int)",
    "case ? | A(x) => (x, ?) | B(x) => (?, x) end",
  ),
  synthesis_case(
    ~ctx=ctx_var("c", "Bool"),
    "if-then-only",
    "if c then 1 else 2",
    "Int",
    "if ? then 1 else ?",
  ),
  synthesis_case("sequence-result", "1; true", "Bool", "?; true"),
  synthesis_case(
    ~ctx=prelude_ctx("type T = A + B in"),
    "match-one-branch",
    "case A | A => 1 | B => 2 end",
    "Int",
    "case ? | ? => 1 | ? => ? end",
  ),
  synthesis_case(
    ~focus=e => int_lit(e, 1),
    "match-focused-middle-branch",
    "case 0 | 0 => 0 | 1 => 1 | 2 => 2 end",
    "Int",
    "case ? | ? => ? | ? => 1 | ? => ? end",
  ),
  synthesis_case(
    ~focus=e => int_lit(e, 2),
    "match-focused-last-branch",
    "case 0 | 0 => 0 | 1 => 1 | 2 => 2 end",
    "Int",
    "case ? | ? => ? | ? => ? | ? => 2 end",
  ),
  synthesis_case(
    ~ctx=ctx_var("p", "(Int, Bool)"),
    ~focus=e => int_lit(e, 0),
    "match-focused-branch-no-demand",
    "case p | (a, b) => a | (c, d) => 0 end",
    "Int",
    "case ? | ? => ? | ? => 0 end",
  ),
  synthesis_case(
    ~ctx=ctx_var("p", "(Int, Bool)"),
    ~focus=e => exp_var(e, "c"),
    ~assumptions=[("p", "(Int, ?)")],
    "match-focused-branch-scrut-demand",
    "case p | (a, b) => 0 | (c, d) => c end",
    "Int",
    "case p | ? => ? | (c, ?) => c end",
  ),
  synthesis_case(
    ~focus=ctor_arg_ap("One"),
    "match-focused-in-let-def",
    "type Option(A) = None + Some(A) in type Digit = Zero + One in let parse_digit = fun s : String -> case s | \"0\" => Some(Zero) | \"1\" => Some(One) | _ => None end in parse_digit(\"5\")",
    "Option(Digit)",
    "type Option(?) = ? + Some(?) in type ? = ? in let ? = fun ? -> case ? | ? => ? | ? => Some(?) | ? => ? end in ?",
  ),
  synthesis_case("use-nat-lit", "use Nat in 1", "Nat", "use Nat in 1"),
  synthesis_case(
    "use-nat-plus",
    "use Nat in 1 + 2",
    "Nat",
    "use Nat in ? + ?",
  ),
  synthesis_case("op-plus-int", "1 + 2", "Int", "? + ?"),
  synthesis_case("op-eq-bool", "1 == 2", "Bool", "? == ?"),
  synthesis_case("op-neg-int", "-1", "Int", "-?"),
  synthesis_case("test-unit", "test 1 == 1 end", "()", "test ? end"),
  synthesis_case(
    "hinted-test-unit",
    "hint 1 test true end",
    "()",
    "hint ? test ? end",
  ),
  synthesis_case("filter-hide", "hide 1 in true", "Bool", "hide ? in true"),
  synthesis_case("filter-eval", "eval 1 in true", "Bool", "eval ? in true"),
];

let tests = (
  "Statics.Slicing.Synthesis",
  atoms @ ctors @ wrappers @ products @ functions @ typaps @ control,
);
