// Analysis slicing tests
open Test_Statics_Slicing_Prelude;

let examples = [
  analysis_case(
    ~focus=e => pat_var(e, "x"),
    "ana-fun-param-ann",
    "fun (x : Int) -> 1",
    "Int",
    "fun (? : Int) -> ?",
  ),
  analysis_case(
    ~ctx=ctx_var("f", "Int -> Bool"),
    ~focus=first_int,
    ~assumptions=[("f", "Int -> ?")],
    "ana-app-arg",
    "f(1)",
    "Int",
    "f(?)",
  ),
  analysis_case(
    ~ctx=ctx_var("f", "Int -> Bool"),
    ~focus=e => exp_var(e, "f"),
    ~assumptions=[("f", "? -> Bool")],
    "ana-app-function",
    "(f(1) : Bool)",
    "Bool",
    "(f(?) : Bool)",
  ),
  analysis_case(
    ~focus=first_int,
    "ana-ascription-inner",
    "(1 : Int)",
    "Int",
    "(? : Int)",
  ),
  analysis_case(
    ~focus=first_int,
    "ana-tuple-element",
    "((1, true) : (Int, Bool))",
    "Int",
    "((?, ?) : (Int, ?))",
  ),
  analysis_case(
    ~focus=first_int,
    "ana-list-element",
    "([1] : [Int])",
    "Int",
    "([?] : [Int])",
  ),
  analysis_case(
    "regression-ana-fun-list-param-query",
    "fun [] -> 1",
    "[?] -> ?",
    "fun [] -> ?",
  ),
  analysis_case(
    ~ctx=ctx_var("x", "(A=())"),
    ~focus=e => exp_var(e, "x"),
    ~assumptions=[("x", "(A=?)")],
    "regression-ana-projection-base-query",
    "x.A",
    "(A=?)",
    "x.A",
  ),
  analysis_case(
    ~focus=e => cons_head_ctor(e, "Z"),
    "regression-ana-sum-list-cons-query",
    "Z:: Z",
    "[+ Z + ?]",
    "Z:: ?",
  ),
  analysis_case(
    ~focus=e => exp_var(e, "a"),
    "regression-ana-let-list-pattern-query",
    "let [] = a in (())",
    "[?]",
    "let [] = a in ?",
  ),
  analysis_case(
    ~focus=e => exp_ctor(e, "Z"),
    "regression-ana-fix-sum-body-query",
    "fix Z -> Z",
    "+ Z + ?",
    "fix Z -> Z",
  ),
  analysis_case(
    ~focus=e => fix_body_int(e, 0),
    "regression-ana-fix-atom-body-query",
    "fix 0 -> 0",
    "Int",
    "fix ? -> 0",
  ),
  analysis_case(
    ~focus=first_empty_list,
    "regression-ana-cons-tail-head-query",
    "0:: [[]]",
    "Int",
    "?:: [[]]",
  ),
  analysis_case(
    ~focus=first_exp_hole,
    "regression-ana-fix-annotated-hole-query",
    "fix(Z:(? -> ?)) -> ?",
    "? -> ?",
    "fix(Z:(? -> ?)) -> ?",
  ),
  analysis_case(
    ~ctx=ctx_var("c", "Bool"),
    ~focus=first_int,
    "ana-if-branch",
    "(if c then 1 else 2) : Int",
    "Int",
    "(if ? then ? else ?) : Int",
  ),
  analysis_case(
    ~ctx=prelude_ctx("type T = A + B in"),
    ~focus=first_int,
    "ana-match-branch",
    "(case A | A => 1 | B => 2 end) : Int",
    "Int",
    "(case ? | ? => ? | ? => ? end) : Int",
  ),
  analysis_case(~focus=first_int, "ana-op-operand", "1 + 2", "Int", "? + ?"),
  analysis_case(
    ~focus=first_binop,
    "ana-test-body",
    "test 1 == 1 end",
    "Bool",
    "test ? end",
  ),
  analysis_case(
    ~focus=first_bool,
    "ana-filter-body",
    "(hide 1 in true) : Bool",
    "Bool",
    "(hide ? in ?) : Bool",
  ),
];

let tests = ("Statics.Slicing.Analysis", examples);
