module Sexp = Sexplib.Sexp;

let self = [
  "- Hazel is a live functional programming environment that supports incomplete programs via typed holes.",
  "- Typed holes, denoted as `?`, can stand for missing expressions or types.",
  "- Programs with holes still carry meaningful static and dynamic semantics, unlike traditional languages.",
  "- Hazel uses a structure editor that maintains well-formed syntax trees with holes instead of raw text.",
  "- Example: Define a function with an unknown type and evaluate it.",
  "```",
  "let f: ? -> ? = fun b -> b && true in f(true);",
  "```",
  "- This function runs successfully even though the type is unknown.",
  "- Hazel uses **bidirectional typing**, where types can be either synthesized or analyzed.",
  "- Example: Bidirectional typing for boolean functions.",
  "```",
  "let f = fun b: Bool -> b && true in f(true);",
  "```",
  "- Holes can be used in types, parameters, and patterns.",
  "```",
  "let f: (Int, ?) -> Int = fun a, b -> a + 1 in f(1, 2);",
  "```",
  "- Hazel also supports polymorphic functions.",
  "```",
  "let poly_id: forall a -> a -> a = typfun a -> fun x: a -> x;",
  "```",
  "- Polymorphic functions can be applied with type arguments using `@<T>` syntax.",
  "```",
  "poly_id@<Int>(5);",
  "```",
  "- Hazel supports defining algebraic data types (ADTs) and using them in pattern matches.",
  "```",
  "type Exp =",
  "  + Var(String)",
  "  + Lam(String, Exp)",
  "  + Ap(Exp, Exp) in",
  "",
  "let subst: (Exp, String, Exp) -> Exp =",
  "  fun v, name, e ->",
  "    case e",
  "    | Var(n) => if n$==name then v else e",
  "    | Lam(x, body) => Lam(x, subst(v, name, body))",
  "    | Ap(e1, e2) => Ap(subst(v, name, e1), subst(v, name, e2))",
  "    end;",
  "```",
  "- Hazel permits incomplete pattern matches and treats them semantically.",
  "```",
  "let f = fun x -> case x | 0 => \"zero\" | ? => \"non-zero\" end;",
  "```",
  "- Evaluation proceeds until it hits a hole, then stops gracefully.",
  "- Example of evaluation with error halted inside a hole:",
  "```",
  "let f: Int -> Int = fun x -> x + true in f(1);",
  "```",
  "- The erroneous addition will be wrapped in a non-empty hole, not crash.",
  "- Hazel's recursive types allow expressive structures.",
  "```",
  "type MyList = rec A -> (Nil + Cons(Int, A)) in",
  "let x: MyList = Cons(1, Cons(2, Cons(3, Nil)));",
  "```",
  "- Hazel supports list processing via pattern matching.",
  "```",
  "let length: [Int] -> Int =",
  "  fun xs ->",
  "    case xs",
  "    | [] => 0",
  "    | hd::tl => 1 + length(tl)",
  "    end;",
  "```",
  "- Hazel allows mutual recursion via let-bindings of tuples.",
  "```",
  "let (even: Int -> Bool, odd: Int -> Bool) =",
  "  (fun n -> if n == 0 then true else odd(n - 1),",
  "   fun n -> if n == 0 then false else even(n - 1))",
  "in even(4);",
  "```",
  "- Projectors and livelits provide visual editing tools in Hazel's GUI.",
  "- Hazel allows tests to be included inline.",
  "```",
  "test 2 + 2 == 4 end;",
  "```",
  "- Hazel supports explaining sub-expressions via cursor-based documentation.",
  "- Hazel is ideal for education, as no edit state is meaningless.",
  "- All code edits are type-preserving and guided by Hazel's edit action model.",
  "- An important note is that comments in Hazel are enclosed by `#` symbols. Eg `# This is a comment #`. The program WILL be erroneous if you do not include an ending '#' symbol for a comment.",
];
