(include_subdirs unqualified)

(library
 (name haz3ltui)
 (modules
  (:standard \ Tui))
 (libraries haz3lcore unix)
 (preprocess
  (pps ppx_deriving.show ppx_yojson_conv ppx_sexp_conv)))

(executable
 (name tui)
 (modules Tui)
 (libraries haz3ltui)
 (modes exe))

(env
 (dev
  (js_of_ocaml
   (flags :standard --debuginfo --noinline --dynlink --linkall --sourcemap)))
 (release
  (js_of_ocaml
   (flags (:standard)))))
