let filename = "haz3l-demo";
let log_key = filename;
let lessons: list(Tutorial.spec) = [
  Tu_Holes.exercise,
  Tu_TylrParser.exercise,
  Tu_Arithmetic.int_exercise,
  Tu_Arithmetic.float_exercise,
  Tu_LetBindings.exercise,
  Tu_Probes.exercise,
  Tu_TypeAnnotations.exercise,
  Tu_Functions.exercise,
  Tu_FunctionMultiArg.exercise,
  Tu_Partial.exercise,
  Tu_Pipelines.exercise,
  Tu_CaseExpressions.exercise,
  Tu_Lists.exercise,
  Tu_ListMap.exercise,
  Tu_ListFold.exercise,
  Ta_StringMean.exercise,
  Tu_LabeledTuples.exercise,
  Tu_Projection.exercise,
  Tu_TupleList.exercise,
  Tu_TupleExtension.exercise,
  Tu_LabelOmission.exercise,
  Tu_TableProjection.exercise,
  Tu_TableProjector.exercise,
  Ta_GradebookMean.exercise,
  Ta_GradebookOverallGrade.exercise,
  Ta_TidyTerm.exercise,
  Ta_BugIdentification1.exercise,
  Ta_BugIdentification2.exercise,
];
