/* The single source of truth for every action the command palette can offer
   and the Shortcuts config slide can rebind.

   This module exists so the two cannot drift. Before it, an action's label
   was a string literal at the ContextualAction.mk site and the config listed
   the same name independently — which had already rotted: the config named
   "Go to Previous Hole" (actual: "Go to Previous Problem"), "Type" (actual:
   "Statics") and "Export Grading Exercise Module" (no such action), while
   Pretty Print and the token-extension actions were unconfigurable because
   nothing listed them.

   Now a call site names a VARIANT, not a string, and ContextualAction.mk is
   gone — of_shortcut is the only constructor. The config slide and its
   analyzed type are both generated by folding over `all`, so adding a
   variant here adds it everywhere, and the compiler rejects a variant that
   forgets its metadata. */

/* The shortcut vocabulary itself lives beside the Hazel types it mirrors, in
   Language.BuiltinsADT.Shortcut, so the config slide and the keybinding
   projector share one definition. Re-exported here (constructors included)
   because this module's default bindings are written in terms of them. */
module S = Language.BuiltinsADT.Shortcut;

type key_mod = S.key_mod = | Meta | Ctrl | Shift | Alt;

type binding = S.binding = | Unbound | Bound(list(key_mod), string);

/* Reuses the groups the command palette already displays, so the config
   slide is organised the way the palette is. */
type section =
  | General
  | Navigation
  | Selection
  | Projection
  | Refactoring
  | Formatting
  | Scratchpads
  | Export
  | Diagnostics
  | Settings;

/* Display/config order. */
let all_sections = [
  General,
  Navigation,
  Selection,
  Projection,
  Refactoring,
  Formatting,
  Scratchpads,
  Export,
  Diagnostics,
  Settings,
];

let section_label = (s: section): string =>
  switch (s) {
  | General => "General"
  | Navigation => "Navigation"
  | Selection => "Selection"
  | Projection => "Projection"
  | Refactoring => "Refactoring"
  | Formatting => "Formatting"
  | Scratchpads => "Scratchpads"
  | Export => "Export"
  | Diagnostics => "Diagnostics"
  | Settings => "Settings"
  };

[@deriving (show({with_path: false}), sexp, yojson, enumerate)]
type t =
  | Undo
  | Redo
  | TydiAssistant
  | GoToDefinition
  | GoToPreviousProblem
  | GoToNextProblem
  | SelectCurrentTerm
  | SelectAll
  | ToggleSelectionFocus
  | SetSelectionFocusLeft
  | SetSelectionFocusRight
  | ExtendSelectionLeftByToken
  | ExtendSelectionRightByToken
  | Fold
  | Probe
  | Statics
  | Livelit
  | Introduce
  | PrettyPrint
  | AddNewCodeScratchpad
  | AddNewDerivationScratchpad
  | RenameCurrentScratchpad
  | DeleteCurrentScratchpad
  | ExportCurrentScratchpad
  | EncodeCurrentScratchpadInUrl
  | ExportForInit
  | ExportSubmission
  | ExportExerciseModule
  | ExportTransitionaryExerciseModule
  | RunBenchmark
  | ReparseCurrentEditor
  | ToggleStatics
  | ToggleCompletion
  | ToggleShowWhitespace
  | ToggleCharacterLevelMouse
  | TogglePrintBenchmarks
  | ToggleDebugSidebar
  | ToggleDynamics
  | ToggleShowElaboration
  | ToggleShowFunctionBodies
  | ToggleShowCaseClauses
  | ToggleShowFixpoints
  | ToggleShowAscriptionSteps
  | ToggleShowLookupSteps
  | ToggleShowStepperFilters
  | ToggleShowHiddenSteps
  | ToggleShowSidebar
  | ToggleShowDocsFeedback;

type action_meta = {
  label: string,
  section,
  mdIcon: string,
  default_binding: binding,
};

/* Exhaustive by construction: a new variant that forgets its metadata is a
   compile error, not a silent gap. */
let meta = (a: t): action_meta =>
  switch (a) {
  | Undo => {
      label: "Undo",
      section: General,
      mdIcon: "undo",
      default_binding: Bound([Meta], "z"),
    }
  | Redo => {
      label: "Redo",
      section: General,
      mdIcon: "redo",
      default_binding: Bound([Meta, Shift], "z"),
    }
  | TydiAssistant => {
      label: "TyDi Assistant",
      section: General,
      mdIcon: "assistant",
      default_binding: Bound([Meta], "/"),
    }
  | GoToDefinition => {
      label: "Go to Definition",
      section: Navigation,
      mdIcon: "arrow_forward",
      default_binding: Bound([], "F12"),
    }
  | GoToPreviousProblem => {
      label: "Go to Previous Problem",
      section: Navigation,
      mdIcon: "arrow_upward",
      default_binding: Bound([Shift], "tab"),
    }
  | GoToNextProblem => {
      label: "Go to Next Problem",
      section: Navigation,
      mdIcon: "arrow_downward",
      default_binding: Unbound,
    }
  | SelectCurrentTerm => {
      label: "Select current term",
      section: Selection,
      mdIcon: "select_all",
      default_binding: Bound([Meta], "d"),
    }
  | SelectAll => {
      label: "Select All",
      section: Selection,
      mdIcon: "select_all",
      default_binding: Bound([Meta], "a"),
    }
  | ToggleSelectionFocus => {
      label: "Toggle Selection Focus",
      section: Selection,
      mdIcon: "flip_horizontal",
      default_binding: Unbound,
    }
  | SetSelectionFocusLeft => {
      label: "Set Selection Focus Left",
      section: Selection,
      mdIcon: "border_left",
      default_binding: Bound([Meta, Alt, Shift], "left"),
    }
  | SetSelectionFocusRight => {
      label: "Set Selection Focus Right",
      section: Selection,
      mdIcon: "border_right",
      default_binding: Bound([Meta, Alt, Shift], "right"),
    }
  | ExtendSelectionLeftByToken => {
      label: "Extend Selection Left by Token",
      section: Selection,
      mdIcon: "chevron_left",
      default_binding: Bound([Alt, Shift], "left"),
    }
  | ExtendSelectionRightByToken => {
      label: "Extend Selection Right by Token",
      section: Selection,
      mdIcon: "chevron_right",
      default_binding: Bound([Alt, Shift], "right"),
    }
  | Fold => {
      label: "Fold",
      section: Projection,
      mdIcon: "camera",
      default_binding: Bound([Alt], "f"),
    }
  | Probe => {
      label: "Probe",
      section: Projection,
      mdIcon: "camera",
      default_binding: Bound([Meta], "e"),
    }
  | Statics => {
      label: "Statics",
      section: Projection,
      mdIcon: "camera",
      default_binding: Bound([Alt], "t"),
    }
  | Livelit => {
      label: "Livelit",
      section: Projection,
      mdIcon: "camera",
      default_binding: Bound([Alt], "l"),
    }
  | Introduce => {
      label: "Introduce",
      section: Refactoring,
      mdIcon: "bolt",
      default_binding: Bound([Meta], "i"),
    }
  | PrettyPrint => {
      label: "Pretty Print",
      section: Formatting,
      mdIcon: "format_align_left",
      default_binding: Bound([Meta], "s"),
    }
  | AddNewCodeScratchpad => {
      label: "Add New Code Scratchpad",
      section: Scratchpads,
      mdIcon: "add",
      default_binding: Unbound,
    }
  | AddNewDerivationScratchpad => {
      label: "Add New Derivation Scratchpad",
      section: Scratchpads,
      mdIcon: "rule",
      default_binding: Unbound,
    }
  | RenameCurrentScratchpad => {
      label: "Rename Current Scratchpad",
      section: Scratchpads,
      mdIcon: "edit",
      default_binding: Unbound,
    }
  | DeleteCurrentScratchpad => {
      label: "Delete Current Scratchpad",
      section: Scratchpads,
      mdIcon: "delete",
      default_binding: Unbound,
    }
  | ExportCurrentScratchpad => {
      label: "Export Current Scratchpad",
      section: Export,
      mdIcon: "download",
      default_binding: Unbound,
    }
  | EncodeCurrentScratchpadInUrl => {
      label: "Encode Current Scratchpad in URL",
      section: Export,
      mdIcon: "download",
      default_binding: Unbound,
    }
  | ExportForInit => {
      label: "Export For Init",
      section: Export,
      mdIcon: "download",
      default_binding: Unbound,
    }
  | ExportSubmission => {
      label: "Export Submission",
      section: Export,
      mdIcon: "download",
      default_binding: Unbound,
    }
  | ExportExerciseModule => {
      label: "Export Exercise Module",
      section: Export,
      mdIcon: "download",
      default_binding: Unbound,
    }
  | ExportTransitionaryExerciseModule => {
      label: "Export Transitionary Exercise Module",
      section: Export,
      mdIcon: "download",
      default_binding: Unbound,
    }
  | RunBenchmark => {
      label: "Run Benchmark",
      section: Diagnostics,
      mdIcon: "timer",
      default_binding: Bound([], "F7"),
    }
  | ReparseCurrentEditor => {
      label: "Reparse Current Editor",
      section: Diagnostics,
      mdIcon: "refresh",
      default_binding: Unbound,
    }
  | ToggleStatics => {
      label: "Toggle Statics",
      section: Settings,
      mdIcon: "tune",
      default_binding: Unbound,
    }
  | ToggleCompletion => {
      label: "Toggle Completion",
      section: Settings,
      mdIcon: "tune",
      default_binding: Unbound,
    }
  | ToggleShowWhitespace => {
      label: "Toggle Show Whitespace",
      section: Settings,
      mdIcon: "tune",
      default_binding: Unbound,
    }
  | ToggleCharacterLevelMouse => {
      label: "Toggle Character-level Mouse",
      section: Settings,
      mdIcon: "tune",
      default_binding: Unbound,
    }
  | TogglePrintBenchmarks => {
      label: "Toggle Print Benchmarks",
      section: Settings,
      mdIcon: "tune",
      default_binding: Unbound,
    }
  | ToggleDebugSidebar => {
      label: "Toggle Debug Sidebar",
      section: Settings,
      mdIcon: "tune",
      default_binding: Unbound,
    }
  | ToggleDynamics => {
      label: "Toggle Dynamics",
      section: Settings,
      mdIcon: "tune",
      default_binding: Unbound,
    }
  | ToggleShowElaboration => {
      label: "Toggle Show Elaboration",
      section: Settings,
      mdIcon: "tune",
      default_binding: Unbound,
    }
  | ToggleShowFunctionBodies => {
      label: "Toggle Show Function Bodies",
      section: Settings,
      mdIcon: "tune",
      default_binding: Unbound,
    }
  | ToggleShowCaseClauses => {
      label: "Toggle Show Case Clauses",
      section: Settings,
      mdIcon: "tune",
      default_binding: Unbound,
    }
  | ToggleShowFixpoints => {
      label: "Toggle Show fixpoints",
      section: Settings,
      mdIcon: "tune",
      default_binding: Unbound,
    }
  | ToggleShowAscriptionSteps => {
      label: "Toggle Show Ascription Steps",
      section: Settings,
      mdIcon: "tune",
      default_binding: Unbound,
    }
  | ToggleShowLookupSteps => {
      label: "Toggle Show Lookup Steps",
      section: Settings,
      mdIcon: "tune",
      default_binding: Unbound,
    }
  | ToggleShowStepperFilters => {
      label: "Toggle Show Stepper Filters",
      section: Settings,
      mdIcon: "tune",
      default_binding: Unbound,
    }
  | ToggleShowHiddenSteps => {
      label: "Toggle Show Hidden Steps",
      section: Settings,
      mdIcon: "tune",
      default_binding: Unbound,
    }
  | ToggleShowSidebar => {
      label: "Toggle Show Sidebar",
      section: Settings,
      mdIcon: "tune",
      default_binding: Unbound,
    }
  | ToggleShowDocsFeedback => {
      label: "Toggle Show Docs Feedback",
      section: Settings,
      mdIcon: "tune",
      default_binding: Unbound,
    }
  };

let label = (a: t): string => meta(a).label;
let section_of = (a: t): section => meta(a).section;
let md_icon = (a: t): string => meta(a).mdIcon;
let default_binding = (a: t): binding => meta(a).default_binding;

let in_section = (s: section): list(t) =>
  List.filter(a => section_of(a) == s, all);

/* Sections carrying no actions are omitted from the config slide. */
let populated_sections: list(section) =
  List.filter(s => in_section(s) != [], all_sections);

/* The palette groups by an optional string; General is the ungrouped bucket. */
let section_string = (a: t): option(string) =>
  switch (section_of(a)) {
  | General => None
  | s => Some(section_label(s))
  };

/* Resolution lives in the shared module (the one place the platform is
   consulted, which is what keeps the config program system-independent). */
let string_of_key_mod = S.string_of_key_mod;
let string_of_chord = S.string_of_chord;
let string_of_binding = S.string_of_binding;

let default_hotkey = (a: t): option(string) =>
  string_of_binding(default_binding(a));
