let mk_shortcut =
    (
      ~hotkey=?,
      ~mdIcon=?,
      ~section=?,
      label,
      ~inject: Page.Update.t => Virtual_dom.Vdom.Effect.t(unit),
      update_action: Page.Update.t,
    )
    : ContextualAction.t => {
  {
    update_action: Some(inject(update_action)),
    hotkey,
    label,
    mdIcon,
    section,
  };
};

let instructor_shortcuts = (~inject): list(ContextualAction.t) => [
  mk_shortcut(
    ~mdIcon="download",
    ~section="Export",
    "Export Exercise Module",
    ~inject,
    Editors(Exercises(ExportModule)),
  ),
  mk_shortcut(
    ~mdIcon="download",
    ~section="Export",
    "Export Transitionary Exercise Module",
    ~inject,
    Editors(Exercises(ExportTransitionary)),
  ),
];

let shortcuts = (~inject, sys: Util.Key.sys): list(ContextualAction.t) =>
  [
    mk_shortcut(
      ~mdIcon="undo",
      ~hotkey=Keyboard.meta(sys) ++ "+z",
      "Undo",
      ~inject,
      Globals(Undo),
    ),
    mk_shortcut(
      ~hotkey=Keyboard.meta(sys) ++ "+shift+z",
      ~mdIcon="redo",
      "Redo",
      ~inject,
      Globals(Redo),
    ),
    mk_shortcut(
      ~hotkey="F12",
      ~mdIcon="arrow_forward",
      ~section="Navigation",
      "Go to Definition",
      ~inject,
      Globals(ActiveEditor(Move(Goal(BindingSiteOfIndicatedVar)))),
    ),
    mk_shortcut(
      ~hotkey="shift+tab",
      ~mdIcon="arrow_upward",
      ~section="Navigation",
      "Go to Previous Problem",
      ~inject,
      Globals(ActiveEditor(Move(Goal(NextProblem(Left))))),
    ),
    mk_shortcut(
      ~mdIcon="arrow_downward",
      ~section="Navigation",
      "Go to Next Problem",
      ~inject,
      Globals(ActiveEditor(Move(Goal(NextProblem(Right))))),
    ),
    mk_shortcut(
      ~hotkey=Keyboard.meta(sys) ++ "+d",
      ~mdIcon="select_all",
      ~section="Selection",
      "Select current term",
      ~inject,
      Globals(ActiveEditor(Select(Term(Current)))),
    ),
    mk_shortcut(
      ~mdIcon="select_all",
      ~hotkey=Keyboard.meta(sys) ++ "+a",
      ~section="Selection",
      "Select All",
      ~inject,
      Globals(ActiveEditor(Select(All))),
    ),
    mk_shortcut(
      ~mdIcon="flip_horizontal",
      ~section="Selection",
      "Toggle Selection Focus",
      ~inject,
      Globals(ActiveEditor(Select(ToggleFocus))),
    ),
    mk_shortcut(
      ~mdIcon="border_left",
      ~section="Selection",
      ~hotkey=Keyboard.meta(sys) ++ "+alt+shift+left",
      "Set Selection Focus Left",
      ~inject,
      Globals(ActiveEditor(Select(SetFocus(Left)))),
    ),
    mk_shortcut(
      ~mdIcon="border_right",
      ~section="Selection",
      ~hotkey=Keyboard.meta(sys) ++ "+alt+shift+right",
      "Set Selection Focus Right",
      ~inject,
      Globals(ActiveEditor(Select(SetFocus(Right)))),
    ),
    mk_shortcut(
      ~mdIcon="chevron_left",
      ~section="Selection",
      ~hotkey="alt+shift+left",
      "Extend Selection Left by Token",
      Globals(ActiveEditor(Select(Resize(Local(Left, ByToken))))),
    ),
    mk_shortcut(
      ~mdIcon="chevron_right",
      ~section="Selection",
      ~hotkey="alt+shift+right",
      "Extend Selection Right by Token",
      Globals(ActiveEditor(Select(Resize(Local(Right, ByToken))))),
    ),
    mk_shortcut(
      ~hotkey="alt+f",
      ~mdIcon="camera",
      ~section="Projection",
      "Fold",
      ~inject,
      Globals(ActiveEditor(Project(SetIndicated(Specific(Fold))))),
    ),
    mk_shortcut(
      ~hotkey=Keyboard.meta(sys) ++ "+e",
      ~mdIcon="camera",
      ~section="Projection",
      "Probe",
      ~inject,
      Globals(ActiveEditor(Probe(ToggleManual))),
    ),
    mk_shortcut(
      ~hotkey="alt+t",
      ~mdIcon="camera",
      ~section="Projection",
      "Statics",
      ~inject,
      Globals(ActiveEditor(Probe(ToggleStatics))),
    ),
    mk_shortcut(
      ~hotkey=Keyboard.meta(sys) ++ "+p",
      ~mdIcon="science",
      ~section="Projection",
      "Toggle Auto Probe",
      Globals(Set(AutoprobeMode)),
    ),
    mk_shortcut(
      ~hotkey="alt+l",
      ~mdIcon="camera",
      ~section="Projection",
      "Livelit",
      ~inject,
      Globals(ActiveEditor(Project(SetIndicated(ChooseLivelit)))),
    ),
    mk_shortcut(
      ~section="Settings",
      ~mdIcon="tune",
      "Toggle Statics",
      ~inject,
      Globals(Set(Statics)),
    ),
    mk_shortcut(
      ~section="Settings",
      ~mdIcon="tune",
      "Toggle Completion",
      ~inject,
      Globals(Set(Assist)),
    ),
    mk_shortcut(
      ~section="Settings",
      ~mdIcon="tune",
      "Toggle Show Whitespace",
      ~inject,
      Globals(Set(SecondaryIcons)),
    ),
    mk_shortcut(
      ~section="Settings",
      ~mdIcon="tune",
      "Toggle Print Benchmarks",
      ~inject,
      Globals(Set(Benchmark)),
    ),
    mk_shortcut(
      ~section="Settings",
      ~mdIcon="tune",
      "Toggle Dynamics",
      ~inject,
      Globals(Set(Dynamics)),
    ),
    mk_shortcut(
      ~section="Settings",
      ~mdIcon="tune",
      "Toggle Show Elaboration",
      ~inject,
      Globals(Set(Elaborate)),
    ),
    mk_shortcut(
      ~section="Settings",
      ~mdIcon="tune",
      "Toggle Show Function Bodies",
      ~inject,
      Globals(Set(Evaluation(ShowFnBodies))),
    ),
    mk_shortcut(
      ~section="Settings",
      ~mdIcon="tune",
      "Toggle Show Case Clauses",
      ~inject,
      Globals(Set(Evaluation(ShowCaseClauses))),
    ),
    mk_shortcut(
      ~section="Settings",
      ~mdIcon="tune",
      "Toggle Show fixpoints",
      ~inject,
      Globals(Set(Evaluation(ShowFixpoints))),
    ),
    mk_shortcut(
      ~section="Settings",
      ~mdIcon="tune",
      "Toggle Show Ascription Steps",
      ~inject,
      Globals(Set(Evaluation(ShowAscriptionSteps))),
    ),
    mk_shortcut(
      ~section="Settings",
      ~mdIcon="tune",
      "Toggle Show Lookup Steps",
      ~inject,
      Globals(Set(Evaluation(ShowLookups))),
    ),
    mk_shortcut(
      ~section="Settings",
      ~mdIcon="tune",
      "Toggle Show Stepper Filters",
      ~inject,
      Globals(Set(Evaluation(ShowFilters))),
    ),
    mk_shortcut(
      ~section="Settings",
      ~mdIcon="tune",
      "Toggle Show Hidden Steps",
      ~inject,
      Globals(Set(Evaluation(ShowHiddenSteps))),
    ),
    mk_shortcut(
      ~section="Settings",
      ~mdIcon="tune",
      "Toggle Show Sidebar",
      ~inject,
      Globals(Set(Sidebar(ToggleShow))),
    ),
    mk_shortcut(
      ~section="Settings",
      ~mdIcon="tune",
      "Toggle Show Docs Feedback",
      ~inject,
      Globals(Set(ExplainThis(ToggleShowFeedback))),
    ),
    mk_shortcut(
      ~hotkey=Keyboard.meta(sys) ++ "+/",
      ~mdIcon="assistant",
      "TyDi Assistant",
      ~inject,
      Globals(ActiveEditor(Buffer(Set(TyDi)))),
    ),
    mk_shortcut(
      ~mdIcon="download",
      ~section="Export",
      "Export Scratch Slide",
      ~inject,
      Editors(Scratch(Export)),
    ),
    mk_shortcut(
      ~mdIcon="download",
      ~section="Export",
      "Encode Scratch Slide in URL",
      ~inject,
      Editors(Scratch(Encode)),
    ),
    mk_shortcut(
      ~mdIcon="download",
      ~section="Export",
      "Export For Init",
      ~inject,
      Globals(ExportForInit),
    ),
    mk_shortcut(
      ~mdIcon="download",
      ~section="Export",
      "Export Submission",
      ~inject,
      Editors(Exercises(ExportSubmission)),
    ),
    mk_shortcut(
      ~section="Diagnostics",
      ~mdIcon="refresh",
      "Reparse Current Editor",
      ~inject,
      Globals(ActiveEditor(Reparse)),
    ),
    mk_shortcut(
      ~mdIcon="timer",
      ~section="Diagnostics",
      ~hotkey="F7",
      "Run Benchmark",
      ~inject,
      Benchmark(Start),
    ),
    mk_shortcut(
      ~mdIcon="bolt",
      ~section="Refactoring",
      ~hotkey=Keyboard.meta(sys) ++ "+i",
      "Introduce",
      ~inject,
      Globals(ActiveEditor(Introduce)),
    ),
    mk_shortcut(
      "Add New Buffer",
      ~hotkey="alt+n",
      ~mdIcon="add",
      ~section="Buffers",
      ~inject,
      Editors(Scratch(AddSlide)),
    ),
    mk_shortcut(
      "Rename Current Buffer",
      ~mdIcon="edit",
      ~section="Buffers",
      ~inject,
      Editors(Scratch(RenameSlide)),
    ),
    mk_shortcut(
      ~mdIcon="delete",
      ~section="Buffers",
      "Delete Current Buffer",
      ~inject,
      Editors(Scratch(DeleteSlide)),
    ),
  ]
  @ (
    if (ExerciseSettings.show_instructor) {
      instructor_shortcuts(~inject);
    } else {
      [];
    }
  );
