(include_subdirs unqualified)

(rule
 (targets Delta.ml)
 (deps Delta.mli)
 (action
  (run %{bin:gen_js_api} %{deps})))

(rule
 (targets MessageTypes.ml)
 (deps MessageTypes.mli)
 (action
  (run %{bin:gen_js_api} %{deps})))

(library
 (name haz3lcore)
 (libraries language ts2ocaml-jsoo-stdlib)
 (js_of_ocaml)
 (instrumentation
  (backend bisect_ppx))
 (preprocess
  (pps
   ppx_yojson_conv
   js_of_ocaml-ppx
   ppx_let
   ppx_sexp_conv
   ppx_enumerate
   ppx_deriving.show
   ppx_deriving.ord
   ppx_deriving.eq)))

(env
 (dev
  (js_of_ocaml
   (flags :standard --debuginfo --noinline --dynlink --linkall --sourcemap)))
 (release
  (js_of_ocaml
   (flags :standard))))
