import * from "./syntax_tree"
import * from "./hazel_util"
import fail from "pervasives"

export enum HTyp {
  Indet(DHExp),
  Int(Number),
  Bool(Number),
}

export let emb_bool = (b : Number) => {
  if (is_const(b)) {
    Bool(b) : (HTyp)
  } else {
    fail("failed cast: passed-in argument is an indet exp") // impossible case
  }
}

export let prj_bool = (h : HTyp) => {
  match (h) {
    Bool(b) => b,
    _ => fail("failed projection: passed-in argument isn't of Bool type") 
  }
}
