(* Auto-generated by: ./hazel gen-tutorial -- DO NOT EDIT *)
(* Source: hazel-programs/tutorial/basics/13-case-expressions.hz *)

let exercise : Tutorial.spec = {
  id = Option.get (Haz3lcore.Id.of_string "a0000011-0011-0011-0011-000000000011");
  title = "Basics / 13 - Case Expressions";
  version = 12;
  module_name = "TuGen_Basics13CaseExpressions";
  prompt = {x|Case expressions let you pattern match on a value.

The syntax is:
```hazelnostatics
case expr
| pattern1 => result1
| pattern2 => result2
| _ => default
end
```

Example:
```hazel
let describe_pair = fun pair : (Int, Int) -> 
case pair
| (0, 0) => "Both zero"
| (0, y) => "First zero, second " ++ string_of_int(y)
| (x, 0) => "Second zero, first " ++ string_of_int(x)
| (1, 2) => "One and two"
| _ => "Default"
end
in
map([(0,0), (0, 1), (1, 0), (1, 2), (3, 4)], describe_pair)
```


Hazel checks each pattern from top to bottom and evaluates the result of the first matching branch. You can use `_` as a wildcard pattern that matches anything.

# Task

Complete the function `process_string_pair` below. It takes a pair of strings `(a, b)` where `a` is a directive and `b` is the target string to process.

The function should behave as follows:
- If `a` is `"pre"`, return the first 3 characters of `b`.
- If `a` is `"post"`, return `b` without its first 3 characters.
- Otherwise, return `b` unchanged.

Assume `b` is always at least 3 characters long.

**Example:**
```hazelnostatics
process_string_pair(("pre", "hazel")) == "haz";
process_string_pair(("post", "hazel")) == "el";
process_string_pair(("other", "hazel")) == "hazel"
```|x};
  display_hint = {x|Use the string_sub(str, start, len) function to get a substring|x};
  task_reference = {x|### Case Expression
   ```hazel
   case 1
   | 0 => "zero"
   | 1 => "one"
   | _ => "other"
   end
   ```
   `_` is a wildcard that matches anything.

   ---

   Pattern matching can also destructure values:
   ```hazel
   case (1, "hello")
   | (0, _) => "zero and something"
   | (n, s) =>
  "number "
  ++ string_of_int(n)
  ++ " and string "
  ++ s
   end
   ```
   

### Useful functions
```hazelnostatics
string_sub : (String, Int, Int) -> String
```
```hazelnostatics
string_length : String -> Int
```

---

```hazel
string_sub("012345", 2, 3)
```
```hazel
string_length("012345")
```|x};
  your_impl =
    Haz3lcore.Zipper.caret_to_start (Option.get (Haz3lcore.TextRoundtrip.of_text ~root:Exp {x|let process_string_pair : (String, String) -> String = fun p ->
case p
end
in
process_string_pair("pre", "hazel")|x}));
  hidden_tests =
    {
      tests =
        Option.get (Haz3lcore.TextRoundtrip.of_text ~root:Exp {x|test process_string_pair("pre", "hazel") == "haz" end;
test process_string_pair("post", "hazel") == "el" end;
test process_string_pair("other", "hazel") == "hazel" end|x});
      hints = ["process_string_pair(\"pre\", \"hazel\") should be \"haz\""; "process_string_pair(\"post\", \"hazel\") should be \"el\""; "process_string_pair(\"other\", \"hazel\") should be \"hazel\""];
    };
  wrapper = false;
  show_report = true;
}
