(* Auto-generated by: ./hazel gen-tutorial -- DO NOT EDIT *)
(* Source: hazel-programs/tutorial/conjoined/10-functions-and-many-samples.hz *)

let exercise : Tutorial.spec =
  {
    id =
      Option.get (Haz3lcore.Id.of_string "b0000008-0008-0008-0008-000000000008");
    title = "10 - Functions And Many Samples";
    version = 1;
    module_name = "TuGen_10FunctionsAndManySamples";
    prompt =
      {x|So far, probes have either had one sample (top level expressions), or zero samples (conditional branch not taken). Probes in functions however collect one sample *per call*.

`watering_amount` adjusts a base amount by the moon phase. It is called three times below.

A **Samples** toggle just appeared at the top of the Task Reference panel; the controls there grow as new commands show up.

**Try this**
1. Probe the function's body: put your cursor on `case` and add a probe.
2. Notice that the sample shown, `220`, now has arrows to the left. You can click on the right arrow to cycle through the 2 other samples, and the left arrow to go back. Alternatively, click on the sample itself, and use **←/→** on your keyboard to step between them.
3. Now, press **Space** (or flip the **Samples** toggle at the top of the sidebar) for *many* mode to see all three at once. Space again to go back.
4. Now, finish the third call (`watering_amount(50, Waning)`) so all three run to completion.|x};
    display_hint =
      {x|Finish the third call: `watering_amount(50, Waning)`. Then probe the `case` and use ←/→.|x};
    task_reference =
      {x|### Probes
- **Add / remove a probe**: Cmd/Ctrl+E, or right-click then *Add probe*
- **Many calls**: one sample per call. ←/→ to step, **Space** for all at once.|x};
    your_impl =
      Haz3lcore.Zipper.caret_to_start
        (Option.get
           (Haz3lcore.TextRoundtrip.of_text ~root:Exp
              {x|type MoonPhase = New + Waxing + Full + Waning in
let watering_amount(base: Int, phase: MoonPhase): Int =
case phase
| New => base + 50
| Full => base - 30
| _ => base
end
in
watering_amount(250, Full);
watering_amount(180, New);
watering_amount(50, ¿)|x}));
    hidden_tests =
      {
        tests =
          Option.get
            (Haz3lcore.TextRoundtrip.of_text ~root:Exp
               {x|test answer == 50 end|x});
        hints = [];
      };
    wrapper = false;
    show_report = true;
  }
