(* Auto-generated by: ./hazel gen-tutorial -- DO NOT EDIT *)
(* Source: hazel-programs/tutorial/conjoined/25-tasks-ahead.hz *)

let exercise : Tutorial.spec =
  {
    id =
      Option.get (Haz3lcore.Id.of_string "b0000026-0026-0026-0026-000000000026");
    title = "25 - Tasks Ahead";
    version = 1;
    module_name = "TuGen_25TasksAhead";
    prompt =
      {x|{{no_editor}}
# The tasks ahead

That is the end of the guided part. What follows are real tasks: some **writing** (build a function to a spec), some **debugging** (a working program with one bug and one FAILING test that knows it).

A few things to expect:

- **The tests are the goal.** Each task shows a 🤔 face until its tests pass, then 🤩. The tests in the editor are the spec; read them early.
- **Debugging tasks have a route.** The sidebar suggests one: read the top comments, then the Model type, then the Action type, then find the test marked FAILING. After that, investigate your way.
- **Probes are a menu, not a script.** Manual probes, auto-probe, many mode, pin, step into, the variable dropdown: use whatever answers the question you actually have. There is no correct combination.
- **Think out loud.** Say what you expect before you look, and what surprised you after. Wrong guesses are the most useful thing you can give us.

On a few tasks probes will be switched off; you still have `print`, the tests, and your eyes. That contrast is part of what we are studying.

Take your time. Ask anything.|x};
    display_hint = {x||x};
    task_reference = {x||x};
    your_impl =
      Haz3lcore.Zipper.caret_to_start
        (Haz3lcore.PersistentZipper.unpersist ~root:Exp
           {
             Haz3lcore.PersistentZipper.zipper =
               {x|((selection((focus Left)(content())(mode Normal)))(relatives((siblings(((Tile((id 9cdfe8b6-2c9f-4688-9db3-af3e901fad70)(label(0))(mold((out Exp)(in_())(nibs(((shape Convex)(sort Exp))((shape Convex)(sort Exp))))))(shards(0))(children()))))()))(ancestors())))(caret Outer)(refractors((manuals())(multis((ids())(suppressed())(ephemerals())))(sample_focus((call_stack())(index -1)(pinned_stack())(indicated_call())(time())(seq 0)(step_range())(pending_focus())))(autoprobe_target())(pending_probe_cursor()))))|x};
             backup_text = {x|0|x};
           });
    hidden_tests =
      {
        tests =
          Haz3lcore.PersistentZipper.unpersist ~root:Exp
            {
              Haz3lcore.PersistentZipper.zipper =
                {x|((selection((focus Left)(content())(mode Normal)))(relatives((siblings(((Tile((id 5ea7e602-eb50-4340-9a73-5609d6662cd0)(label(test end))(mold((out Exp)(in_(Exp))(nibs(((shape Convex)(sort Exp))((shape Convex)(sort Exp))))))(shards(0 1))(children(((Secondary((id 5cd5570d-ed40-46ec-950e-e1f978d1961e)(content(Whitespace" "))))(Tile((id c991e955-5330-4ac3-bcaa-60a45cd2473e)(label(true))(mold((out Exp)(in_())(nibs(((shape Convex)(sort Exp))((shape Convex)(sort Exp))))))(shards(0))(children())))(Secondary((id ab69f87c-3be7-4a34-af00-7711527a422e)(content(Whitespace" "))))))))))()))(ancestors())))(caret Outer)(refractors((manuals())(multis((ids())(suppressed())(ephemerals())))(sample_focus((call_stack())(index -1)(pinned_stack())(indicated_call())(time())(seq 0)(step_range())(pending_focus())))(autoprobe_target())(pending_probe_cursor()))))|x};
              backup_text = {x|test true end|x};
            };
        hints = [];
      };
    wrapper = false;
    show_report = false;
  }
