(* Auto-generated by: ./hazel gen-tutorial -- DO NOT EDIT *)
(* Source: hazel-programs/tutorial/conjoined/01-arithmetic-and-holes.hz *)

let exercise : Tutorial.spec = {
  id = Option.get (Haz3lcore.Id.of_string "b0000001-0001-0001-0001-000000000001");
  title = "01 - Arithmetic And Holes";
  version = 1;
  module_name = "TuGen_01ArithmeticAndHoles";
  prompt = {x|Hazel is a live functional environment. Every edit maintains program structure, and evaluation proceeds *around* holes (the hexagons), so there is always a result to look at, which may be a value or a partially evaluated program.

Check on this program's evaluation with a **probe**: put your caret on the `+` token and press **Cmd/Ctrl+E** (or right-click, *Add probe*). The program's value appears at the end of the line: Hazel computed everything around the missing piece.

Probe commands are listed in the **Quick Reference** in the sidebar; new ones are highlighted.

# Task

A nightshade plant drinks 125 ml twice a day, plus a 50 ml weekly top-up. 

1. Fill the hole with the number of days in a week. Watch the probe; it should read **1800**.|x};
  display_hint = {x|A week is 7 days.|x};
  task_reference = {x|### Holes
Hexagons are holes. Hazel evaluates around them. Fill one by typing a value.

### Integer operations
`(+ - * /)`|x};
  your_impl =
    Haz3lcore.Zipper.caret_to_start
      (Haz3lcore.PersistentZipper.unpersist ~root:Exp
  { Haz3lcore.PersistentZipper.zipper = {x|((selection((focus Left)(content())(mode Normal)(anchor_caret Outer)(smart_rounded false)))(relatives((siblings(((Tile((id 462e445e-8e13-4d3b-92e5-52ec758c9742)(label(2))(mold((out Exp)(in_())(nibs(((shape Convex)(sort Exp))((shape Convex)(sort Exp))))))(shards(0))(children())))(Secondary((id 0060d304-1951-4355-a295-1336a9426231)(content(Whitespace" "))))(Tile((id 799168af-ea5e-4687-8abc-270c2f20cd92)(label(*))(mold((out Exp)(in_())(nibs(((shape(Concave 27))(sort Exp))((shape(Concave 27))(sort Exp))))))(shards(0))(children())))(Secondary((id e1400e75-ae02-40ed-a2aa-5e8a048a8151)(content(Whitespace" "))))(Tile((id 67ca98db-2344-47ee-adda-929907d52d28)(label(125))(mold((out Exp)(in_())(nibs(((shape Convex)(sort Exp))((shape Convex)(sort Exp))))))(shards(0))(children())))(Secondary((id cfad8814-158f-48a8-803d-49d0aba4ea64)(content(Whitespace" "))))(Tile((id cf688099-a9a7-448b-aa27-4e283221d8cd)(label(*))(mold((out Exp)(in_())(nibs(((shape(Concave 27))(sort Exp))((shape(Concave 27))(sort Exp))))))(shards(0))(children())))(Secondary((id f88ac8ba-f8d3-4137-9a39-1c904ad52119)(content(Whitespace" ")))))((Grout((id 3d428e79-962c-4481-947a-e76fce21fada)(shape Convex)))(Secondary((id eeec44fd-6b7e-4af5-8c73-0cf899eb20a0)(content(Whitespace" "))))(Tile((id cc961b9b-71ba-4857-9057-b59a91e0e55a)(label(+))(mold((out Exp)(in_())(nibs(((shape(Concave 28))(sort Exp))((shape(Concave 28))(sort Exp))))))(shards(0))(children())))(Secondary((id d9afbb91-388f-4117-8c49-d30a8c8af7c8)(content(Whitespace" "))))(Tile((id b2977199-ac70-48a4-9795-4b6a70d40ec2)(label(50))(mold((out Exp)(in_())(nibs(((shape Convex)(sort Exp))((shape Convex)(sort Exp))))))(shards(0))(children()))))))(ancestors())))(caret Outer)(refractors((manuals())(multis((ids())(suppressed())(ephemerals())))(sample_focus((call_stack())(index -1)(pinned_stack())(indicated_call())(time())(seq 0)(step_range())(pending_focus())))(autoprobe_target())(pending_probe_cursor()))))|x};
    backup_text = {x|2 * 125 *  + 50|x} });
  hidden_tests =
    {
      tests =
        (Haz3lcore.PersistentZipper.unpersist ~root:Exp
  { Haz3lcore.PersistentZipper.zipper = {x|((selection((focus Left)(content())(mode Normal)(anchor_caret Outer)(smart_rounded false)))(relatives((siblings(((Tile((id 5facda7f-2f2f-4d99-818a-cbf061f19576)(label(test end))(mold((out Exp)(in_(Exp))(nibs(((shape Convex)(sort Exp))((shape Convex)(sort Exp))))))(shards(0 1))(children(((Secondary((id 39e34b5f-59e9-4a94-8e52-650678899846)(content(Whitespace" "))))(Tile((id e8775916-2bbf-4aa4-960e-2d4343fdc1ec)(label(answer))(mold((out Exp)(in_())(nibs(((shape Convex)(sort Exp))((shape Convex)(sort Exp))))))(shards(0))(children())))(Secondary((id e253a882-3e13-4242-b1ac-9c83f134792e)(content(Whitespace" "))))(Tile((id 86b19373-b8cc-4309-ac01-3506907c6a11)(label(==))(mold((out Exp)(in_())(nibs(((shape(Concave 31))(sort Exp))((shape(Concave 31))(sort Exp))))))(shards(0))(children())))(Secondary((id a39166b0-9ac0-42a0-b16e-01f72f22d645)(content(Whitespace" "))))(Tile((id d9f92412-5c3e-449e-84c6-8c6a63a482bf)(label(1800))(mold((out Exp)(in_())(nibs(((shape Convex)(sort Exp))((shape Convex)(sort Exp))))))(shards(0))(children())))(Secondary((id 7bb226c4-fd02-4ec2-bad9-a4f3a7d38bc5)(content(Whitespace" "))))))))))()))(ancestors())))(caret Outer)(refractors((manuals())(multis((ids())(suppressed())(ephemerals())))(sample_focus((call_stack())(index -1)(pinned_stack())(indicated_call())(time())(seq 0)(step_range())(pending_focus())))(autoprobe_target())(pending_probe_cursor()))))|x};
    backup_text = {x|test answer == 1800 end|x} });
      hints = ["Fill the hole appropriately."];
    };
  wrapper = true;
  show_report = true;
}
