(* Auto-generated by: ./hazel gen-tutorial -- DO NOT EDIT *)
(* Source: hazel-programs/tutorial/conjoined/01-arithmetic-and-holes.hz *)

let exercise : Tutorial.spec =
  {
    id =
      Option.get (Haz3lcore.Id.of_string "b0000001-0001-0001-0001-000000000001");
    title = "01 - Arithmetic And Holes";
    version = 1;
    module_name = "TuGen_01ArithmeticAndHoles";
    prompt =
      {x|Hazel is a live functional environment. Every edit maintains program structure, and evaluation proceeds *around* holes (the hexagons), so there is always a result to look at, which may be a value or a partially evaluated program.

Check on this program's evaluation with a **probe**: put your caret on the `+` token and press **Cmd/Ctrl+E** (or right-click, *Add probe*). The program's value appears at the end of the line: Hazel computed everything around the missing piece.

Probe commands are listed in the **Quick Reference** in the sidebar; new ones are highlighted.

# Task

A nightshade plant drinks 125 ml twice a day, plus a 50 ml weekly top-up. 

1. Fill the hole with the number of days in a week. Watch the probe; it should read **1800**.|x};
    display_hint = {x|A week is 7 days.|x};
    task_reference =
      {x|### Holes
Hexagons are holes. Hazel evaluates around them. Fill one by typing a value.

### Integer operations
`(+ - * /)`|x};
    your_impl =
      Haz3lcore.Zipper.caret_to_start
        (Haz3lcore.PersistentZipper.unpersist ~root:Exp
           {
             Haz3lcore.PersistentZipper.zipper =
               {x|((selection((focus Left)(content())(mode Normal)))(relatives((siblings(((Tile((id d71080fd-2dd9-47e2-bca4-51ef4c348f04)(label(2))(mold((out Exp)(in_())(nibs(((shape Convex)(sort Exp))((shape Convex)(sort Exp))))))(shards(0))(children())))(Secondary((id b9d2b23a-14d1-4b9b-b531-7c57eb5b7cbb)(content(Whitespace" "))))(Tile((id f49fdcd4-5520-4508-bfbf-9f01a8be6618)(label(*))(mold((out Exp)(in_())(nibs(((shape(Concave 27))(sort Exp))((shape(Concave 27))(sort Exp))))))(shards(0))(children())))(Secondary((id 5b9915ca-1fff-4e2e-a226-29ce5059c2d7)(content(Whitespace" "))))(Tile((id cbb990d3-01e6-4550-bc49-0e9d721bd687)(label(125))(mold((out Exp)(in_())(nibs(((shape Convex)(sort Exp))((shape Convex)(sort Exp))))))(shards(0))(children())))(Secondary((id 84ab4610-48d4-4c58-bd97-d3036602971c)(content(Whitespace" "))))(Tile((id a981e16b-53e7-4a01-aa78-76807c972eb0)(label(*))(mold((out Exp)(in_())(nibs(((shape(Concave 27))(sort Exp))((shape(Concave 27))(sort Exp))))))(shards(0))(children())))(Secondary((id d18a2649-5d64-4cb1-aa5c-99ef5165eb6b)(content(Whitespace" ")))))((Grout((id e643e81d-fc5b-426a-9559-47d2c8209809)(shape Convex)))(Secondary((id ee07c16a-7cc8-441f-ab41-71e3e540e626)(content(Whitespace" "))))(Tile((id 7ede10da-2432-4527-8b70-bc73eecec1fa)(label(+))(mold((out Exp)(in_())(nibs(((shape(Concave 28))(sort Exp))((shape(Concave 28))(sort Exp))))))(shards(0))(children())))(Secondary((id 2d90cf9c-eae5-4615-98ed-d34ff16be546)(content(Whitespace" "))))(Tile((id 8805f927-2481-48e3-90cf-7fd1d8f478bb)(label(50))(mold((out Exp)(in_())(nibs(((shape Convex)(sort Exp))((shape Convex)(sort Exp))))))(shards(0))(children()))))))(ancestors())))(caret Outer)(refractors((manuals())(multis((ids())(suppressed())(ephemerals())))(sample_focus((call_stack())(index -1)(pinned_stack())(indicated_call())(time())(seq 0)(step_range())(pending_focus())))(autoprobe_target())(pending_probe_cursor()))))|x};
             backup_text = {x|2 * 125 *  + 50|x};
           });
    hidden_tests =
      {
        tests =
          Haz3lcore.PersistentZipper.unpersist ~root:Exp
            {
              Haz3lcore.PersistentZipper.zipper =
                {x|((selection((focus Left)(content())(mode Normal)))(relatives((siblings(((Tile((id 86b2f102-fabf-419f-90df-cd019fb75734)(label(test end))(mold((out Exp)(in_(Exp))(nibs(((shape Convex)(sort Exp))((shape Convex)(sort Exp))))))(shards(0 1))(children(((Secondary((id d4d19b6d-aa08-4dc4-9d8f-51ca58e7932a)(content(Whitespace" "))))(Tile((id bcec43f3-3970-451d-adaa-8ec97fba6345)(label(answer))(mold((out Exp)(in_())(nibs(((shape Convex)(sort Exp))((shape Convex)(sort Exp))))))(shards(0))(children())))(Secondary((id 61a32dd7-02b3-440e-bd82-d5110347eb04)(content(Whitespace" "))))(Tile((id 5fdb8755-ed8d-43b5-a5a6-baa576e3e3f6)(label(==))(mold((out Exp)(in_())(nibs(((shape(Concave 31))(sort Exp))((shape(Concave 31))(sort Exp))))))(shards(0))(children())))(Secondary((id 926d826b-10a5-46a9-9381-a349bf0cb16d)(content(Whitespace" "))))(Tile((id 9a8dd0d1-3b63-4d62-86ea-b540c850d69b)(label(1800))(mold((out Exp)(in_())(nibs(((shape Convex)(sort Exp))((shape Convex)(sort Exp))))))(shards(0))(children())))(Secondary((id c320c478-fe15-43f2-be0b-09183e8625d1)(content(Whitespace" "))))))))))()))(ancestors())))(caret Outer)(refractors((manuals())(multis((ids())(suppressed())(ephemerals())))(sample_focus((call_stack())(index -1)(pinned_stack())(indicated_call())(time())(seq 0)(step_range())(pending_focus())))(autoprobe_target())(pending_probe_cursor()))))|x};
              backup_text = {x|test answer == 1800 end|x};
            };
        hints = [ "Fill the hole appropriately." ];
      };
    wrapper = true;
    show_report = true;
  }
