(* Auto-generated by: ./hazel gen-tutorial -- DO NOT EDIT *)
(* Source: hazel-programs/tutorial/conjoined/01-arithmetic-and-holes.hz *)

let exercise : Tutorial.spec =
  {
    id =
      Option.get (Haz3lcore.Id.of_string "b0000001-0001-0001-0001-000000000001");
    title = "01 - Arithmetic And Holes";
    version = 1;
    module_name = "TuGen_01ArithmeticAndHoles";
    prompt =
      {x|Hazel is a live functional environment. Every edit maintains program structure, and evaluation proceeds *around* holes (the hexagons), so there is always a result to look at, which may be a value or a partially evaluated program.

Let's check on the evaluation of this program using a **probe**: put your cursor on the `+` and press **Cmd/Ctrl+E** (or right-click, *Add probe*). The program's value appears right there, hole and all: Hazel computed everything around the missing piece.

# Task

These slides are loosely themed as parts of a simulation video game, Night Gardener.
A nightshade plant drinks 125 ml twice a day, plus a 50 ml weekly top-up. Fill the hole and watch the probe; you are done when it reads **1800**.|x};
    display_hint = {x|A week is 7 days.|x};
    task_reference =
      {x|### Holes
Hexagons are holes. Hazel evaluates around them. Fill one by typing a value.

### Integer operations
`(+ - * /)`

### Probes
- **Add / remove a probe**: Cmd/Ctrl+E, or right-click then *Add probe*|x};
    your_impl =
      Haz3lcore.Zipper.caret_to_start
        (Haz3lcore.PersistentZipper.unpersist ~root:Exp
           {
             Haz3lcore.PersistentZipper.zipper =
               {x|((selection((focus Left)(content())(mode Normal)))(relatives((siblings(((Tile((id 7126c00f-6d80-4ac5-be37-118776e0890f)(label(2))(mold((out Exp)(in_())(nibs(((shape Convex)(sort Exp))((shape Convex)(sort Exp))))))(shards(0))(children())))(Secondary((id f4ee0078-b37d-4c36-acce-00a136febab0)(content(Whitespace" "))))(Tile((id 611e9a43-ab87-4c60-91a5-c3089bb85495)(label(*))(mold((out Exp)(in_())(nibs(((shape(Concave 27))(sort Exp))((shape(Concave 27))(sort Exp))))))(shards(0))(children())))(Secondary((id 43da9fd5-89f4-481d-a766-413af1e6341e)(content(Whitespace" "))))(Tile((id 7f7f8c85-031c-48d2-8d07-0d6159d9ff77)(label(125))(mold((out Exp)(in_())(nibs(((shape Convex)(sort Exp))((shape Convex)(sort Exp))))))(shards(0))(children())))(Secondary((id 128c6bc9-7f1d-4886-bd91-f9b209dc6b02)(content(Whitespace" "))))(Tile((id 241bd49c-6d8a-4a62-b102-3b768adb642a)(label(*))(mold((out Exp)(in_())(nibs(((shape(Concave 27))(sort Exp))((shape(Concave 27))(sort Exp))))))(shards(0))(children())))(Secondary((id 63732379-6782-4738-af67-a2723adccbe7)(content(Whitespace" ")))))((Grout((id 231dcb10-83d3-4014-aec4-4b4233eb00bd)(shape Convex)))(Secondary((id 6cff7429-b35c-46ed-af27-7a7c72559f0a)(content(Whitespace" "))))(Tile((id b78db622-7284-4043-bbff-df6dd4c864ba)(label(+))(mold((out Exp)(in_())(nibs(((shape(Concave 28))(sort Exp))((shape(Concave 28))(sort Exp))))))(shards(0))(children())))(Secondary((id 39ee04f9-b6a1-45bd-9e9a-35c71a27644e)(content(Whitespace" "))))(Tile((id e83b628e-29d1-480e-97fd-3dcbd4c377b7)(label(50))(mold((out Exp)(in_())(nibs(((shape Convex)(sort Exp))((shape Convex)(sort Exp))))))(shards(0))(children()))))))(ancestors())))(caret Outer)(refractors((manuals())(multis((ids())(suppressed())(ephemerals())))(sample_focus((call_stack())(index -1)(pinned_stack())(indicated_call())(time())(seq 0)(step_range())(pending_focus())))(autoprobe_target())(pending_probe_cursor()))))|x};
             backup_text = {x|2 * 125 *  + 50|x};
           });
    hidden_tests =
      {
        tests =
          Haz3lcore.PersistentZipper.unpersist ~root:Exp
            {
              Haz3lcore.PersistentZipper.zipper =
                {x|((selection((focus Left)(content())(mode Normal)))(relatives((siblings(((Tile((id 93ed1992-9434-4623-bf23-1f082b9e630d)(label(test end))(mold((out Exp)(in_(Exp))(nibs(((shape Convex)(sort Exp))((shape Convex)(sort Exp))))))(shards(0 1))(children(((Secondary((id a331dd7c-8eca-4fb5-8524-da15606d2da2)(content(Whitespace" "))))(Tile((id de38dd84-ff8e-464f-b30d-162954e9451a)(label(answer))(mold((out Exp)(in_())(nibs(((shape Convex)(sort Exp))((shape Convex)(sort Exp))))))(shards(0))(children())))(Secondary((id 1005ae05-af9d-49cb-a5d7-2dbc0d92f573)(content(Whitespace" "))))(Tile((id bb111f7e-b94b-41e3-9ad5-437bf83515a4)(label(==))(mold((out Exp)(in_())(nibs(((shape(Concave 31))(sort Exp))((shape(Concave 31))(sort Exp))))))(shards(0))(children())))(Secondary((id 8c253398-227d-4312-a39a-70866b467b99)(content(Whitespace" "))))(Tile((id b4f88994-1068-4d72-a19d-9579e2c50912)(label(1800))(mold((out Exp)(in_())(nibs(((shape Convex)(sort Exp))((shape Convex)(sort Exp))))))(shards(0))(children())))(Secondary((id 3c4cca08-ba07-40da-9dec-a56f449844c1)(content(Whitespace" "))))))))))()))(ancestors())))(caret Outer)(refractors((manuals())(multis((ids())(suppressed())(ephemerals())))(sample_focus((call_stack())(index -1)(pinned_stack())(indicated_call())(time())(seq 0)(step_range())(pending_focus())))(autoprobe_target())(pending_probe_cursor()))))|x};
              backup_text = {x|test answer == 1800 end|x};
            };
        hints = [ "Fill the hole appropriately." ];
      };
    wrapper = true;
    show_report = true;
  }
