(* Auto-generated by: ./hazel gen-tutorial -- DO NOT EDIT *)
(* Source: hazel-programs/tutorial/conjoined/02-parser-and-backpack.hz *)

let exercise : Tutorial.spec =
  {
    id =
      Option.get (Haz3lcore.Id.of_string "b0000002-0002-0002-0002-000000000002");
    title = "02 - Parser And Backpack";
    version = 1;
    module_name = "TuGen_02ParserAndBackpack";
    prompt =
      {x|Hazel's parser helps you complete incomplete syntax. When you start a multi-token form like `let ... in`, the delimiters you still owe wait in the *backpack*, shown in yellow above the cursor.

A `let` binds a name for use in the rest of the program:
```hazelnostatics
let x = expr in
body
```

**Try this**
1. Fill the definition expression (after the `=`) with `250 * 7`.
2. Type `in`, and watch it leave the backpack. Backspace it, then press `Tab` to drop it from the backpack instead. Either way works.
3. Finish the body so the whole program reads `let weekly = 250 * 7 in weekly`.
4. Probe `weekly` on the last line (**Cmd/Ctrl+E**): it should read **1750**.|x};
    display_hint = {x||x};
    task_reference =
      {x|### Let
```hazel
let a = 1 in
a
```

### Backpack
- `Tab` drops the next delimiter
- typing it (e.g. `in`) also works

### Probes
- **Add / remove a probe**: Cmd/Ctrl+E, or right-click then *Add probe*|x};
    your_impl =
      Haz3lcore.Zipper.caret_to_start
        (Haz3lcore.PersistentZipper.unpersist ~root:Exp
           {
             Haz3lcore.PersistentZipper.zipper =
               {x|((selection((focus Left)(content())(mode Normal)))(relatives((siblings(((Tile((id cfdc33cb-af54-4a48-a7f2-1419b356e60f)(label(let = in))(mold((out Exp)(in_(Pat Exp))(nibs(((shape Convex)(sort Exp))((shape(Concave 45))(sort Exp))))))(shards(0 1))(children(((Secondary((id ee5f0a73-bf6d-4e67-9f0c-56594317bc68)(content(Whitespace" "))))(Tile((id 031ab63b-8dbe-4546-bd45-b5c8c9d456f0)(label(weekly))(mold((out Pat)(in_())(nibs(((shape Convex)(sort Pat))((shape Convex)(sort Pat))))))(shards(0))(children())))(Secondary((id a80fa832-2a77-4331-8f43-9f6336f003cb)(content(Whitespace" ")))))))))(Secondary((id 363ec0cb-2d10-4528-bd72-df9cdd36b46f)(content(Whitespace" ")))))((Grout((id 62f66552-cd06-43d1-9cad-a4156a48bd5c)(shape Convex))))))(ancestors())))(caret Outer)(refractors((manuals())(multis((ids())(suppressed())(ephemerals())))(sample_focus((call_stack())(index -1)(pinned_stack())(indicated_call())(time())(seq 0)(step_range())(pending_focus())))(autoprobe_target())(pending_probe_cursor()))))|x};
             backup_text = {x|let weekly = |x};
           });
    hidden_tests =
      {
        tests =
          Haz3lcore.PersistentZipper.unpersist ~root:Exp
            {
              Haz3lcore.PersistentZipper.zipper =
                {x|((selection((focus Left)(content())(mode Normal)))(relatives((siblings(((Tile((id bf42c22c-9858-4584-a93f-44c48c5e7a89)(label(test end))(mold((out Exp)(in_(Exp))(nibs(((shape Convex)(sort Exp))((shape Convex)(sort Exp))))))(shards(0 1))(children(((Secondary((id 5f1caaf8-4434-47fd-acdd-025a48b3bb47)(content(Whitespace" "))))(Tile((id b8b60f31-76a5-4736-bb63-5b7bc290281b)(label(answer))(mold((out Exp)(in_())(nibs(((shape Convex)(sort Exp))((shape Convex)(sort Exp))))))(shards(0))(children())))(Secondary((id da5f5173-a08f-4cba-ab90-782ec25366b6)(content(Whitespace" "))))(Tile((id b3f77dff-7e9c-496f-98f5-adfe03412ce9)(label(==))(mold((out Exp)(in_())(nibs(((shape(Concave 31))(sort Exp))((shape(Concave 31))(sort Exp))))))(shards(0))(children())))(Secondary((id 1cf4f8d8-1791-4f71-bcb6-bd2f09a8f5d7)(content(Whitespace" "))))(Tile((id 50821318-e633-4b4e-a41e-6ca9c1f2dd0c)(label(1750))(mold((out Exp)(in_())(nibs(((shape Convex)(sort Exp))((shape Convex)(sort Exp))))))(shards(0))(children())))(Secondary((id 27e835ef-887f-4782-9b83-78e22a7eecf1)(content(Whitespace" ")))))))))(Tile((id b13ad03f-d623-4fcb-99ff-68900631b268)(label(";"))(mold((out Exp)(in_())(nibs(((shape(Concave 35))(sort Exp))((shape(Concave 35))(sort Exp))))))(shards(0))(children())))(Secondary((id 0d7bc691-2094-464e-a311-5dc77a7ec75b)(content(Whitespace"\n")))))((Grout((id 4d9df5ea-a2c6-4000-92aa-59520210c348)(shape Convex))))))(ancestors())))(caret Outer)(refractors((manuals())(multis((ids())(suppressed())(ephemerals())))(sample_focus((call_stack())(index -1)(pinned_stack())(indicated_call())(time())(seq 0)(step_range())(pending_focus())))(autoprobe_target())(pending_probe_cursor()))))|x};
              backup_text = {x|test answer == 1750 end;
|x};
            };
        hints = [ "Build `let weekly = 250 * 7 in weekly`." ];
      };
    wrapper = true;
    show_report = true;
  }
