(* Auto-generated by: ./hazel gen-tutorial -- DO NOT EDIT *)
(* Source: hazel-programs/tutorial/conjoined/11-aligning-samples.hz *)

let exercise : Tutorial.spec =
  {
    id =
      Option.get (Haz3lcore.Id.of_string "b0000009-0009-0009-0009-000000000009");
    title = "11 - Aligning Samples";
    version = 1;
    module_name = "TuGen_11AligningSamples";
    prompt =
      {x|With probes in several places, Hazel keeps the samples *aligned* to one call at a time. The sample you click is the **focus**, and the others line up with it.

First, finish the function: it returns `base + adjust`.

**Try this**
1. This time, instead place a **multi-probe** on the function definition: put your cursor on `let` and add a probe. Recall that this will add a probe for each line in the definition.
2. Click one call's sample. The `adjust` sample lines up with that same call and turns **green**: green means it is from that same run of the function.
3. A **⊖** marks a sample that exists but is not aligned to your focus. Click a ⊖ to align to it instead.
4. Using the sample information you see, try to answer the following question: When the `phase` is `New`, what is the value of `base + adjust`? You likely want to use the arrow keys on the `phase` sample (in single-sample mode), or switch to *many* mode (double-click any sample, click a sample and press **Space**, or flip the **Samples** toggle above).|x};
    display_hint =
      {x|The function returns `base + adjust`. Then probe `adjust` and a call, and click between the call samples.|x};
    task_reference =
      {x|### Probes
- **Focus**: the sample you click; others align to it
- **⊖**: a sample exists but is not aligned to the focus. Click it to align.|x};
    your_impl =
      Haz3lcore.Zipper.caret_to_start
        (Option.get
           (Haz3lcore.TextRoundtrip.of_text ~root:Exp
              {x|type MoonPhase = New + Waxing + Full + Waning in
let watering_amount(
base: Int,
phase: MoonPhase): Int =
let adjust =
case phase
| New => 50
| Full => 0 - 30
| _ => 0
end
in
¿
in
watering_amount(250, Full);
watering_amount(180, New);
watering_amount(50, Waning)|x}));
    hidden_tests =
      {
        tests =
          Option.get
            (Haz3lcore.TextRoundtrip.of_text ~root:Exp
               {x|test answer == 50 end|x});
        hints = [];
      };
    wrapper = false;
    show_report = true;
  }
