(* Auto-generated by: ./hazel gen-tutorial -- DO NOT EDIT *)
(* Source: hazel-programs/tutorial/archive/22-labeled-tuple-list-conversions.hz *)

let exercise : Tutorial.spec = {
  id = Option.get (Haz3lcore.Id.of_string "e6334292-295b-4d50-bbaf-f762cc6fd351");
  title = "Archive / 22 - Labeled Tuple List Conversions";
  version = 1;
  module_name = "TuGen_Archive22LabeledTupleListConversions";
  prompt = {x|To aid in the dynamic processing and generation of labeled tuples, Hazel provides two operations for converting between labeled tuples and lists.

### to_lvs : ? -> [(label=String, value=?)]
Turns a labeled tuple into a list of label/value pairs.

```hazel
let t = (length=3, width=5, height=7) in
to_lvs(t)
```

If the types of the values are consistent, this will give the combined type of all the values; otherwise it falls back to the unknown type `?`.

### from_lvs : [(label=String, value=?)] -> ?
The inverse of `to_lvs`. Takes a list of label/value pairs and returns a labeled tuple.

```hazel
let dimensions : [(label=String, value=Int)] = 
[(label="width", value=3), (label="depth", value=2), (label="time", value=9)]
in
from_lvs(dimensions)
```


### Gradually typed

Because Hazel is gradually typed and has the unknown type `?` (a type hole represented by a hexagon), lists with inconsistent element types can be used to build a labeled tuple with inconsistent values dynamically.

```hazel
let attributes : [(label=String, value= )] = [(label="first_name", value="George"), (label="last_name", value="Patel"), (label="age", value=32)] in
from_lvs(attributes)

```


### Unknown type for arbitrary tuples

Hazel does not provide a way to give an arbitrary tuple a concrete type annotation, so the `t` parameter uses the unknown type `?` — similar to `any` in TypeScript or `Any` in Python. The update function `fn` similarly takes `?` and returns `?` for the same reason.

# Task

Implement the function:

```hazelnostatics
update_entry : (?, String -> Bool, (? -> ?)) -> ?
```

`update_entry(tuple, label_predicate, update_fn)`:
- `tuple` — a labeled tuple (typed as `?`).
- `label_predicate` — a function `String -> Bool` that determines which labels should be updated.
- `update_fn` — a function `? -> ?` applied to the values of all matching entries.

Apply `update_fn` to every value whose label satisfies `label_predicate`.

**Example:**
```hazelnostatics
update_entry((apple=1, pear=2, avocado=3),
             string_match("^a", _),
             fun i -> i + 1)
== (apple=2, pear=2, avocado=4)
```
where `string_match("^a", _)` is a predicate that matches any string starting with `a`.|x};
  display_hint = {x|Convert the tuple to a list, map over the list to update the relevant entries, then turn it back into a tuple|x};
  task_reference = {x|### to_lvs
```hazelnostatics
to_lvs : ? -> [
(label=String, value=?)
]
```

---

Convert a record to a list of label-value pairs:
```hazel
to_lvs(
  (first="John", last="Doe")
)
```

### from_lvs
```hazelnostatics
from_lvs : [
(label=String, value=?)
] -> ?
```

---

Convert a list of label-value pairs back into a record:
```hazel
from_lvs([
(label="x", value=1),
(label="y", value=2)
])
```

### map
```hazelnostatics
map : ([T], T -> U) -> [U]
```

---

Apply a function to each element:
```hazel
map([1, 2, 3], fun x -> x + 1)
```


### Reverse function application and pipelining

```hazel
5
|> (fun x -> x * 2)
|> (fun x -> x + 1)
```|x};
  your_impl =
    Haz3lcore.Zipper.caret_to_start (Option.get (Haz3lcore.TextRoundtrip.of_text ~root:Exp {x|let update_entry = 
fun (t, label_predicate : (String -> Bool), fn : (? -> ?)) ->
¿
in
update_entry((apple=1, pear=2, avocado=3), 
string_match("^a",_), 
fun n -> n + 1)|x}));
  hidden_tests =
    {
      tests =
        Option.get (Haz3lcore.TextRoundtrip.of_text ~root:Exp {x|test update_entry((apple=1, pear=2, avocado=3), string_match("^a",_), int_plus(1,_)) == (apple=2, pear=2, avocado=4) end;
test update_entry((x=10, y=20, z=30), string_eq("y",_), fun i -> i * 2) == (x=10, y=40, z=30) end;
test update_entry((), string_eq("", _), fun i -> i + 1) == () end|x});
      hints = ["Example input"; "Updating specific entry"; "Empty tuple"];
    };
  wrapper = false;
  show_report = true;
}
