(* Auto-generated by: ./hazel gen-tutorial -- DO NOT EDIT *)
(* Source: hazel-programs/tutorial/conjoined/22-sample-colors.hz *)

let exercise : Tutorial.spec =
  {
    id =
      Option.get (Haz3lcore.Id.of_string "b0000022-0022-0022-0022-000000000022");
    title = "22 - Sample Colors";
    version = 1;
    module_name = "TuGen_22SampleColors";
    prompt =
      {x|# Sample colors

When you click a sample, the others take on colors showing how their run relates to it. You met two already: **pink** ran before, **blue** ran after. **Green** is the focus's own run, and gray is unrelated. There is a legend at the bottom of the probe sidebar; nothing here needs memorizing.

**Try this**
1. Probe `first`, `second`, `third`. Click `second`: `first` is pink (ran before), `third` is blue (ran after).
2. In the watering section, probe `adj` inside `daily_water` and probe the calls. Click a call: its `adj` is green (same run); a call that started before it is pink, one that finished after is blue.
3. Switch to *many* mode and click a sample inside the map. Samples from the same outer call are colored; samples from a different call are gray.|x};
    display_hint = {x||x};
    task_reference =
      {x|### Colors
- **green**: the focus's own run
- **pink**: started before the focus
- **blue**: finished after the focus
- **gray**: a different, unrelated call|x};
    your_impl =
      Haz3lcore.Zipper.caret_to_start
        (Option.get
           (Haz3lcore.TextRoundtrip.of_text ~root:Exp
              {x|let first = 1 + 2 in
let second = 3 * 4 in
let third = 5 + 6 in

type MoonPhase = New + Waxing + Full + Waning in
let daily_water(base: Int, phase: MoonPhase): Int =
let adj =
case phase
| New => 50
| Full => 0 - 30
| _ => 0
end
in
base + adj
in
daily_water(250, Full);
daily_water(50, New);

type Plant = (name = String, water = Int) in
let bed_labels(bed: [Plant]): [String] =
map(bed, fun p -> p.name ++ ": " ++ string_of_int(p.water) ++ "ml")
in
let fern: Plant = (name = "fern", water = 250) in
let orchid: Plant = (name = "orchid", water = 180) in
let cactus: Plant = (name = "cactus", water = 50) in
bed_labels([fern, orchid]);
bed_labels([cactus])|x}));
    hidden_tests =
      {
        tests =
          Option.get
            (Haz3lcore.TextRoundtrip.of_text ~root:Exp {x|test true end|x});
        hints = [];
      };
    wrapper = false;
    show_report = false;
  }
