(* Auto-generated by: ./hazel gen-tutorial -- DO NOT EDIT *)
(* Source: hazel-programs/tutorial/conjoined/25-tasks-ahead.hz *)

let exercise : Tutorial.spec =
  {
    id =
      Option.get (Haz3lcore.Id.of_string "b0000026-0026-0026-0026-000000000026");
    title = "25 - Tasks Ahead";
    version = 1;
    module_name = "TuGen_25TasksAhead";
    prompt =
      {x|{{no_editor}}
# The tasks ahead

*(Placeholder.)* You have reached the end of the guided tutorial. Next come a series of short **program-writing** and **debugging** tasks that put what you have learned to work.

We will fill this in with an overview: what the tasks look like, how they are structured, and a reminder to keep thinking out loud and to ask questions whenever you need.|x};
    display_hint = {x||x};
    task_reference = {x||x};
    your_impl =
      Haz3lcore.Zipper.caret_to_start
        (Option.get (Haz3lcore.TextRoundtrip.of_text ~root:Exp {x|0|x}));
    hidden_tests =
      {
        tests =
          Option.get
            (Haz3lcore.TextRoundtrip.of_text ~root:Exp {x|test true end|x});
        hints = [];
      };
    wrapper = false;
    show_report = false;
  }
