(* Auto-generated by: ./hazel gen-tutorial -- DO NOT EDIT *)
(* Source: hazel-programs/tutorial/conjoined/25-tasks-ahead.hz *)

let exercise : Tutorial.spec = {
  id = Option.get (Haz3lcore.Id.of_string "b0000026-0026-0026-0026-000000000026");
  title = "25 - Tasks Ahead";
  version = 1;
  module_name = "TuGen_25TasksAhead";
  prompt = {x|{{no_editor}}
# Tasks ahead

The following are some more substantial tasks, alternating between two types:

- **writing**: build a function to a spec (auto-probe is on for most of these)
- **debugging**: a working program with one failing test; find and fix the bug

Notes:

- **The tests are the spec.** Read them early.
- **Debugging tasks have a suggested approach** in the Task Reference sidebar. You probably do not need to read the whole program in detail; start with the suggested steps.
- **Use whatever probe tools feel natural.** Manual probes, auto-probe, many mode, pin, step into, the variable dropdown: whatever answers your current question.
- **Think out loud.** Say what you expect before you look, and what surprised you after.

On a few tasks probes will be switched off; you still have `print` and the tests. That contrast is part of what we are studying.

Take your time. Ask questions.|x};
  display_hint = {x||x};
  task_reference = {x||x};
  your_impl =
    Haz3lcore.Zipper.caret_to_start
      (Haz3lcore.PersistentZipper.unpersist ~root:Exp
  { Haz3lcore.PersistentZipper.zipper = {x|((selection((focus Left)(content())(mode Normal)(anchor_caret Outer)(smart_rounded false)))(relatives((siblings(((Tile((id 0e4bbfc5-2f4a-4f60-8cf6-d26a45f01395)(label(0))(mold((out Exp)(in_())(nibs(((shape Convex)(sort Exp))((shape Convex)(sort Exp))))))(shards(0))(children()))))()))(ancestors())))(caret Outer)(refractors((manuals())(multis((ids())(suppressed())(ephemerals())))(sample_focus((call_stack())(index -1)(pinned_stack())(indicated_call())(time())(seq 0)(step_range())(pending_focus())))(autoprobe_target())(pending_probe_cursor()))))|x};
    backup_text = {x|0|x} });
  hidden_tests =
    {
      tests =
        (Haz3lcore.PersistentZipper.unpersist ~root:Exp
  { Haz3lcore.PersistentZipper.zipper = {x|((selection((focus Left)(content())(mode Normal)(anchor_caret Outer)(smart_rounded false)))(relatives((siblings(((Tile((id 4f411e4b-0296-4cbb-ad29-c044eef528cc)(label(test end))(mold((out Exp)(in_(Exp))(nibs(((shape Convex)(sort Exp))((shape Convex)(sort Exp))))))(shards(0 1))(children(((Secondary((id 21a13976-bf54-4700-9ebf-2299b2d2b2ae)(content(Whitespace" "))))(Tile((id 2bfcc7f7-294b-42de-863d-b55ab9ed963e)(label(true))(mold((out Exp)(in_())(nibs(((shape Convex)(sort Exp))((shape Convex)(sort Exp))))))(shards(0))(children())))(Secondary((id cfd387c1-fef7-4b1e-b24e-0a5789d0398f)(content(Whitespace" "))))))))))()))(ancestors())))(caret Outer)(refractors((manuals())(multis((ids())(suppressed())(ephemerals())))(sample_focus((call_stack())(index -1)(pinned_stack())(indicated_call())(time())(seq 0)(step_range())(pending_focus())))(autoprobe_target())(pending_probe_cursor()))))|x};
    backup_text = {x|test true end|x} });
      hints = [];
    };
  wrapper = false;
  show_report = false;
}
