(* Auto-generated by: ./hazel gen-tutorial -- DO NOT EDIT *)
(* Source: hazel-programs/tutorial/conjoined/07-if-expressions.hz *)

let exercise : Tutorial.spec = {
  id = Option.get (Haz3lcore.Id.of_string "b0000006-0006-0006-0006-000000000006");
  title = "07 - If Expressions";
  version = 1;
  module_name = "TuGen_07IfExpressions";
  prompt = {x|An `if` chooses between two values based on a condition:
```hazelnostatics
if condition then a else b
```
The condition must be a `Bool`. You can nest them:
```hazelnostatics
if condition_1 then -1
else if condition_2 then 0
else 1
```

# Task

**See it as you write**
*Before you begin writing*, right-click the `clamp` definition and choose *Add multi probe* (or Cmd/Ctrl+E with the cursor on it). A probe lands on each line, so values appear as you type. Add line breaks to see more, join lines to see fewer.

Over-watering drowns a plant. Complete `clamp` so it holds a watering amount `x` to the range 0 to 100: below 0 gives `0`, above 100 gives `100`, otherwise `x` unchanged.|x};
  display_hint = {x|Start with `if x < 0 then 0 else ...` and nest another `if` for the upper bound.|x};
  task_reference = {x|### If
```hazel
if 3 < 0 then 0 else 3
```
Nested:
```hazel
if x < 0 then -1
else if x == 0 then 0
else 1
```

### Comparisons
`==  <  >  <=  >=`

### Probes
- **Add / remove a probe**: Cmd/Ctrl+E, or right-click then *Add probe*
- **Multi probe** (on a definition): a probe per line. Add or remove line breaks to control how much you see.|x};
  your_impl =
    Haz3lcore.Zipper.caret_to_start (Option.get (Haz3lcore.TextRoundtrip.of_text ~root:Exp {x|let clamp(x: Int): Int =
¿

in
clamp(150)|x}));
  hidden_tests =
    {
      tests =
        Option.get (Haz3lcore.TextRoundtrip.of_text ~root:Exp {x|test clamp(-5) == 0 end;
test clamp(50) == 50 end;
test clamp(150) == 100 end|x});
      hints = ["clamp(-5) should be 0"; "clamp(50) should be 50"; "clamp(150) should be 100"];
    };
  wrapper = false;
  show_report = true;
}
