(* Auto-generated by: ./hazel gen-tutorial -- DO NOT EDIT *)
(* Source: hazel-programs/tutorial/basics/02-the-tylr-parser-and-backpack.hz *)

let exercise : Tutorial.spec = {
  id = Option.get (Haz3lcore.Id.of_string "a0000002-0002-0002-0002-000000000002");
  title = "Basics / 02 - The Tylr Parser And Backpack";
  version = 3;
  module_name = "TuGen_Basics02TheTylrParserAndBackpack";
  prompt = {x|Hazel uses a tile-based parser called Tylr. When you type a multi-token form like `let`, Tylr automatically tracks the remaining delimiters that are needed to complete the syntactic form. These obligations are held in the *backpack*, shown in yellow above the cursor.

The editor below already contains `let x =` with a hole automatically placed after the `=`. Notice that the `in` delimiter is in the backpack — it still needs to be *dropped* into the program.

Complete the expression step by step:
1. Type `1` to fill in the value for `x`.
2. Add a space, then press `Tab` (or type `in`) to drop the `in` delimiter from the backpack, followed by another space.
3. Type `x + 1` as the body of the `let` expression.

The result should evaluate to **2**.|x};
  display_hint = {x|Type a let expression and use Tab to complete obligations|x};
  task_reference = {x|### Let Expression
```hazel
let a = 1 in
a
```

### Backpack
- **Tab** drops the next obligation from the backpack
- Typing the delimiter (e.g. `in`) also works|x};
  your_impl =
    Haz3lcore.Move.to_start (Option.get (Haz3lcore.TextRoundtrip.of_text ~root:Exp {x|let x = ¿|x}));
  hidden_tests =
    {
      tests =
        Option.get (Haz3lcore.TextRoundtrip.of_text ~root:Exp {x|test answer == 2 end;
¿|x});
      hints = ["Type `let x = 1 in x + 1` using Tab to drop backpack obligations."];
    };
  wrapper = true;
  show_report = false;
}
