(* Auto-generated by: ./hazel gen-tutorial -- DO NOT EDIT *)
(* Source: hazel-programs/tutorial/conjoined/02-parser-and-backpack.hz *)

let exercise : Tutorial.spec = {
  id = Option.get (Haz3lcore.Id.of_string "b0000002-0002-0002-0002-000000000002");
  title = "02 - Parser And Backpack";
  version = 1;
  module_name = "TuGen_02ParserAndBackpack";
  prompt = {x|Hazel's parser helps you complete incomplete syntax. When you start a multi-token form like `let … = … in`, the tokens you still owe wait in the *backpack*, shown in yellow above the caret.

`let` expressions bind names for use in the rest of the program:
```hazelnostatics
let x = expr in
body
```

# Task
1. After the `=`, fill the definition with `250 * 7`.
2. Type `in` and watch it leave the backpack (or press `Tab` to drop it without typing).
3. Finish the body so the program reads `let weekly = 250 * 7 in weekly`.
4. Probe `weekly` on the last line (**Cmd/Ctrl+E**); it should read **1750**.|x};
  display_hint = {x||x};
  task_reference = {x|### Let
```hazel
let a = 1 in
a
```

### Backpack
- `Tab` drops the next token
- typing it (e.g. `in`) also works|x};
  your_impl =
    Haz3lcore.Zipper.caret_to_start
      (Haz3lcore.PersistentZipper.unpersist ~root:Exp
  { Haz3lcore.PersistentZipper.zipper = {x|((selection((focus Left)(content())(mode Normal)(anchor_caret Outer)(smart_rounded false)))(relatives((siblings(((Tile((id 76c1a969-cdc4-49b5-9eab-f6b6e2834309)(label(let = in))(mold((out Exp)(in_(Pat Exp))(nibs(((shape Convex)(sort Exp))((shape(Concave 45))(sort Exp))))))(shards(0 1))(children(((Secondary((id fbf8f122-c4c3-4257-8da7-4cf0543baa3a)(content(Whitespace" "))))(Tile((id 480e4179-b023-4045-9d83-59542d0781ea)(label(weekly))(mold((out Pat)(in_())(nibs(((shape Convex)(sort Pat))((shape Convex)(sort Pat))))))(shards(0))(children())))(Secondary((id 42c5939b-59c9-44ef-bdfc-cbc30ade8cae)(content(Whitespace" ")))))))))(Secondary((id a464b930-8002-4525-a850-4b20d469385f)(content(Whitespace" ")))))((Grout((id e42d0fee-8f1c-41f9-b2e1-b435b263f61c)(shape Convex))))))(ancestors())))(caret Outer)(refractors((manuals())(multis((ids())(suppressed())(ephemerals())))(sample_focus((call_stack())(index -1)(pinned_stack())(indicated_call())(time())(seq 0)(step_range())(pending_focus())))(autoprobe_target())(pending_probe_cursor()))))|x};
    backup_text = {x|let weekly = |x} });
  hidden_tests =
    {
      tests =
        (Haz3lcore.PersistentZipper.unpersist ~root:Exp
  { Haz3lcore.PersistentZipper.zipper = {x|((selection((focus Left)(content())(mode Normal)(anchor_caret Outer)(smart_rounded false)))(relatives((siblings(((Tile((id 2df79701-4b30-452d-ae4e-757afeee2c2d)(label(test end))(mold((out Exp)(in_(Exp))(nibs(((shape Convex)(sort Exp))((shape Convex)(sort Exp))))))(shards(0 1))(children(((Secondary((id e5ea2b23-fb85-43c9-ad1c-bb0f973bc6be)(content(Whitespace" "))))(Tile((id ef8271b0-c1d3-45ac-94ec-480cd6f8da5b)(label(answer))(mold((out Exp)(in_())(nibs(((shape Convex)(sort Exp))((shape Convex)(sort Exp))))))(shards(0))(children())))(Secondary((id d2b6d5b1-17c5-41ec-96c1-2ad1f8750e7b)(content(Whitespace" "))))(Tile((id 767a7f90-fab6-46ff-a80f-6d8ca91e75da)(label(==))(mold((out Exp)(in_())(nibs(((shape(Concave 31))(sort Exp))((shape(Concave 31))(sort Exp))))))(shards(0))(children())))(Secondary((id 0ae2253f-c1d2-4ea4-aedb-6ea4325fef5f)(content(Whitespace" "))))(Tile((id de901c5b-d769-4f96-891a-7e6cb36238d3)(label(1750))(mold((out Exp)(in_())(nibs(((shape Convex)(sort Exp))((shape Convex)(sort Exp))))))(shards(0))(children())))(Secondary((id dd61a715-e375-4598-9419-203cc003ea28)(content(Whitespace" ")))))))))(Tile((id ffa21c80-310f-4323-9fe8-bbffe0104f2a)(label(";"))(mold((out Exp)(in_())(nibs(((shape(Concave 35))(sort Exp))((shape(Concave 35))(sort Exp))))))(shards(0))(children())))(Secondary((id a0275c5e-e392-49e4-b82a-dc08d7feedeb)(content(Whitespace"\n")))))((Grout((id 204ee263-13b9-4361-b721-1191901c5965)(shape Convex))))))(ancestors())))(caret Outer)(refractors((manuals())(multis((ids())(suppressed())(ephemerals())))(sample_focus((call_stack())(index -1)(pinned_stack())(indicated_call())(time())(seq 0)(step_range())(pending_focus())))(autoprobe_target())(pending_probe_cursor()))))|x};
    backup_text = {x|test answer == 1750 end;
|x} });
      hints = ["Build `let weekly = 250 * 7 in weekly`."];
    };
  wrapper = true;
  show_report = true;
}
