initialProgram: |
  # ROOM BOOKING MVU PRELUDE #

  type Weekday = M + T + W + R + F in
  type TimeOfDay = AM + PM in
  type Time = (Weekday, TimeOfDay) in
  type User = String in
  type BookingID = Int in
  type Booking = (Time, User, BookingID) in
  type BookingFormData = (Time, User) in
  type Model = (BookingFormData, [Booking], BookingID) in

  type Action =
    + AddBooking(User, Weekday, TimeOfDay)
    + CancelBooking(User, Int)
    + ClearBookings
  in

  let initFormState = ((M, AM), "") in
  let model_init: Model = (initFormState, [], 0) in

  let getBookings: Model -> [Booking] =
    fun _, bs,_ -> bs in

  let bookingExists: (Model, Booking) -> Bool =
    fun model, booking ->
      exists(getBookings(model), fun b -> b == booking)  
  in

  let getUserBookings: (Model, User) -> [Booking] =
    fun model, user ->
      filter(getBookings(model), fun (_, u:User,_) -> u == user) 
  in

  let getBookingById: (Model, BookingID) -> Booking =
    fun model, id ->
      case filter(getBookings(model), fun (_, _, i:BookingID) -> i == id)
      | [booking] => booking
      | _ => ?  
      end  
  in

  let rm_booking: (User, BookingID, [Booking]) -> [Booking] =
    fun user, id, bookings ->
      filter(
        bookings, fun (_, u:User, i:BookingID) -> (u!= user) \/ (i!= id)) in

  let update: (Model, Action) -> Model =
    ? 
  in
prompt: |
  Write the Booking update function
tests: |
  # ROOM BOOKING MVU TESTS #

  test
    getBookings(update(model_init, AddBooking("Charles",M, AM)))
    == [((M, AM),"Charles",0)]  
  end;

  test
    let model = update(model_init, AddBooking("Alice", T, PM)) in
    getBookings(model) == [((T, PM), "Alice", 0)] 
  end;

  test
    let model = update(model_init, AddBooking("Bob", W, AM)) in
    getUserBookings(model, "Bob") == [((W, AM), "Bob", 0)]  
  end;

  test
    let model = update(model_init, AddBooking("Alice", R, PM)) in
    let model = update(model, CancelBooking("Alice", 0)) in
    getUserBookings(model, "Alice") == []  
  end;

  test
    let model = update(model_init, AddBooking("Alice", F, AM)) in
    let model = update(model, AddBooking("Bob", F, AM)) in
    getBookingById(model, 1) == ((F, AM), "Bob", 1)   
  end;

  test
    let model = update(model_init, AddBooking("Alice", M, AM)) in
    let model = update(model, AddBooking("Bob", M, PM)) in
    let model = update(model, AddBooking("Alice", T, AM)) in
    let model = update(model, AddBooking("Bob", T, PM)) in
    let model = update(model, AddBooking("Alice", W, AM)) in
    let model = update(model, CancelBooking("Alice", 0)) in
    let model = update(model, CancelBooking("Bob", 3)) in
    getBookings(model) == [((W, AM), "Alice", 4), ((T, AM), "Alice", 2), ((M, PM), "Bob", 1)]  
  end;

  test
    let model = update(model_init, AddBooking("Alice", M, AM)) in
    let model = update(model, AddBooking("Bob", M, AM)) in
    let model = update(model, AddBooking("Charlie", M, AM)) in
    let model = update(model, AddBooking("Dave", M, PM)) in
    let model = update(model, AddBooking("Eve", M, PM)) in
    let model = update(model, CancelBooking("Bob", 1)) in
    let model = update(model, CancelBooking("Dave", 3)) in
    let model = update(model, CancelBooking("Alice", 0)) in
    getBookings(model) == [((M, PM), "Eve", 4), ((M, AM), "Charlie", 2)]  
  end;

  test
    let model = update(model_init, AddBooking("Alice", M, AM)) in
    let model = update(model, ClearBookings) in
    getBookings(model) == []  
  end;