initialProgram: |
  # USERNAME CHECKER MVU PRELUDE #

  type UsernameCriteria =
    + MinLength(Int)
    + StartsWithLetter
    + NoSpaces in

  type UsernameValidity =
    + Invalid
    + Valid

  type Username = String in
  type Criteria = [UsernameCriteria] in
  type Validity = UsernameValidity in

  type Model = (Username, Criteria, Validity) in

  let initialModel: Model = (
    "",
    [
      MinLength(5),
      StartsWithLetter,
      NoSpaces
    ],
    Invalid
  ) in

  type Action =
    + UpdateUsername(String)
    + ClearCriteria
    + AddCriterion(UsernameCriteria)
    + RemoveCriterion(UsernameCriteria) in

  let meetsMinLength: (String, Int) -> Bool =
    fun username, len ->
      string_length(username) >= len in

  let string_contains: (String, String) -> Bool = fun s1: String, s2: String ->
    let len = string_length(s1) in
    let check = fun idx: Int ->
      if idx >= len
      then false
      else
        let char = string_sub(s1, idx, 1) in
        if string_eq(char, s2)
        then true
        else check(idx + 1)
    in
    check(0)
  in

  let hasFromSet: (String, String) -> Bool =
    fun username: Username, set: String ->
      let loop: String -> Bool =
        fun s: String ->
          if string_length(s) == 0 
          then false 
          else
            let first = string_sub(s, 0, 1) in
            if string_contains(set, first) 
            then true 
            else loop(string_sub(s, 1, string_length(s) - 1)) 
      in loop(username)
  in

  let hasNoSpaces: String -> Bool =
    fun username: Username ->
      not (hasFromSet(username, " ")) in

  let startsWithLetter: Username -> Bool =
    fun username: Username ->
      if string_length(username) == 0
      then false
      else
        let first_char = string_sub(username, 0, 1) in
      string_contains("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz", first_char) in

  let meetsCriterion: (Username, UsernameCriteria) -> Bool =
    fun username, criterion ->
      case criterion
      | StartsWithLetter => startsWithLetter(username)
      | NoSpaces => hasNoSpaces(username)
      | MinLength(len) => meetsMinLength(username, len)
      end in

  let metCriteria: (Username, [UsernameCriteria]) -> [Bool] =
    fun username, criteria ->
      filter(
        criteria,
        fun c: UsernameCriteria -> meetsCriterion(username, c)
      ) in

  let Validity_of: Int -> UsernameValidity =
    fun num_criteria_met ->
      case num_criteria_met
      | 3 => Valid
      | _ => Invalid 
      end in

  let calculateValidity: (Username, [UsernameCriteria]) -> UsernameValidity =
    fun username, criteria ->
      Validity_of(length(metCriteria(username, criteria))) in


  let update: (Model, Action) -> Model =
    ?
  in
  
prompt: |
  Write the Usernames update function
tests: |
  test
    let model = update(initialModel, ClearCriteria) in
    let (_, criteria, _) = model in
    length(criteria) == 0
  end;

  test
    let model = update(initialModel, ClearCriteria) in
    let model = update(model, AddCriterion(MinLength(5))) in
    let model = update(model, UpdateUsername("abcd")) in
    let (_, _, validity) = model in
    validity == Invalid
  end;

  test
    let model = update(initialModel, ClearCriteria) in
    let model = update(model, AddCriterion(MinLength(5))) in
    let model = update(model, UpdateUsername("abcde")) in
    let (_, _, validity) = model in
    validity == Valid
  end;

  test
  let model = update(initialModel, ClearCriteria) in
  let model = update(model, AddCriterion(StartsWithLetter)) in
  let model = update(model, UpdateUsername("1user")) in
  let (_, _, validity) = model in
  validity == Invalid
  end;

  test
    let model = update(initialModel, ClearCriteria) in
    let model = update(model, AddCriterion(StartsWithLetter)) in
    let model = update(model, UpdateUsername("User")) in
    let (_, _, validity) = model in
    validity == Valid
  end;

  test
    let model = update(initialModel, ClearCriteria) in
    let model = update(model, AddCriterion(NoSpaces)) in
    let model = update(model, UpdateUsername("User name")) in
    let (_, _, validity) = model in
    validity == Invalid
  end;

  test
    let model = update(initialModel, ClearCriteria) in
    let model = update(model, AddCriterion(NoSpaces)) in
    let model = update(model, UpdateUsername("Username")) in
    let (_, _, validity) = model in
    validity == Valid
  end;

  test
  let model = update(initialModel, UpdateUsername("User1")) in
  let (_, _, validity) = model in
  validity == Valid
  end;

  test
  let model = update(initialModel, UpdateUsername("1 us")) in
  let (_, _, validity) = model in
  validity == Invalid
  end;