import Ast from "./ast"
import AstSexp from "./ast_sexp"
import MaybeIndet from "./maybe_indet"

import Sexp from "../../sexplib/sexp"

export let print_p = v => print(v)
export let print_i = e => {
  let sexp = AstSexp.sexpOfAst(e)
  let str = Sexp.toString(sexp)
  print(str)
}
export let print_m = m =>
  match (m) {
    MaybeIndet.Value(v) => print_p(v),
    MaybeIndet.Indet(e) => print_i(e),
  }
