open Alcotest;
open Test_Evaluator_Prelude;
open Language;

[@deriving show({with_path: false})]
type error =
  | NoError
  | StaticError(list(Mark.t))
  | DynamicError(list(Mark.t));

/* Equality on Mark.t for tests.
   We can't use structural `==` on marks because some constructors carry
   `Typ.t` payloads whose `annotation.ids` are freshly generated by statics
   but are zeros in the test-built expected values. We compare via the
   derived show, which renders ids opaque, normalizing them away.
   INCOMPLETE: only the cases exercised by these tests are handled; extend
   here when adding tests that produce other Mark constructors. */
let mark_equal = (a: Language.Mark.t, b: Language.Mark.t): bool =>
  switch (a, b) {
  | (
      ExpectationMismatch({ana: ana1, syn: syn1}),
      ExpectationMismatch({ana: ana2, syn: syn2}),
    ) =>
    Typ.show(ana1) == Typ.show(ana2) && Typ.show(syn1) == Typ.show(syn2)
  | (ExpectationMismatch(_), _)
  | (_, ExpectationMismatch(_)) => false
  | _ =>
    failwith(
      "Test_Evaluator_LiveTyping.mark_equal: unhandled Mark constructor; "
      ++ "extend mark_equal to cover this case.",
    )
  };

let testable_error =
  testable(Fmt.using(show_error, Fmt.string), (a: error, b: error) =>
    switch (a, b) {
    | (NoError, NoError) => true
    | (StaticError(e1), StaticError(e2)) => List.equal(mark_equal, e1, e2)
    | (DynamicError(e1), DynamicError(e2)) => List.equal(mark_equal, e1, e2)
    | _ => false
    }
  );
module FError =
  Grammar.Factory({
    type t = error;
    let default_value = (): error => {
      NoError;
    };
  });

/* The live-typing input CodeWithStatics builds from an evaluation: the
   dynamics, narrowed to the pinned call when there is one, converted for
   statics by the same Dynamics.to_live_typing_map the editor uses. */
let live_typing_of_state =
    (~pin: option(CallStack.t)=None, state: EvaluatorState.t)
    : LiveTyping.Map.t => {
  let dynamics: Dynamics.t = {
    ...Dynamics.empty,
    probe_map: EvaluatorState.get_probes(state),
    type_inst_map: EvaluatorState.get_type_insts(state),
  };
  (
    switch (pin) {
    | None => dynamics
    | Some(pinned_stack) =>
      Dynamics.filter_by_focus(
        {
          ...Sample.Focus.init,
          pinned_stack: Some(pinned_stack),
        },
        dynamics,
      )
    }
  )
  |> Dynamics.to_live_typing_map;
};

/* A term as the editor prints it, on one line. */
let show_any = (any: Any.t): string =>
  Haz3lcore.(
    Printer.of_segment(
      ~holes="?",
      ExpToSegment.any_to_segment(
        ~settings=
          ExpToSegment.Settings.of_core(~inline=true, CoreSettings.off),
        any,
      ),
    )
  );

/**
 * Maps static and live typing error information to error annotations.
 * Simplifies the nested switch logic with pattern matching.
 */
let map_error_annotation = (static_info, live_typing_info) => {
  let static_error =
    Option.map(Info.marks_of, static_info)
    |> Option.bind(_, ms =>
         switch (ms) {
         | [] => None
         | _ => Some(ms)
         }
       );
  let live_typing_error =
    Option.map(Info.marks_of, live_typing_info)
    |> Option.bind(_, ms =>
         switch (ms) {
         | [] => None
         | _ => Some(ms)
         }
       );

  switch (static_error, live_typing_error) {
  | (Some(e), _) => StaticError(e)
  | (None, Some(e)) => DynamicError(e)
  | (None, None) => NoError
  };
};

/**
 * Reusable test function for live typing validation.
 * Takes an expected expression with error annotations and verifies
 * that the live typing system correctly identifies errors.
 */
let test_live_typing = (~test_name=?, expected_exp: FError.exp) => {
  // Create expression with fresh IDs for static analysis
  let exp_with_ids: Exp.t =
    Grammar.map_exp_annotation(_ => IdTagged.IdTag.fresh(), expected_exp);

  let test_name =
    Util.OptUtil.get(() => show_any(Exp(exp_with_ids)), test_name);

  // Perform initial static analysis (also produces elaborated expression).
  let (initial_statics, elaborated_exp) =
    Statics.mk(CoreSettings.on, Builtins.ctx_init(Some(Int)), exp_with_ids);

  let original_errors =
    StaticsBase.Map.errors(initial_statics) |> List.map(snd);
  Alcotest.check(
    Alcotest.int,
    "Expect no static errors initially",
    0,
    List.length(original_errors),
  );

  // Compute targets for expressions with unknown types (needed for live typing)
  let targets =
    Haz3lcore.CachedStatics.compute_targets(
      ~settings=CoreSettings.on,
      ~info_map=initial_statics,
      ~probe_ids=Id.Map.empty,
    );

  // Evaluate the elaborated expression to collect dynamic information
  let (_, evaluation_state) =
    Evaluator.evaluate(
      ~eval_info=EvalInfo.of_targets(targets),
      ~env=Builtins.env_init,
      elaborated_exp,
    );

  let dynamic_expressions = live_typing_of_state(evaluation_state);

  // Re-run static analysis with dynamic information
  let (live_typing_statics, _) =
    Statics.mk(
      ~dynamics=dynamic_expressions,
      CoreSettings.on,
      Builtins.ctx_init(Some(Int)),
      exp_with_ids,
    );

  // Map the expression to annotate errors based on static and live typing
  let actual_exp: FError.exp =
    Grammar.map_exp_annotation(
      id_tag => {
        let static_info =
          StaticsBase.Map.lookup(
            IdTagged.IdTag.rep_id(id_tag),
            initial_statics,
          );
        let live_typing_info =
          StaticsBase.Map.lookup(
            IdTagged.IdTag.rep_id(id_tag),
            live_typing_statics,
          );

        map_error_annotation(static_info, live_typing_info);
      },
      exp_with_ids,
    );

  let testable_annotated: testable(Grammar.exp_t(error)) =
    testable(
      Fmt.using([%derive.show: Grammar.exp_t(error)], Fmt.string),
      Grammar.equal_exp_t((a: error, b: error) =>
        switch (a, b) {
        | (NoError, NoError) => true
        | (StaticError(e1), StaticError(e2)) =>
          List.equal(mark_equal, e1, e2)
        | (DynamicError(e1), DynamicError(e2)) =>
          List.equal(mark_equal, e1, e2)
        | _ => false
        }
      ),
    );
  // Verify that the actual error annotations match expectations
  check(testable_annotated, test_name, expected_exp, actual_exp);
};
/* Adapter: previous tests wrote `inconsistent_exp(Expectation({ana, syn}))`.
   In the new architecture, type-mismatch errors are represented as the single
   Mark `ExpectationMismatch({ana, syn})`. */
type inconsistent_kind =
  | Expectation({
      ana: Typ.t,
      syn: Typ.t,
    });
let inconsistent_exp = (kind: inconsistent_kind): list(Mark.t) =>
  switch (kind) {
  | Expectation({ana, syn}) => [
      Mark.ExpectationMismatch({
        ana,
        syn,
      }),
    ]
  };

type live_run = {
  static_map: Statics.Map.t,
  live_map: Statics.Map.t,
  /* The ids the editor decorates, as the shared reporting filter
     (StaticsBase.Map.live_typing_error_ids) computes them. */
  live_ids: list(Id.t),
};

/* The pin ProbeProj.pin_call builds for a probed call: the call's own id
   over the stack it ran under. The program must probe exactly one call, and
   that call must have run exactly once, or the pin is ambiguous. */
let pin_of_probed_call =
    (probes: Sample.Map.t, probe_targets: Sample.targets): CallStack.t =>
  switch (Id.Map.bindings(probe_targets)) {
  | [(ap_id, _)] =>
    switch (Id.Map.find_opt(ap_id, probes)) {
    | Some([sample]) => CallStack.extend(ap_id, sample.call_stack)
    | Some(samples) =>
      fail(
        Printf.sprintf(
          "the probed call ran %d times; pinning needs exactly one",
          List.length(samples),
        ),
      )
    | None => fail("the probed call never ran")
    }
  | probed =>
    fail(
      Printf.sprintf(
        "expected exactly one ^^probe, found %d",
        List.length(probed),
      ),
    )
  };

/* Static and live passes over `program`, the live one fed the dynamics of a
   full evaluation. With `~pinned`, the dynamics are first narrowed to the
   program's single `^^probe`d call, as CodeWithStatics narrows them to the
   editor's sample focus. */
let live_run = (~pinned: bool, program: string): live_run => {
  let (exp, elaborated, static_map, probe_targets) =
    parse_with_probes(program);
  let ctx = Builtins.ctx_init(Some(Int));
  let targets =
    Haz3lcore.CachedStatics.compute_targets(
      ~settings=CoreSettings.on,
      ~info_map=static_map,
      ~probe_ids=Id.Map.map(_ => (), probe_targets),
    );
  let (_, state) =
    Evaluator.evaluate(
      ~eval_info=EvalInfo.of_targets(targets),
      ~env=Builtins.env_init,
      elaborated,
    );
  let pin =
    pinned
      ? Some(
          pin_of_probed_call(
            EvaluatorState.get_probes(state),
            probe_targets,
          ),
        )
      : None;
  let (live_map, _) =
    Statics.mk(
      ~dynamics=live_typing_of_state(~pin, state),
      CoreSettings.on,
      ctx,
      exp,
    );
  {
    static_map,
    live_map,
    live_ids:
      StaticsBase.Map.live_typing_error_ids(
        ~static_error_ids=StaticsBase.Map.error_ids(static_map),
        live_map,
      ),
  };
};

/* Each live typing error as "<mark> <term>", sorted, so a run's errors
   compare as one value. */
let describe_live_errors = ({live_map, live_ids, _}: live_run): list(string) =>
  live_ids
  |> List.concat_map(id => {
       let info =
         switch (StaticsBase.Map.lookup(id, live_map)) {
         | Some(info) => info
         | None => fail("live typing error id without info: " ++ Id.show(id))
         };
       let term =
         switch (Info.any_of(info)) {
         | Some(any) => show_any(any)
         | None => fail("live typing error on a secondary node")
         };
       Info.marks_of(info)
       |> List.filter(Mark.is_live_reportable)
       |> List.map(mark => Mark.Variants.to_name(mark) ++ " " ++ term);
     })
  |> List.sort(String.compare);

/* `call`, marked for sampling the way a user pins it: with a probe on the
   application. */
let probed = (call: string): string => "^^probe(" ++ call ++ ")";

/* The info of the pattern variable `name` in `map`. Assumes `name` is bound
   only once in the program. */
let pat_info = (name: string, map: Statics.Map.t): option(Info.pat) =>
  Id.Map.fold(
    (_, info, acc) =>
      switch (info) {
      | Info.InfoPat({user_term, _} as p)
          when Pat.get_var(user_term) == Some(name) =>
        Some(p)
      | _ => acc
      },
    map,
    None,
  );

/* The synthesized type of binder `name`: the type that drives both the
   inspector display and the context entry seen by uses. */
let pat_elab_syn_ty = (name: string, map: Statics.Map.t): option(Typ.t) =>
  pat_info(name, map) |> Option.map((p: Info.pat) => p.elab_syn_ty);

/* The type of binder `name` with its head resolved through the binder's own
   context, so a `typfun` parameter reads as the type live typing
   instantiated it to. */
let pat_ty_normalized = (name: string, map: Statics.Map.t): option(Typ.t) =>
  pat_info(name, map)
  |> Option.map((p: Info.pat) => Typ.weak_head_normalize(p.ctx, p.ty));

/* Property: for every expression-info id, the elab_syn_ty produced by static
   analysis run *with* live-typing dynamics is more precise than (or equal to)
   the elab_syn_ty produced by the static-only analysis. Refinement only ever
   moves down the precision lattice. */
let precision_property = (exp: Exp.t): bool =>
  try({
    let exp_with_ids =
      Grammar.map_exp_annotation(_ => IdTagged.IdTag.fresh(), exp);
    let ctx = Builtins.ctx_init(Some(Int));
    let (static_map, elaborated) =
      Statics.mk(CoreSettings.on, ctx, exp_with_ids);
    if (StaticsBase.Map.has_errors(static_map)) {
      true;
    } else {
      let targets =
        Haz3lcore.CachedStatics.compute_targets(
          ~settings=CoreSettings.on,
          ~info_map=static_map,
          ~probe_ids=Id.Map.empty,
        );
      let (_, state) =
        Evaluator.evaluate(
          ~eval_info=EvalInfo.of_targets(targets),
          ~env=Builtins.env_init,
          elaborated,
        );
      let dynamics = live_typing_of_state(state);
      let (live_map, _) =
        Statics.mk(~dynamics, CoreSettings.on, ctx, exp_with_ids);
      Id.Map.for_all(
        (id, info_static) =>
          switch (info_static, StaticsBase.Map.lookup(id, live_map)) {
          | (Info.InfoExp(s), Some(Info.InfoExp(l))) =>
            Typ.is_more_precise(ctx, l.elab_syn_ty, s.elab_syn_ty)
          | _ => true
          },
        static_map,
      );
    };
  }) {
  | _ => true
  };

let precision_property_test =
  QCheck_alcotest.to_alcotest(
    QCheck.Test.make(
      ~name="Live type refines synthesized static type",
      ~count=500,
      QCheck_Util.arb_exp(~minimal_idents=true, 10),
      precision_property,
    ),
  );

let tests = (
  "Evaluator.LiveTyping",
  [
    precision_property_test,
    test_case(
      "dynamic in-editor feedback",
      `Slow,
      () => {
        let program = {hazel|
let unique = (fun xs ->
  fold_left(xs, fun (seen, x) ->if mem(seen,x) then seen else seen @[x], []))in
let pivot_table = (fun (table, new_col, index, value) ->
  let indices = map(table, index) |> unique in
  let new_cols = map(table, new_col) |> unique in

  map(indices, fun idx ->
    (index=idx) ...
    (map(new_cols, fun col ->
      (label=col,
        value=filter(table, fun r -> index(r) == idx && new_col(r) == col)
        |>value)
    ) |> from_lvs)
  ))in



let results =
  pivot_table(
    [(a=1,b=2,c=3), (a=1,b=2,c=3), (a=1,b=2,c=3), (a=1,b=2,c=3) ,(a=1,b=2,c=3)]
    @ [(a=1,b=2,c=3), (a=1,b=2,c=3), (a=1,b=2,c=3), (a=1,b=2,c=3) ,(a=1,b=2,c=3)],
    fun r -> r.a |> string_of_int,
    fun r -> r.b,
    fun r -> fold_left(r.c, int_plus, 0))
in

(results).`2`
|hazel};
        let exp = parse_exp(program);
        let (_, elaborated) =
          Statics.mk(CoreSettings.on, Builtins.ctx_init(Some(Int)), exp);
        let (result, state: EvaluatorState.t) =
          Evaluator.evaluate(~env=Builtins.env_init, elaborated);

        let dynamic_expressions = live_typing_of_state(state);
        let _static_feedback =
          Statics.mk(
            ~dynamics=dynamic_expressions,
            CoreSettings.on,
            Builtins.ctx_init(Some(Int)),
            exp,
          );

        let expected_exp =
          parse_exp({hz|
          [(index=2, `1`=30).`2`]
          |hz});
        check(testable_exp(), "Result of execution", expected_exp, result);
      },
    ),
    test_case(
      "Type flows through unknown ascription dynamically",
      `Quick,
      () => {
        // Create expected expression with dynamic error annotation
        // This tests that int(1) : ? : String correctly identifies
        // the type inconsistency when ? is resolved to int but expected as string
        let expected_exp: FError.exp =
          FError.(
            Exp.(
              asc(
                asc(
                  ~ann=
                    DynamicError(
                      inconsistent_exp(
                        Test_Statics_Prelude.FTemp.Typ.(
                          Expectation({
                            ana: string(),
                            syn: int(),
                          })
                        ),
                      ),
                    ),
                  int(1),
                  Typ.unknown(Internal),
                ),
                Typ.string(),
              )
            )
          );

        test_live_typing(expected_exp);
      },
    ),
    /* DISABLED: live-typing duplicates the inner branch's ExpectationMismatch
          onto the surrounding `If` expression. Tracked in
          https://github.com/hazelgrove/hazel/issues/2265. Re-enable once the
          extra mark on the If is removed.
       test_case(
         "Conditional uses runtime type information",
         `Quick,
         () => {
           open FError;
           open Exp;

           test_live_typing(
             bin_op(
               String(Concat),
               if_(
                 bool(true),
                 asc(
                   ~ann=
                     DynamicError(
                       inconsistent_exp(
                         Test_Statics_Prelude.FTemp.Typ.(
                           Expectation({
                             ana: string(),
                             syn: int(),
                           })
                         ),
                       ),
                     ),
                   int(1),
                   Typ.unknown(Internal),
                 ),
                 asc(string("World"), Typ.unknown(Internal)),
               ),
               string("World"),
             ),
           );
           test_live_typing(
             bin_op(
               String(Concat),
               if_(
                 bool(false),
                 asc(int(1), Typ.unknown(Internal)),
                 asc(string("Hello"), Typ.unknown(Internal)),
               ),
               string("World"),
             ),
           );
         },
       ),
       */
    test_case(
      "Unannotated lambda applied to string causes dynamic error",
      `Quick,
      () => {
        open FError;
        open Exp;
        let exp: FError.exp =
          ap(
            Forward,
            fn(
              Pat.var("y"),
              bin_op(
                Int(Plus),
                var(
                  ~ann=
                    DynamicError(
                      inconsistent_exp(
                        Test_Statics_Prelude.FTemp.Typ.(
                          Expectation({
                            ana: int(),
                            syn: string(),
                          })
                        ),
                      ),
                    ),
                  "y",
                ),
                int(1),
              ),
            ),
            string(""),
          );
        test_live_typing(exp);
      },
    ),
    test_case(
      "Pattern variable gets live type from application",
      `Quick,
      () => {
        let exp = parse_exp({|(fun x -> x)(1)|});
        let ctx = Builtins.ctx_init(Some(Int));
        let (static_map, elaborated) = Statics.mk(CoreSettings.on, ctx, exp);
        let targets =
          Haz3lcore.CachedStatics.compute_targets(
            ~settings=CoreSettings.on,
            ~info_map=static_map,
            ~probe_ids=Id.Map.empty,
          );
        let (_, state) =
          Evaluator.evaluate(
            ~eval_info=EvalInfo.of_targets(targets),
            ~env=Builtins.env_init,
            elaborated,
          );
        let dynamics = live_typing_of_state(state);
        let (live_map, _) = Statics.mk(~dynamics, CoreSettings.on, ctx, exp);
        check(
          Alcotest.option(Test_Statics_Prelude.testable_typ),
          "x has static type ?",
          Some(Test_Statics_Prelude.FTemp.Typ.unknown(Internal)),
          pat_ty_normalized("x", static_map),
        );
        check(
          Alcotest.option(Test_Statics_Prelude.testable_typ),
          "x has live type Int",
          Some(Test_Statics_Prelude.FTemp.Typ.int()),
          pat_ty_normalized("x", live_map),
        );
      },
    ),
    test_case(
      "Let-bound pattern variable gets live type",
      `Quick,
      () => {
        let exp = parse_exp({|let x = map([1,2,3], fun _ -> "") in x|});
        let ctx = Builtins.ctx_init(Some(Int));
        let (static_map, elaborated) = Statics.mk(CoreSettings.on, ctx, exp);
        let targets =
          Haz3lcore.CachedStatics.compute_targets(
            ~settings=CoreSettings.on,
            ~info_map=static_map,
            ~probe_ids=Id.Map.empty,
          );
        let (_, state) =
          Evaluator.evaluate(
            ~eval_info=EvalInfo.of_targets(targets),
            ~env=Builtins.env_init,
            elaborated,
          );
        let dynamics = live_typing_of_state(state);
        let (live_map, _) = Statics.mk(~dynamics, CoreSettings.on, ctx, exp);
        /* The let-bound pattern `x`: statically `[?]`, at runtime `[String]`. */
        check(
          Alcotest.option(Test_Statics_Prelude.testable_typ),
          "x binder synthesizes ? statically",
          Some(Test_Statics_Prelude.FTemp.Typ.unknown(Internal)),
          pat_elab_syn_ty("x", static_map),
        );
        check(
          Alcotest.option(Test_Statics_Prelude.testable_typ),
          "x binder is live [String]",
          Some(Test_Statics_Prelude.FTemp.Typ.(list(string()))),
          pat_elab_syn_ty("x", live_map),
        );
      },
    ),
    test_case(
      "Captured variable shadowed at the binder is not a live error",
      `Quick,
      () => {
        /* `f` closes over the outer `h : Int`. Its value is sampled at
           binders inside `fun h -> ...`, where the name `h` means the
           parameter instead — so a sample read against the ambient scope
           types as `() -> (() -> Int)` and the `z` binder gets a spurious
           ExpectationMismatch. The closure must be read against the
           environment it captured. */
        let program = {|let h = 3 in let f = fun () -> h in let g = fun h -> let z = h in 3 + h() in g(f)|};
        let {live_ids, live_map, _} = live_run(~pinned=false, program);
        check(
          Alcotest.int,
          "no live typing errors",
          0,
          List.length(live_ids),
        );
        check(
          Alcotest.option(Test_Statics_Prelude.testable_typ),
          "z binder is live () -> Int, not () -> ?",
          Some(Test_Statics_Prelude.FTemp.Typ.(arrow(prod([]), int()))),
          pat_elab_syn_ty("z", live_map),
        );
      },
    ),
    test_case(
      "Captured variable shadowed after capture is not a live error",
      `Quick,
      () => {
        /* Same hazard without the probed binder itself doing the shadowing:
           `f` captures `k : Int`, a later `k : String` shadows it, and the
           parameter `p` is sampled with `f`'s closure. Reading that closure
           against the ambient scope gives `p : () -> String`, making
           `3 + p()` a live error. */
        let program = {|let k = 3 in let f = fun () -> k in let k = "hi" in let g = fun p -> 3 + p() in g(f)|};
        let {live_ids, live_map, _} = live_run(~pinned=false, program);
        check(
          Alcotest.int,
          "no live typing errors",
          0,
          List.length(live_ids),
        );
        check(
          Alcotest.option(Test_Statics_Prelude.testable_typ),
          "p binder is live () -> Int",
          Some(Test_Statics_Prelude.FTemp.Typ.(arrow(prod([]), int()))),
          pat_elab_syn_ty("p", live_map),
        );
      },
    ),
    test_case(
      "Unannotated lambda called with inconsistent types gives no feedback",
      `Quick,
      () => {
        let program = {|let f = fun x -> x @ [""] in f(1);f(2.0)|};
        let exp = parse_exp(program);
        let no_errors = Grammar.map_exp_annotation(_ => NoError, exp);

        test_live_typing(no_errors);
      },
    ),
    test_case(
      "typfun uses dynamic type env with correct type",
      `Quick,
      () => {
        let program = {|(typfun a -> fun x : a -> (x : a))@<String>("")|};
        let exp = parse_exp(program);
        let no_errors = Grammar.map_exp_annotation(_ => NoError, exp);

        test_live_typing(
          ~test_name={|(typfun a -> fun x : a -> (x : a))@<String>("")|},
          no_errors,
        );
      },
    ),
    test_case(
      "typfun uses dynamic type env with incorrect type",
      `Quick,
      () => {
        open FError;
        open Exp;

        let exp: FError.exp =
          ap(
            Forward,
            typ_ap(
              typ_fun(
                TPat.var("a"),
                fn(
                  Pat.var("x"),
                  asc(
                    asc(
                      ~ann=
                        DynamicError(
                          inconsistent_exp(
                            Test_Statics_Prelude.FTemp.Typ.(
                              Expectation({
                                ana: var("a"),
                                syn: string(),
                              })
                            ),
                          ),
                        ),
                      var("x"),
                      Typ.unknown(Hole(EmptyHole)),
                    ),
                    Typ.var("a"),
                  ),
                ),
                None,
              ),
              Typ.int(),
            ),
            string(""),
          );
        test_live_typing(
          ~test_name={|(typfun a -> fun x -> (x : ? : a))@<Int>("")|},
          exp,
        );
      },
    ),
    test_case(
      "typfun with matching type instantiation: no error",
      `Quick,
      () => {
        open FError;
        open Exp;
        /* Same shape as the previous test, but instantiated to <String>
           with a String argument: a := String, x := "", so the inner
           Asc body has type String which matches `a`. Live-typing must
           consult the type-instantiation map to resolve `a` to `String`;
           if it leaves `a` Abstract, meet(Var("a"), String) fails and a
           spurious DynamicError is reported. */
        let exp: FError.exp =
          ap(
            Forward,
            typ_ap(
              typ_fun(
                TPat.var("a"),
                fn(
                  Pat.var("x"),
                  asc(
                    asc(var("x"), Typ.unknown(Hole(EmptyHole))),
                    Typ.var("a"),
                  ),
                ),
                None,
              ),
              Typ.string(),
            ),
            string(""),
          );
        test_live_typing(
          ~test_name={|(typfun a -> fun x -> (x : ? : a))@<String>("")|},
          exp,
        );
      },
    ),
    test_case(
      "Polymorphism with dynamic type environment in unevaluated code",
      `Quick,
      () => {
        let program = {|(typfun a -> fun (g) -> (fun () -> g : a))@<String>("")|};
        let exp = parse_exp(program);
        let no_errors = Grammar.map_exp_annotation(_ => NoError, exp);
        test_live_typing(~test_name=program, no_errors);
      },
    ),
    /* Annotated `poly` schemes whose type variable is instantiated at
       runtime. The refined body type (e.g. map's `[?]` result concretized
       from samples) must be re-generalized against the annotation before
       being rewrapped in Poly, or the scheme spuriously fails the
       expectation check at (and above) the typfun node. */
    test_case(
      "Annotated poly instantiated to a labeled tuple: no error",
      `Quick,
      () => {
        let program = {|let f : poly r -> ([r], r -> r) -> [r] = typfun r -> fun (xs : [r], g : r -> r) -> map(xs, g) in f@<(m= Int)>([(m= 1)], fun x -> x)|};
        let exp = parse_exp(program);
        let no_errors = Grammar.map_exp_annotation(_ => NoError, exp);
        test_live_typing(~test_name=program, no_errors);
      },
    ),
    test_case(
      "Annotated poly instantiated to a base type through map: no error",
      `Quick,
      () => {
        let program = {|let f : poly r -> ([r], r -> r) -> [r] = typfun r -> fun (xs : [r], g : r -> r) -> map(xs, g) in f@<Int>([1], fun x -> x)|};
        let exp = parse_exp(program);
        let no_errors = Grammar.map_exp_annotation(_ => NoError, exp);
        test_live_typing(~test_name=program, no_errors);
      },
    ),
    test_case(
      "Nested annotated polys, innermost instantiated to a labeled tuple: no error",
      `Quick,
      () => {
        let program = {|let f : poly a -> poly b -> poly c -> ([a], a -> b, b -> c) -> [c] = typfun a -> typfun b -> typfun c -> fun (xs : [a], p : a -> b, q : b -> c) -> map(xs, fun x -> q(p(x))) in f@<Int>@<Int>@<(m= Int)>([1], fun x -> x, fun y -> (m= y))|};
        let exp = parse_exp(program);
        let no_errors = Grammar.map_exp_annotation(_ => NoError, exp);
        test_live_typing(~test_name=program, no_errors);
      },
    ),
    test_case(
      "Poly annotation crossing an intermediate fun: no error",
      `Quick,
      () => {
        let program = {|let f : poly a -> Int -> poly c -> ([c], c -> c) -> [c] = typfun a -> fun x -> typfun c -> fun (ys : [c], g : c -> c) -> map(ys, g) in f@<Int>(1)@<(m= Int)>([(m= 1)], fun y -> y)|};
        let exp = parse_exp(program);
        let no_errors = Grammar.map_exp_annotation(_ => NoError, exp);
        test_live_typing(~test_name=program, no_errors);
      },
    ),
    test_case(
      "Conflicting instantiations of an annotated poly: no error",
      `Quick,
      () => {
        let program = {|let f : poly r -> ([r], r -> r) -> [r] = typfun r -> fun (xs : [r], g : r -> r) -> map(xs, g) in (f@<Int>([1], fun x -> x), f@<(m= Int)>([(m= 1)], fun x -> x))|};
        let exp = parse_exp(program);
        let no_errors = Grammar.map_exp_annotation(_ => NoError, exp);
        test_live_typing(~test_name=program, no_errors);
      },
    ),
    test_case(
      "Genuine mismatch under an annotated poly is still reported",
      `Quick,
      () => {
        open FError;
        open Exp;
        /* Same shape as "typfun uses dynamic type env with incorrect type",
           but with an explicit `poly` ascription on the typfun. The
           re-generalization applied to annotated typfuns must not mask the
           genuine error inside the body. */
        let exp: FError.exp =
          ap(
            Forward,
            typ_ap(
              asc(
                typ_fun(
                  TPat.var("a"),
                  fn(
                    Pat.var("x"),
                    asc(
                      asc(
                        ~ann=
                          DynamicError(
                            inconsistent_exp(
                              Test_Statics_Prelude.FTemp.Typ.(
                                Expectation({
                                  ana: var("a"),
                                  syn: string(),
                                })
                              ),
                            ),
                          ),
                        var("x"),
                        Typ.unknown(Hole(EmptyHole)),
                      ),
                      Typ.var("a"),
                    ),
                  ),
                  None,
                ),
                Typ.poly(
                  TPat.var("a"),
                  Typ.arrow(Typ.unknown(Hole(EmptyHole)), Typ.var("a")),
                ),
              ),
              Typ.int(),
            ),
            string(""),
          );
        test_live_typing(
          ~test_name=
            {|((typfun a -> fun x -> (x : ? : a)) : poly a -> ? -> a)@<Int>("")|},
          exp,
        );
      },
    ),
    /* Reporting policy: only observed ana/syn conflicts (ExpectationMismatch)
       are surfaced as live typing errors. Join-failure marks over sibling
       branches that were refined from disjoint runtime samples stay out of
       the report. */
    test_case(
      "Heterogeneous unknown field through a case join is not a live error",
      `Quick,
      () => {
        let program = {|let f = fun (xs : [(k= String, v= ?)]) -> map(xs, fun (k= k, v= v) -> case k == "name" | true => v | false => v end) in f([(k= "name", v= "a"), (k= "age", v= 1)])|};
        let {live_ids, static_map, live_map} =
          live_run(~pinned=false, program);
        check(
          Alcotest.int,
          "no static errors",
          0,
          List.length(StaticsBase.Map.error_ids(static_map)),
        );
        check(
          Alcotest.int,
          "no live typing errors reported",
          0,
          List.length(live_ids),
        );
        /* Guard against a vacuous pass: the live run must still have hit
           the branch-join conflict; only the reporting filter keeps it
           out of the error list. */
        let has_nomeet =
          Id.Map.exists(
            (_id, info) =>
              List.exists(
                fun
                | Mark.NoMeet(_) => true
                | _ => false,
                Info.marks_of(info),
              ),
            live_map,
          );
        check(
          Alcotest.bool,
          "live map still carries the NoMeet join mark",
          true,
          has_nomeet,
        );
      },
    ),
    test_case(
      "Observed ana/syn conflict survives the reporting filter",
      `Quick,
      () => {
        let program = {|(fun y -> y + 1)("")|};
        let {live_ids, live_map, _} = live_run(~pinned=false, program);
        check(
          Alcotest.int,
          "one live typing error survives the filter",
          1,
          List.length(live_ids),
        );
        let all_em =
          List.for_all(
            id =>
              switch (StaticsBase.Map.lookup(id, live_map)) {
              | Some(info) =>
                List.exists(
                  fun
                  | Mark.ExpectationMismatch(_) => true
                  | _ => false,
                  Info.marks_of(info),
                )
              | None => false
              },
            live_ids,
          );
        check(
          Alcotest.bool,
          "surviving id carries ExpectationMismatch",
          true,
          all_em,
        );
      },
    ),
    test_case(
      "Bad projection on a refined element type is a live error",
      `Quick,
      () => {
        /* `r : ?` refines from samples to (value= Bool, count= Int); the
           projection `.get_acne` is then a witnessed misuse (LabelNotFound)
           and must survive the live-error mark filter. */
        let program = {|let xs : [(value= Bool, count= Int)] = [(value= true, count= 1)] in map(xs, fun r -> r.get_acne)|};
        let {live_ids, static_map, live_map} =
          live_run(~pinned=false, program);
        check(
          Alcotest.int,
          "no static errors",
          0,
          List.length(StaticsBase.Map.error_ids(static_map)),
        );
        check(
          Alcotest.int,
          "one live typing error reported",
          1,
          List.length(live_ids),
        );
        let has_label_not_found =
          List.for_all(
            id =>
              switch (StaticsBase.Map.lookup(id, live_map)) {
              | Some(info) =>
                List.exists(
                  fun
                  | Mark.LabelNotFound(_) => true
                  | _ => false,
                  Info.marks_of(info),
                )
              | None => false
              },
            live_ids,
          );
        check(
          Alcotest.bool,
          "surviving id carries LabelNotFound",
          true,
          has_label_not_found,
        );
      },
    ),
    /* Pinning a call narrows the dynamics to that call's extent, as the
       editor's sample focus does. `get` is a stringly-keyed registry: "size"
       is a number, anything else a handler. `show` reads the size as a
       point, which is a misuse in both calls, then invokes the entry it
       looked up and compares it to itself. Each of those two is right for
       one entry and a misuse for the other, so which node errs, and with
       what kind, follows the pin. */
    test_case(
      "Pinned call selects the samples: which live errors fire follows the pin",
      `Quick,
      () => {
        let registry_program = (size_call, bump_call) =>
          {|let get = fun key -> case key | "size" => (12 : ?) | _ => ((fun n -> n + 1) : ?) end in
let show = fun key ->
  let x = get("size").x in
  let v = get(key) in
  (x, v(1), v == v) in
let _ = |}
          ++ size_call
          ++ {| in
|}
          ++ bump_call;
        let size = {|show("size")|}
        and bump = {|show("bump")|};
        let unpinned = live_run(~pinned=false, registry_program(size, bump));
        let pinned_size =
          live_run(~pinned=true, registry_program(probed(size), bump));
        let pinned_bump =
          live_run(~pinned=true, registry_program(size, probed(bump)));
        check(
          int,
          "no static errors",
          0,
          List.length(StaticsBase.Map.error_ids(unpinned.static_map)),
        );
        let errors = Alcotest.(list(string));
        check(
          errors,
          "unpinned: v's samples never meet, only the constant misuse",
          [{|DotOperatorRequiresTuple (get("size")).x|}],
          describe_live_errors(unpinned),
        );
        check(
          errors,
          {|pinned on show("size"): v is an Int, so v(1) applies a non-function|},
          [
            {|DotOperatorRequiresTuple (get("size")).x|},
            {|ExpectationMismatch v|},
          ],
          describe_live_errors(pinned_size),
        );
        check(
          errors,
          {|pinned on show("bump"): v is a function, so v == v compares functions|},
          [
            {|CompareFun v == v|},
            {|DotOperatorRequiresTuple (get("size")).x|},
          ],
          describe_live_errors(pinned_bump),
        );
        let typ = Alcotest.option(Test_Statics_Prelude.testable_typ);
        Test_Statics_Prelude.FTemp.Typ.(
          {
            check(
              typ,
              "v stays ? unpinned",
              Some(unknown(Internal)),
              pat_elab_syn_ty("v", unpinned.live_map),
            );
            check(
              typ,
              {|v is live Int under show("size")|},
              Some(int()),
              pat_elab_syn_ty("v", pinned_size.live_map),
            );
            check(
              typ,
              {|v is live ? -> Int under show("bump")|},
              Some(arrow(unknown(Internal), int())),
              pat_elab_syn_ty("v", pinned_bump.live_map),
            );
          }
        );
      },
    ),
    /* The same pin narrows the type instantiations. `a` is instantiated at
       Int inside `g` and at String inside `h`, and each TypAp's stack sits
       under its wrapper's call frame, so a pin on the wrapper keeps just
       that instantiation. */
    test_case(
      "Pinned call selects the instantiations a typfun parameter takes",
      `Quick,
      () => {
        let wrapper_program = (g_call, h_call) =>
          {|let f = typfun a -> fun (x : a) -> x in
let g = fun n -> f@<Int>(n) in
let h = fun s -> f@<String>(s) in
let _ = |}
          ++ g_call
          ++ {| in
|}
          ++ h_call;
        let g = {|g(1)|}
        and h = {|h("s")|};
        let unpinned = live_run(~pinned=false, wrapper_program(g, h));
        let pinned_g =
          live_run(~pinned=true, wrapper_program(probed(g), h));
        let pinned_h =
          live_run(~pinned=true, wrapper_program(g, probed(h)));
        check(
          int,
          "no static errors",
          0,
          List.length(StaticsBase.Map.error_ids(unpinned.static_map)),
        );
        let typ = Alcotest.option(Test_Statics_Prelude.testable_typ);
        Test_Statics_Prelude.FTemp.Typ.(
          {
            check(
              typ,
              "a joins both instantiations to ? unpinned",
              Some(unknown(Internal)),
              pat_ty_normalized("x", unpinned.live_map),
            );
            check(
              typ,
              "a is Int under g(1)",
              Some(int()),
              pat_ty_normalized("x", pinned_g.live_map),
            );
            check(
              typ,
              {|a is String under h("s")|},
              Some(string()),
              pat_ty_normalized("x", pinned_h.live_map),
            );
          }
        );
      },
    ),
  ],
);
