open Alcotest;
open Test_Evaluator_Prelude;
open Language;

[@deriving show({with_path: false})]
type error =
  | NoError
  | StaticError(list(Mark.t))
  | DynamicError(list(Mark.t));

/* Equality on Mark.t for tests.
   We can't use structural `==` on marks because some constructors carry
   `Typ.t` payloads whose `annotation.ids` are freshly generated by statics
   but are zeros in the test-built expected values. We compare via the
   derived show, which renders ids opaque, normalizing them away.
   INCOMPLETE: only the cases exercised by these tests are handled; extend
   here when adding tests that produce other Mark constructors. */
let mark_equal = (a: Language.Mark.t, b: Language.Mark.t): bool =>
  switch (a, b) {
  | (
      ExpectationMismatch({ana: ana1, syn: syn1}),
      ExpectationMismatch({ana: ana2, syn: syn2}),
    ) =>
    Typ.show(ana1) == Typ.show(ana2) && Typ.show(syn1) == Typ.show(syn2)
  | (ExpectationMismatch(_), _)
  | (_, ExpectationMismatch(_)) => false
  | _ =>
    failwith(
      "Test_Evaluator_LiveTyping.mark_equal: unhandled Mark constructor; "
      ++ "extend mark_equal to cover this case.",
    )
  };

let testable_error =
  testable(Fmt.using(show_error, Fmt.string), (a: error, b: error) =>
    switch (a, b) {
    | (NoError, NoError) => true
    | (StaticError(e1), StaticError(e2)) => List.equal(mark_equal, e1, e2)
    | (DynamicError(e1), DynamicError(e2)) => List.equal(mark_equal, e1, e2)
    | _ => false
    }
  );
module FError =
  Grammar.Factory({
    type t = error;
    let default_value = (): error => {
      NoError;
    };
  });

/**
 * Helper function to assemble live typing data map from samples and type instantiations.
 * This logic is shared between multiple test cases.
 */
let mk_live_typing =
    (
      probe_data: Id.Map.t(list(Sample.t)),
      type_insts: Dynamics.TypeInstMap.t,
    )
    : LiveTyping.Map.t => {
  LiveTyping.Map.mk(
    Id.Map.map(
      samples =>
        List.map(
          (s: Sample.t): LiveTyping.sample => {exp: s.value},
          samples,
        ),
      probe_data,
    ),
    Id.Map.map(
      List.map(
        (inst: Dynamics.TypeInstantiation.t): LiveTyping.type_instantiation =>
        {
          tpat_id: inst.tpat_id,
          type_var: inst.type_var,
          instantiated_type: inst.instantiated_type,
        }
      ),
      type_insts,
    ),
  );
};

/**
 * Maps static and live typing error information to error annotations.
 * Simplifies the nested switch logic with pattern matching.
 */
let map_error_annotation = (static_info, live_typing_info) => {
  let static_error =
    Option.map(Info.marks_of, static_info)
    |> Option.bind(_, ms =>
         switch (ms) {
         | [] => None
         | _ => Some(ms)
         }
       );
  let live_typing_error =
    Option.map(Info.marks_of, live_typing_info)
    |> Option.bind(_, ms =>
         switch (ms) {
         | [] => None
         | _ => Some(ms)
         }
       );

  switch (static_error, live_typing_error) {
  | (Some(e), _) => StaticError(e)
  | (None, Some(e)) => DynamicError(e)
  | (None, None) => NoError
  };
};

/**
 * Reusable test function for live typing validation.
 * Takes an expected expression with error annotations and verifies
 * that the live typing system correctly identifies errors.
 */
let test_live_typing = (~test_name=?, expected_exp: FError.exp) => {
  // Create expression with fresh IDs for static analysis
  let exp_with_ids: Exp.t =
    Grammar.map_exp_annotation(_ => IdTagged.IdTag.fresh(), expected_exp);

  let test_name =
    Util.OptUtil.get(
      () => {
        Haz3lcore.(
          Printer.of_segment(
            ~holes="?",
            ExpToSegment.exp_to_segment(
              ~settings=
                ExpToSegment.Settings.of_core(~inline=true, CoreSettings.off),
              exp_with_ids,
            ),
          )
        )
      },
      test_name,
    );

  // Perform initial static analysis (also produces elaborated expression).
  let (initial_statics, elaborated_exp) =
    Statics.mk(CoreSettings.on, Builtins.ctx_init(Some(Int)), exp_with_ids);

  let original_errors =
    StaticsBase.Map.errors(initial_statics) |> List.map(snd);
  Alcotest.check(
    Alcotest.int,
    "Expect no static errors initially",
    0,
    List.length(original_errors),
  );

  // Compute targets for expressions with unknown types (needed for live typing)
  let targets =
    Haz3lcore.CachedStatics.compute_targets(
      ~settings=CoreSettings.on,
      ~info_map=initial_statics,
      ~probe_ids=Id.Map.empty,
    );

  // Evaluate the elaborated expression to collect dynamic information
  let (_, evaluation_state) =
    Evaluator.evaluate(~targets, ~env=Builtins.env_init, elaborated_exp);

  // Extract probe data and type instantiations from the evaluation state
  let probe_data = EvaluatorState.get_probes(evaluation_state);
  let type_insts = EvaluatorState.get_type_insts(evaluation_state);

  // Convert probe closures and type instantiations to dynamic expressions for static re-analysis
  let dynamic_expressions = mk_live_typing(probe_data, type_insts);

  // Re-run static analysis with dynamic information
  let (live_typing_statics, _) =
    Statics.mk(
      ~dynamics=dynamic_expressions,
      CoreSettings.on,
      Builtins.ctx_init(Some(Int)),
      exp_with_ids,
    );

  // Map the expression to annotate errors based on static and live typing
  let actual_exp: FError.exp =
    Grammar.map_exp_annotation(
      id_tag => {
        let static_info =
          StaticsBase.Map.lookup(
            IdTagged.IdTag.rep_id(id_tag),
            initial_statics,
          );
        let live_typing_info =
          StaticsBase.Map.lookup(
            IdTagged.IdTag.rep_id(id_tag),
            live_typing_statics,
          );

        map_error_annotation(static_info, live_typing_info);
      },
      exp_with_ids,
    );

  let testable_annotated: testable(Grammar.exp_t(error)) =
    testable(
      Fmt.using([%derive.show: Grammar.exp_t(error)], Fmt.string),
      Grammar.equal_exp_t((a: error, b: error) =>
        switch (a, b) {
        | (NoError, NoError) => true
        | (StaticError(e1), StaticError(e2)) =>
          List.equal(mark_equal, e1, e2)
        | (DynamicError(e1), DynamicError(e2)) =>
          List.equal(mark_equal, e1, e2)
        | _ => false
        }
      ),
    );
  // Verify that the actual error annotations match expectations
  check(testable_annotated, test_name, expected_exp, actual_exp);
};
/* Adapter: previous tests wrote `inconsistent_exp(Expectation({ana, syn}))`.
   In the new architecture, type-mismatch errors are represented as the single
   Mark `ExpectationMismatch({ana, syn})`. */
type inconsistent_kind =
  | Expectation({
      ana: Typ.t,
      syn: Typ.t,
    });
let inconsistent_exp = (kind: inconsistent_kind): list(Mark.t) =>
  switch (kind) {
  | Expectation({ana, syn}) => [
      Mark.ExpectationMismatch({
        ana,
        syn,
      }),
    ]
  };

/* Property: for every expression-info id, the elab_syn_ty produced by static
   analysis run *with* live-typing dynamics is more precise than (or equal to)
   the elab_syn_ty produced by the static-only analysis. Refinement only ever
   moves down the precision lattice. */
let precision_property = (exp: Exp.t): bool =>
  try({
    let exp_with_ids =
      Grammar.map_exp_annotation(_ => IdTagged.IdTag.fresh(), exp);
    let ctx = Builtins.ctx_init(Some(Int));
    let (static_map, elaborated) =
      Statics.mk(CoreSettings.on, ctx, exp_with_ids);
    if (StaticsBase.Map.has_errors(static_map)) {
      true;
    } else {
      let targets =
        Haz3lcore.CachedStatics.compute_targets(
          ~settings=CoreSettings.on,
          ~info_map=static_map,
          ~probe_ids=Id.Map.empty,
        );
      let (_, state) =
        Evaluator.evaluate(~targets, ~env=Builtins.env_init, elaborated);
      let dynamics =
        mk_live_typing(
          EvaluatorState.get_probes(state),
          EvaluatorState.get_type_insts(state),
        );
      let (live_map, _) =
        Statics.mk(~dynamics, CoreSettings.on, ctx, exp_with_ids);
      Id.Map.for_all(
        (id, info_static) =>
          switch (info_static, StaticsBase.Map.lookup(id, live_map)) {
          | (Info.InfoExp(s), Some(Info.InfoExp(l))) =>
            Typ.is_more_precise(ctx, l.elab_syn_ty, s.elab_syn_ty)
          | _ => true
          },
        static_map,
      );
    };
  }) {
  | _ => true
  };

let precision_property_test =
  QCheck_alcotest.to_alcotest(
    QCheck.Test.make(
      ~name="Live type refines synthesized static type",
      ~count=500,
      QCheck_Util.arb_exp(~minimal_idents=true, 10),
      precision_property,
    ),
  );

let tests = (
  "Evaluator.LiveTyping",
  [
    precision_property_test,
    test_case(
      "dynamic in-editor feedback",
      `Slow,
      () => {
        let program = {hazel|
let unique = (fun xs ->
  fold_left(xs, fun (seen, x) ->if mem(seen,x) then seen else seen @[x], []))in
let pivot_table = (fun (table, new_col, index, value) ->
  let indices = map(table, index) |> unique in
  let new_cols = map(table, new_col) |> unique in

  map(indices, fun idx ->
    (index=idx) ...
    (map(new_cols, fun col ->
      (label=col,
        value=filter(table, fun r -> index(r) == idx && new_col(r) == col)
        |>value)
    ) |> from_lvs)
  ))in



let results =
  pivot_table(
    [(a=1,b=2,c=3), (a=1,b=2,c=3), (a=1,b=2,c=3), (a=1,b=2,c=3) ,(a=1,b=2,c=3)]
    @ [(a=1,b=2,c=3), (a=1,b=2,c=3), (a=1,b=2,c=3), (a=1,b=2,c=3) ,(a=1,b=2,c=3)],
    fun r -> r.a |> string_of_int,
    fun r -> r.b,
    fun r -> fold_left(r.c, int_plus, 0))
in

(results).`2`
|hazel};
        let exp = parse_exp(program);
        let (_, elaborated) =
          Statics.mk(CoreSettings.on, Builtins.ctx_init(Some(Int)), exp);
        let (result, state: EvaluatorState.t) =
          Evaluator.evaluate(~env=Builtins.env_init, elaborated);

        let dynamics = EvaluatorState.get_probes(state);
        let type_insts = EvaluatorState.get_type_insts(state);

        // Convert probe closures and type instantiations to dynamic expressions for static re-analysis
        let dynamic_expressions = mk_live_typing(dynamics, type_insts);
        let _static_feedback =
          Statics.mk(
            ~dynamics=dynamic_expressions,
            CoreSettings.on,
            Builtins.ctx_init(Some(Int)),
            exp,
          );

        let expected_exp =
          parse_exp({hz|
          [(index=2, `1`=30).`2`]
          |hz});
        check(testable_exp(), "Result of execution", expected_exp, result);
      },
    ),
    test_case(
      "Type flows through unknown ascription dynamically",
      `Quick,
      () => {
        // Create expected expression with dynamic error annotation
        // This tests that int(1) : ? : String correctly identifies
        // the type inconsistency when ? is resolved to int but expected as string
        let expected_exp: FError.exp =
          FError.(
            Exp.(
              asc(
                asc(
                  ~ann=
                    DynamicError(
                      inconsistent_exp(
                        Test_Statics_Prelude.FTemp.Typ.(
                          Expectation({
                            ana: string(),
                            syn: int(),
                          })
                        ),
                      ),
                    ),
                  int(1),
                  Typ.unknown(Internal),
                ),
                Typ.string(),
              )
            )
          );

        test_live_typing(expected_exp);
      },
    ),
    /* DISABLED: live-typing duplicates the inner branch's ExpectationMismatch
          onto the surrounding `If` expression. Tracked in
          https://github.com/hazelgrove/hazel/issues/2265. Re-enable once the
          extra mark on the If is removed.
       test_case(
         "Conditional uses runtime type information",
         `Quick,
         () => {
           open FError;
           open Exp;

           test_live_typing(
             bin_op(
               String(Concat),
               if_(
                 bool(true),
                 asc(
                   ~ann=
                     DynamicError(
                       inconsistent_exp(
                         Test_Statics_Prelude.FTemp.Typ.(
                           Expectation({
                             ana: string(),
                             syn: int(),
                           })
                         ),
                       ),
                     ),
                   int(1),
                   Typ.unknown(Internal),
                 ),
                 asc(string("World"), Typ.unknown(Internal)),
               ),
               string("World"),
             ),
           );
           test_live_typing(
             bin_op(
               String(Concat),
               if_(
                 bool(false),
                 asc(int(1), Typ.unknown(Internal)),
                 asc(string("Hello"), Typ.unknown(Internal)),
               ),
               string("World"),
             ),
           );
         },
       ),
       */
    test_case(
      "Unannotated lambda applied to string causes dynamic error",
      `Quick,
      () => {
        open FError;
        open Exp;
        let exp: FError.exp =
          ap(
            Forward,
            fn(
              Pat.var("y"),
              bin_op(
                Int(Plus),
                var(
                  ~ann=
                    DynamicError(
                      inconsistent_exp(
                        Test_Statics_Prelude.FTemp.Typ.(
                          Expectation({
                            ana: int(),
                            syn: string(),
                          })
                        ),
                      ),
                    ),
                  "y",
                ),
                int(1),
              ),
            ),
            string(""),
          );
        test_live_typing(exp);
      },
    ),
    test_case(
      "Unannotated lambda called with inconsistent types gives no feedback",
      `Quick,
      () => {
        let program = {|let f = fun x -> x @ [""] in f(1);f(2.0)|};
        let exp = parse_exp(program);
        let no_errors = Grammar.map_exp_annotation(_ => NoError, exp);

        test_live_typing(no_errors);
      },
    ),
    test_case(
      "typfun uses dynamic type env with correct type",
      `Quick,
      () => {
        let program = {|(typfun a -> fun x : a -> (x : a))@<String>("")|};
        let exp = parse_exp(program);
        let no_errors = Grammar.map_exp_annotation(_ => NoError, exp);

        test_live_typing(
          ~test_name={|(typfun a -> fun x : a -> (x : a))@<String>("")|},
          no_errors,
        );
      },
    ),
    test_case(
      "typfun uses dynamic type env with incorrect type",
      `Quick,
      () => {
        open FError;
        open Exp;

        let exp: FError.exp =
          ap(
            Forward,
            typ_ap(
              typ_fun(
                TPat.var("a"),
                fn(
                  Pat.var("x"),
                  asc(
                    asc(
                      ~ann=
                        DynamicError(
                          inconsistent_exp(
                            Test_Statics_Prelude.FTemp.Typ.(
                              Expectation({
                                ana: var("a"),
                                syn: string(),
                              })
                            ),
                          ),
                        ),
                      var("x"),
                      Typ.unknown(Hole(EmptyHole)),
                    ),
                    Typ.var("a"),
                  ),
                ),
                None,
              ),
              Typ.int(),
            ),
            string(""),
          );
        test_live_typing(
          ~test_name={|(typfun a -> fun x -> (x : ? : a))@<Int>("")|},
          exp,
        );
      },
    ),
    test_case(
      "typfun with matching type instantiation: no error",
      `Quick,
      () => {
        open FError;
        open Exp;
        /* Same shape as the previous test, but instantiated to <String>
           with a String argument: a := String, x := "", so the inner
           Asc body has type String which matches `a`. Live-typing must
           consult the type-instantiation map to resolve `a` to `String`;
           if it leaves `a` Abstract, meet(Var("a"), String) fails and a
           spurious DynamicError is reported. */
        let exp: FError.exp =
          ap(
            Forward,
            typ_ap(
              typ_fun(
                TPat.var("a"),
                fn(
                  Pat.var("x"),
                  asc(
                    asc(var("x"), Typ.unknown(Hole(EmptyHole))),
                    Typ.var("a"),
                  ),
                ),
                None,
              ),
              Typ.string(),
            ),
            string(""),
          );
        test_live_typing(
          ~test_name={|(typfun a -> fun x -> (x : ? : a))@<String>("")|},
          exp,
        );
      },
    ),
    test_case(
      "Polymorphism with dynamic type environment in unevaluated code",
      `Quick,
      () => {
        let program = {|(typfun a -> fun (g) -> (fun () -> g : a))@<String>("")|};
        let exp = parse_exp(program);
        let no_errors = Grammar.map_exp_annotation(_ => NoError, exp);
        test_live_typing(~test_name=program, no_errors);
      },
    ),
  ],
);
