#!/usr/bin/env python3
"""
Python build system for Gradescope autograders
Equivalent to the Perl Makefile system
"""

import os
import sys
import shutil
import subprocess
import zipfile
from pathlib import Path
import argparse


def check_syntax(script_path):
    """Check Python script syntax (equivalent to perl -c)"""
    try:
        result = subprocess.run([sys.executable, '-m', 'py_compile', script_path], 
                              capture_output=True, text=True, check=True)
        print(f"✓ Syntax check passed for {script_path}")
        return True
    except subprocess.CalledProcessError as e:
        print(f"✗ Syntax error in {script_path}:")
        print(e.stderr)
        return False


def prepare_main_script(source_script):
    """
    Prepare the main test script (no need for standalone packaging in Python)
    """
    print(f"Using test script: {source_script}")
    
    # Make sure it's executable
    os.chmod(source_script, 0o755)
    
    print(f"✓ Prepared {source_script}")


def copy_lib_files():
    """Copy library files (equivalent to rsync -a ../lib/ lib)"""
    lib_source = Path("../lib")
    lib_dest = Path("lib")
    
    if lib_source.exists():
        if lib_dest.exists():
            shutil.rmtree(lib_dest)
        shutil.copytree(lib_source, lib_dest)
        print("✓ Copied library files")
    else:
        print("ⓘ No library files to copy")


def create_run_autograder_bash(source_script):
    """Create bash run_autograder script (equivalent to Perl version)"""
    bash_content = f'''#!/usr/bin/env bash
# see
# https://gradescope-autograders.readthedocs.io/en/latest/specs/

cd /autograder/source
python3 {source_script}
'''
    
    with open("run_autograder", "w") as f:
        f.write(bash_content)
    
    os.chmod("run_autograder", 0o755)
    print("✓ Created run_autograder bash script")


def create_setup_script():
    """Create setup.sh for dependencies (simplified version)"""
    setup_content = '''#!/bin/bash
# THIS FILE IS AUTOGENERATED-- SEE build.py

# Install Python dependencies
pip install -r requirements.txt 2>/dev/null || echo "No requirements.txt found"

# Install any additional system packages if needed
# apt-get update && apt-get install -y <packages>
'''
    
    with open("setup.sh", "w") as f:
        f.write(setup_content)
    
    os.chmod("setup.sh", 0o755)
    print("✓ Created setup.sh")


def create_requirements_file(script_path):
    """Create requirements.txt based on imports (simplified)"""
    # This is a simplified version - you could use pipreqs or similar tools
    # for automatic dependency detection
    
    common_packages = {
        'requests': 'requests',
        'numpy': 'numpy', 
        'pandas': 'pandas',
        'matplotlib': 'matplotlib',
        # Add more as needed
    }
    
    requirements = []
    
    try:
        with open(script_path, 'r') as f:
            content = f.read()
            for package, pip_name in common_packages.items():
                if f'import {package}' in content or f'from {package}' in content:
                    requirements.append(pip_name)
    except FileNotFoundError:
        pass
    
    if requirements:
        with open("requirements.txt", "w") as f:
            for req in requirements:
                f.write(f"{req}\n")
        print(f"✓ Created requirements.txt with {len(requirements)} packages")
    else:
        print("ⓘ No external dependencies detected")


def create_zip(source_script):
    """Create AG.zip file"""
    with zipfile.ZipFile("AG.zip", "w", zipfile.ZIP_DEFLATED) as zf:
        # Add all relevant files
        files_to_zip = [
            "run_autograder",  # Bash script entry point (no .py extension)
            source_script,     # Use the original script directly
            "setup.sh"
        ]
        
        # Add requirements.txt if it exists
        if Path("requirements.txt").exists():
            files_to_zip.append("requirements.txt")
        
        # Add lib directory if it exists
        lib_dir = Path("lib")
        if lib_dir.exists():
            for file_path in lib_dir.rglob("*"):
                if file_path.is_file():
                    zf.write(file_path)
        
        for file_name in files_to_zip:
            if Path(file_name).exists():
                zf.write(file_name)
        
        print("✓ Created AG.zip")


def build_autograder(target):
    """Build a specific autograder target"""
    print(f"Building autograder: {target}")
    
    # Determine source script
    if target == "default":
        source_script = "run_test_base.py"
    else:
        source_script = f"run_test_{target.replace('-', '_')}.py"
    
    if not Path(source_script).exists():
        print(f"✗ Source script {source_script} not found")
        return False
    
    # Check syntax
    if not check_syntax(source_script):
        return False
    
    # Copy library files
    copy_lib_files()
    
    # Prepare main script
    prepare_main_script(source_script)
    
    # Create bash run_autograder entry point
    create_run_autograder_bash(source_script)
    
    # Create setup script
    create_setup_script()
    
    # Create requirements file
    create_requirements_file(source_script)
    
    # Create zip file
    create_zip(source_script)
    
    print(f"✓ Successfully built {target} autograder")
    return True


def clean():
    """Clean build artifacts"""
    artifacts = ["AG.zip", "lib", "setup.sh", "run_autograder", "requirements.txt"]
    
    for artifact in artifacts:
        path = Path(artifact)
        if path.is_file():
            path.unlink()
            print(f"✓ Removed {artifact}")
        elif path.is_dir():
            shutil.rmtree(path)
            print(f"✓ Removed directory {artifact}")


def main():
    parser = argparse.ArgumentParser(description="Build Gradescope autograders")
    parser.add_argument("target", nargs="?", default="default", 
                       help="Target to build (default, grade-hazel, check-hazel, etc.)")
    parser.add_argument("--clean", action="store_true", help="Clean build artifacts")
    
    args = parser.parse_args()
    
    if args.clean:
        clean()
        return
    
    success = build_autograder(args.target)
    if not success:
        sys.exit(1)


if __name__ == "__main__":
    main()
