open Util;
open Sort;
module P = Precedence;

/* This module determines the syntactic extent of the language; the
 * entire Syntax module is driven by the below definitions. To add
 * a new syntactic form add a case to either the atomic_form or
 * compound_form types and follow the errors. The cases in their
 * corresponding `get` functions determine the shape, precedence,
 * and expansion behavior of the form.*/

/* When you complete a token corresponding to a delimiter of a
 * compound form, that token might be 'expanded', which is to say,
 * converted from a monotile to a incomplete polytile aka shard
 * representing a part of specific form. All leading delimiters
 * of all forms trigger expansion, but not all trailing
 * delimiters, for example ambiguous trailing delimiters like
 * `in` or `>`. Thus we designate certain delimiters as expanding
 * on a per-form basis. Expanding delimiters should be globally
 * unique, and indeed it would probably be better if we dispensed
 * with this explicit classification and instead derived this
 * information from the grammar. Currently all forms fall into two
 * classes: Either only the leading delimiter triggers expansion,
 * or the leading and trailing delimiters trigger expansion */
[@deriving (show({with_path: false}), sexp, yojson)]
type expansion =
  | Non /* Non-expandind: Placeholder for atomic forms */
  | L /* Leading-only: All keyword forms and some special cases */
  | LT; /* Leading and trailing: Used for parethesis-like things */

[@deriving (show({with_path: false}), sexp, yojson)]
type expansions = list((Token.t, (Label.t, Direction.t)));

/* A label, a mold, and expansion behavior together determine a form. */
[@deriving (show({with_path: false}), sexp, yojson)]
type t = {
  label: Label.t,
  mold: Mold.t,
  expansion,
};

let mk = (expansion, label, mold) => {
  label,
  mold,
  expansion,
};

let op = Mold.mk_op(_, []);

let mk_atom = (t: Token.t, mold_of) => mk(Non, [t], mold_of([]));

let mk_atom_op = (sort: Sort.t, t: Token.t) => mk_atom(t, Mold.mk_op(sort));

let mk_infix = (t: Token.t, sort: Sort.t, ~l=?, ~r=?, prec) =>
  mk_atom(t, Mold.mk_bin(prec, sort, ~l?, ~r?));

let mk_prefix = (t: Token.t, sort: Sort.t, prec) =>
  mk_atom(t, Mold.mk_pre(prec, sort));

let mk_pre_c =
    (exp, label: Label.t, prec, sort: Sort.t, inner_sorts: list(Sort.t)) =>
  mk(exp, label, Mold.mk_pre(prec, sort, inner_sorts));

let mk_op_c = (exp, label: Label.t, sort: Sort.t, inner_sorts: list(Sort.t)) =>
  mk(exp, label, Mold.mk_op(sort, inner_sorts));

let mk_post_c =
    (exp, label: Label.t, prec, sort: Sort.t, child_sorts: list(Sort.t)) =>
  mk(exp, label, Mold.mk_post(prec, sort, child_sorts));

let mk_parens = (sort: Sort.t) =>
  mk_op_c(LT, Token.tuple_lbl, sort, [sort]);

/* B. Operands:
   Order in this type determines relative remolding
   priority for forms with overlapping regexps */

[@deriving enumerate]
type atomic_form =
  | Var
  | DrvVar
  | ExplicitHole
  | LLMHole
  | Wild
  | String
  | QuotedLabel
  | IntLit
  | FloatLit
  | BoolLit
  | LivelitName
  | ProjectorInvoke
  | UndefinedLit
  | EmptyList
  | EmptyTuple
  | Deferral
  | TyVar
  | TyVarP
  | Ctr
  | Type
  | InfixDelimiterPrefix;

/* C. Compound Forms:
   Order in this type determines relative remolding
   priority for forms which share the same labels
   A list of all possible compound_forms is automatically
   generated by @deriving enumerate */

[@deriving enumerate]
type drv_compound_form =
  // Interface to normal forms
  | OfProp
  | OfCtx
  | OfJdmt
  | OfAlfaExp
  | OfAlfaTyp
  | OfAlfaPat
  | OfAlfaTPat
  // Formula (only for pretty printing)
  | Subst
  | SubstTy
  | Glb
  // Judgments
  | Val
  | Eval
  | Entail
  | UnaryEntail
  | Consistent
  | ConsistentFake
  | MatchedArrow
  | MatchedArrowFake
  | MatchedProd
  | MatchedProdFake
  | MatchedSum
  | MatchedSumFake
  // Proposition
  | Valid
  | HasType
  | Syn
  | Ana
  | And
  | Or
  | Impl
  | Not
  // Ctx
  | Cons
  | Concat
  | List
  // Exp
  | Neg
  | Plus
  | Minus
  | Times
  | Eq
  | Lt
  | Gt
  | If
  | Let
  | Fix
  | Fun
  | Dot
  | Case
  | Rule
  // Pat
  | Cast
  // Typ
  | Arrow
  | Prod
  | Sum
  | Rec
  // Shared
  | ApExp
  | ApPat
  | CommaExp
  | CommaPat
  | ParenProp
  | ParenExp
  | ParenPat
  | ParenTyp
  | QuoteExp
  | QuotePat
  | QuoteTyp
  | QuoteTPat;

let drv_get: drv_compound_form => t =
  fun
  | OfJdmt => mk_op_c(L, ["of_jdmt", "end"], Exp, [Drv(Exp)])
  | OfCtx => mk_op_c(L, ["of_ctx", "end"], Exp, [Drv(Exp)])
  | OfProp => mk_op_c(L, ["of_prop", "end"], Exp, [Drv(Exp)])
  | OfAlfaExp => mk_op_c(L, ["of_alfa_exp", "end"], Exp, [Drv(Exp)])
  | OfAlfaTyp => mk_op_c(L, ["of_alfa_typ", "end"], Exp, [Drv(Typ)])
  | OfAlfaPat => mk_op_c(L, ["of_alfa_pat", "end"], Exp, [Drv(Pat)])
  | OfAlfaTPat => mk_op_c(L, ["of_alfa_tpat", "end"], Exp, [Drv(TPat)])
  | Subst =>
    mk_pre_c(
      Non,
      ["[", "/", "]"],
      P.fun_,
      Drv(Exp),
      [Drv(Exp), Drv(Pat)],
    )
  | SubstTy =>
    mk_pre_c(
      Non,
      ["[", "/", "]"],
      P.fun_,
      Drv(Typ),
      [Drv(Typ), Drv(TPat)],
    )
  | Glb => mk_op_c(L, ["glb(", ",", ")"], Drv(Typ), [Drv(Typ), Drv(Typ)])
  | Val => mk_op_c(L, ["val", "end"], Drv(Exp), [Drv(Exp)])
  | Eval => mk_infix("\\=/", Drv(Exp), P.min)
  | Entail => mk_infix("|-", Drv(Exp), P.min)
  | UnaryEntail => mk_pre_c(L, ["|-"], P.min, Drv(Exp), [Drv(Exp)])
  // Note(zhiyao):
  // Auto complete is only available for sort Exp, that's why
  // we need a fake_consistent to make it work for Drv(Exp)
  | ConsistentFake =>
    mk_pre_c(L, ["consistent", "~"], P.fun_, Exp, [Drv(Typ)])
  | Consistent =>
    mk(
      LT,
      ["consistent", "~"],
      Mold.mk_pre'(P.fun_, Drv(Exp), Drv(Exp), [Drv(Typ)], Drv(Typ)),
    )
  | MatchedArrowFake =>
    mk_pre_c(L, ["matched_arrow", "with"], P.fun_, Exp, [Drv(Typ)])
  | MatchedArrow =>
    mk(
      LT,
      ["matched_arrow", "with"],
      Mold.mk_pre'(P.fun_, Drv(Exp), Drv(Exp), [Drv(Typ)], Drv(Typ)),
    )
  | MatchedProdFake =>
    mk_pre_c(L, ["matched_prod", "with"], P.fun_, Exp, [Drv(Typ)])
  | MatchedProd =>
    mk(
      L,
      ["matched_prod", "with"],
      Mold.mk_pre'(P.fun_, Drv(Exp), Drv(Exp), [Drv(Typ)], Drv(Typ)),
    )
  | MatchedSumFake =>
    mk_pre_c(L, ["matched_sum", "with"], P.fun_, Exp, [Drv(Typ)])
  | MatchedSum =>
    mk(
      L,
      ["matched_sum", "with"],
      Mold.mk_pre'(P.fun_, Drv(Exp), Drv(Exp), [Drv(Typ)], Drv(Typ)),
    )
  | Valid => mk_op_c(L, ["valid", "end"], Drv(Exp), [Drv(Typ)])
  | HasType =>
    mk(LT, [":"], Mold.mk_bin'(P.ann, Drv(Exp), Drv(Exp), [], Drv(Typ)))
  | Syn =>
    mk(LT, ["=>"], Mold.mk_bin'(P.ann, Drv(Exp), Drv(Exp), [], Drv(Typ)))
  | Ana =>
    mk(LT, ["<="], Mold.mk_bin'(P.ann, Drv(Exp), Drv(Exp), [], Drv(Typ)))
  | And => mk_infix("/\\", Drv(Exp), P.and_)
  | Or => mk_infix("\\/", Drv(Exp), P.or_)
  | Impl => mk_infix("==>", Drv(Exp), P.impl)
  | Not => mk_pre_c(L, ["!"], P.neg, Drv(Exp), [])
  | Cons =>
    mk(
      LT,
      ["::"],
      Mold.mk_bin'(P.cons, Drv(Exp), Drv(Exp), [], Drv(Exp)),
    )
  | Concat => mk_infix("@", Drv(Exp), P.plus)
  | List => mk_op_c(LT, ["[", "]"], Drv(Exp), [Drv(Exp)])
  | Neg => mk_pre_c(L, ["-"], P.neg, Drv(Exp), [])
  | Plus => mk_infix("+", Drv(Exp), P.plus)
  | Minus => mk_infix("-", Drv(Exp), P.plus)
  | Times => mk_infix("*", Drv(Exp), P.mult)
  | Eq => mk_infix("==", Drv(Exp), P.eqs)
  | Lt => mk_infix("<", Drv(Exp), P.eqs)
  | Gt => mk_infix(">", Drv(Exp), P.eqs)
  | If =>
    mk_pre_c(
      L,
      ["if", "then", "else"],
      P.if_,
      Drv(Exp),
      [Drv(Exp), Drv(Exp)],
    )
  | Let =>
    mk_pre_c(
      L,
      ["let", "=", "in"],
      P.let_,
      Drv(Exp),
      [Drv(Pat), Drv(Exp)],
    )
  | Fix => mk_pre_c(L, ["fix", "->"], P.fun_, Drv(Exp), [Drv(Pat)])
  | Fun => mk_pre_c(L, ["fun", "->"], P.fun_, Drv(Exp), [Drv(Pat)])
  | Dot => mk_infix(".", Drv(Exp), P.dot)
  | Case => mk_op_c(L, ["case", "end"], Drv(Exp), [Drv(Exp)])
  | Rule =>
    mk(
      L,
      ["|", "=>"],
      Mold.mk_bin'(P.rule_sep, Drv(Exp), Drv(Exp), [Drv(Pat)], Drv(Exp)),
    )
  | Cast =>
    mk(LT, [":"], Mold.mk_bin'(P.asc, Drv(Pat), Drv(Pat), [], Drv(Typ)))
  | Arrow => mk_infix("->", Drv(Typ), P.type_arrow)
  | Prod => mk_infix("*", Drv(Typ), P.type_prod)
  | Sum => mk_infix("+", Drv(Typ), P.type_plus)
  | Rec => mk_pre_c(L, ["rec", "->"], P.fun_, Drv(Typ), [Drv(TPat)])
  | ApExp => mk_post_c(LT, ["(", ")"], P.ap, Drv(Exp), [Drv(Exp)])
  | ApPat => mk_post_c(LT, ["(", ")"], P.ap, Drv(Pat), [Drv(Pat)])
  | CommaExp => mk_infix(",", Drv(Exp), P.comma)
  | CommaPat => mk_infix(",", Drv(Pat), P.comma)
  | ParenProp => mk_op_c(LT, ["(", ")"], Drv(Jdmt), [Drv(Jdmt)])
  | ParenExp => mk_op_c(LT, ["(", ")"], Drv(Exp), [Drv(Exp)])
  | ParenPat => mk_op_c(LT, ["(", ")"], Drv(Pat), [Drv(Pat)])
  | ParenTyp => mk_op_c(LT, ["(", ")"], Drv(Typ), [Drv(Typ)])
  | QuoteExp => mk_pre_c(L, ["$"], P.unquote, Drv(Exp), [])
  | QuotePat => mk_pre_c(L, ["$"], P.unquote, Drv(Pat), [])
  | QuoteTyp => mk_pre_c(L, ["$"], P.max, Drv(Typ), [])
  | QuoteTPat => mk_pre_c(L, ["$"], P.unquote, Drv(TPat), []);

[@deriving enumerate]
type compound_form =
  // INFIX OPERATORS
  | TypeArrow
  | CellJoin
  | Plus
  | Minus
  | Times
  | Power
  | FPower
  | Divide
  | Equals
  | StringEquals
  | StringConcat
  | Lt
  | Gt
  | NotEquals
  | Gte
  | Lte
  | FPlus
  | FMinus
  | FTimes
  | FDivide
  | FEquals
  | FLt
  | FGt
  | FNotEquals
  | FGte
  | FLte
  | LogicalAnd
  | LogicalOrLegacy
  | LogicalOr
  | ListConcat
  | ConsExp
  | ConsPat
  | Typeann
  | TupleLabeledExp
  | TupleLabeledPat
  | TupleLabeledTyp
  | DotExp
  | TupleExtension
  | DotTyp
  | TypeAsc
  | TypPlus
  // UNARY PREFIX OPERATORS
  | Not
  | TypSumSingle
  | UnaryMinus
  | Unquote
  // N-ARY OPS (on the semantics level)
  | CommaExp
  | CommaPat
  | CommaTyp
  // PAIRED DELIMITERS:
  | ListLitExp
  | ListLitPat
  | ListTyp
  //NOTE(andrew): parens being below aps is load-bearing, unfortunately
  | ParensExp
  | ParensPat
  | ParensTyp
  | ApExpEmpty
  | ApExp
  | ApPat
  | ApTyp
  | ApExpTyp
  | Case
  | Test
  | HintedTest
  | Fun
  | Fix
  | TypFun
  | Forall
  | Rec
  | Rule
  | Pipeline
  // DOUBLE DELIMITERS
  | FilterHide
  | FilterEval
  | FilterPause
  | FilterDebug
  | Use
  // Drv
  | Drv(drv_compound_form)
  | DrvQuotePat
  // TRIPLE DELIMITERS
  | Let
  | TypeAlias
  | If;

let get: compound_form => t =
  fun
  // INFIX OPERATORS
  | TypeArrow => mk_infix("->", Typ, P.type_arrow)
  | CellJoin => mk_infix(";", Exp, P.semi)
  | Plus => mk_infix("+", Exp, P.plus)
  | Minus => mk_infix("-", Exp, P.plus)
  | Times => mk_infix("*", Exp, P.mult)
  | Power => mk_infix("**", Exp, P.power)
  | FPower => mk_infix("**.", Exp, P.power)
  | Divide => mk_infix("/", Exp, P.mult)
  | Equals => mk_infix("==", Exp, P.eqs)
  | StringEquals => mk_infix("$==", Exp, P.eqs)
  | StringConcat => mk_infix("++", Exp, P.concat)
  | Lt => mk_infix("<", Exp, P.eqs)
  | Gt => mk_infix(">", Exp, P.eqs)
  | NotEquals => mk_infix("!=", Exp, P.eqs)
  | Gte => mk_infix(">=", Exp, P.eqs)
  | Lte => mk_infix("<=", Exp, P.eqs)
  | FPlus => mk_infix("+.", Exp, P.plus)
  | FMinus => mk_infix("-.", Exp, P.plus)
  | FTimes => mk_infix("*.", Exp, P.mult)
  | FDivide => mk_infix("/.", Exp, P.mult)
  | FEquals => mk_infix("==.", Exp, P.eqs)
  | FLt => mk_infix("<.", Exp, P.eqs)
  | FGt => mk_infix(">.", Exp, P.eqs)
  | FNotEquals => mk_infix("!=.", Exp, P.eqs)
  | FGte => mk_infix(">=.", Exp, P.eqs)
  | FLte => mk_infix("<=.", Exp, P.eqs)
  | LogicalAnd => mk_infix("&&", Exp, P.and_)
  | LogicalOrLegacy => mk_infix("\\/", Exp, P.or_)
  | LogicalOr => mk_infix("||", Exp, P.or_)
  | ListConcat => mk_infix("@", Exp, P.concat)
  | ConsExp => mk_infix("::", Exp, P.cons)
  | ConsPat => mk_infix("::", Pat, P.cons)
  | Typeann => mk_infix(":", Pat, ~l=Pat, ~r=Typ, P.asc)
  | TupleLabeledExp => mk_infix("=", Exp, P.lab)
  | TupleLabeledPat => mk_infix("=", Pat, P.lab)
  | TupleLabeledTyp => mk_infix("=", Typ, P.lab)
  | DotExp => mk_infix(".", Exp, P.dot)
  | DotTyp => mk_infix(".", Typ, P.dot)
  | TypeAsc => mk_infix(":", Exp, ~l=Exp, ~r=Typ, P.asc)
  | TupleExtension => mk_infix("...", Exp, P.plus)
  | TypPlus => mk_infix("+", Typ, P.type_plus)
  // UNARY PREFIX OPERATORS
  | Not => mk_prefix("!", Exp, P.not_)
  | TypSumSingle => mk_prefix("+", Typ, P.or_)
  | UnaryMinus => mk_prefix("-", Exp, P.neg)
  | Unquote => mk_prefix("$", Exp, P.unquote)
  // N-ARY OPS (on the semantics level)
  | CommaExp => mk_infix(",", Exp, P.comma)
  | CommaPat => mk_infix(",", Pat, P.comma)
  | CommaTyp => mk_infix(",", Typ, P.comma)
  // PAIRED DELIMITERS:
  | ListLitExp => mk_op_c(LT, ["[", "]"], Exp, [Exp])
  | ListLitPat => mk_op_c(LT, ["[", "]"], Pat, [Pat])
  | ListTyp => mk_op_c(LT, ["[", "]"], Typ, [Typ])
  //NOTE(andrew): parens being below aps is load-bearing, unfortunately
  | ParensExp => mk_parens(Exp)
  | ParensPat => mk_parens(Pat)
  | ParensTyp => mk_parens(Typ)
  | ApExpEmpty => mk_post_c(LT, ["()"], P.ap, Exp, [])
  | ApExp => mk_post_c(LT, ["(", ")"], P.ap, Exp, [Exp])
  | ApPat => mk_post_c(LT, ["(", ")"], P.ap, Pat, [Pat])
  | ApTyp => mk_post_c(LT, ["(", ")"], P.type_sum_ap, Typ, [Typ])
  | ApExpTyp => mk_post_c(L, ["@<", ">"], P.ap, Exp, [Typ])
  | Case => mk_op_c(L, ["case", "end"], Exp, [Rul])
  | Test => mk_op_c(L, ["test", "end"], Exp, [Exp])
  | Fun => mk_pre_c(L, ["fun", "->"], P.fun_, Exp, [Pat])
  | Fix => mk_pre_c(L, ["fix", "->"], P.fun_, Exp, [Pat])
  | TypFun => mk_pre_c(L, ["typfun", "->"], P.fun_, Exp, [TPat])
  | Forall => mk_pre_c(L, ["forall", "->"], P.fun_, Typ, [TPat])
  | Rec => mk_pre_c(L, ["rec", "->"], P.fun_, Typ, [TPat])
  | Rule =>
    mk(L, ["|", "=>"], Mold.mk_bin'(P.rule_sep, Rul, Exp, [Pat], Exp))
  | Pipeline => mk_infix("|>", Exp, P.eqs) // in OCaml, pipeline precedence is in same class as '=', '<', etc.
  // DOUBLE DELIMITERS
  | FilterHide => mk_pre_c(L, ["hide", "in"], P.let_, Exp, [Exp])
  | FilterEval => mk_pre_c(L, ["eval", "in"], P.let_, Exp, [Exp])
  | FilterPause => mk_pre_c(L, ["pause", "in"], P.let_, Exp, [Exp])
  | FilterDebug => mk_pre_c(L, ["debug", "in"], P.let_, Exp, [Exp])
  | Use => mk_pre_c(L, ["use", "in"], P.let_, Exp, [Typ])
  // Drv
  | Drv(drv_compound_form) => drv_get(drv_compound_form)
  | DrvQuotePat => mk_pre_c(L, ["$"], P.unquote, Pat, [])
  // TRIPLE DELIMITERS
  | Let => mk_pre_c(L, ["let", "=", "in"], P.let_, Exp, [Pat, Exp])
  | TypeAlias => mk_pre_c(L, ["type", "=", "in"], P.let_, Exp, [TPat, Typ])
  | If => mk_pre_c(L, ["if", "then", "else"], P.if_, Exp, [Exp, Exp])
  | HintedTest => mk_op_c(L, ["hint", "test", "end"], Exp, [Exp, Exp]);

let forms: list((compound_form, t)) =
  List.map(f => (f, get(f)), all_of_compound_form);

let delims: list(Token.t) =
  forms |> List.concat_map(((_, t)) => t.label) |> List.sort_uniq(compare);

/* These are tokens that have proven annoying as TyDi suggestions.
 * This category is doubly nominative in that it has proven hard
 * to derive automatically; typically these are annoying bacause
 * they have a prefix that occurs more commonly */
let annoying_delims = ["|>", "||", "::", "!=", "!=.", "**."];
let is_annoying_delim = List.mem(_, annoying_delims);

/* Returns a list of all strings which are proper prefixes of
 * a non-leading alphanumeric concave delimiter of a compount form.
 * These are assigned a special backup infix-op mode, so that
 * when you're entering e.g. the `in` in a let, you don't get
 * disruptive switching between a convex variable and concaved
 * delimiter */
let infix_delimiter_ops_prefixes: list(Token.t) =
  forms
  |> List.filter_map(((form: compound_form, _)) => {
       let form = get(form);
       switch ((form.mold.nibs |> snd).shape) {
       /* Could be pickier here, e.g. just trailing delimiters */
       | _ when List.length(form.label) >= 2 => Some(form.label)
       | _ => None
       };
     })
  |> List.concat
  |> List.filter(Token.is_potential_operand)
  |> List.sort_uniq(compare)
  |> List.map(Token.prefixes)
  |> List.concat;

let is_infix_delimiter_op_prefix = List.mem(_, infix_delimiter_ops_prefixes);

/* Tokens that appear both as single-token labels and in other forms labels.
 * These have special put-down behavior to make sure we can actually enter
 * the single-delimiter variant during left-to-right entry */
let amiguous_polymorphs: list(Token.t) = {
  let single_token_labels =
    forms
    |> List.filter_map(((_, {label, _})) =>
         switch (label) {
         | [token] => Some(token)
         | _ => None
         }
       )
    |> Token.sort_uniq;
  let appears_in_other_forms = (target_token: Token.t): bool => {
    forms
    |> List.exists(((_, {label, _})) =>
         switch (label) {
         | [token] when token == target_token => false
         | label => List.mem(target_token, label)
         }
       );
  };
  single_token_labels |> List.filter(appears_in_other_forms);
};

let is_ambiguous_polymorph = List.mem(_, amiguous_polymorphs);

let get_atomic_form: atomic_form => (Token.t => bool, list(Mold.t)) =
  fun
  | Var => (Token.is_var, [op(Exp), op(Pat)])
  | InfixDelimiterPrefix => (
      is_infix_delimiter_op_prefix,
      [
        Mold.mk_bin(Precedence.max, Exp, []),
        Mold.mk_bin(Precedence.max, Pat, []),
        Mold.mk_bin(Precedence.max, Typ, []),
        Mold.mk_bin(Precedence.max, TPat, []),
      ],
    )
  | ExplicitHole => (
      Token.is_explicit_hole,
      [op(Exp), op(Pat), op(Typ), op(TPat), op(Drv(Typ))],
    )
  | LLMHole => (Token.is_llm_hole, [op(Exp), op(Pat), op(Typ), op(TPat)])
  | Wild => (Token.is_wild, [op(Pat), op(Drv(Exp))])
  | String => (Token.is_string, [op(Exp), op(Pat)])
  | QuotedLabel => (Token.is_quoted_label, [op(Exp), op(Pat), op(Typ)])
  | IntLit => (Token.is_int, [op(Exp), op(Pat)])
  | FloatLit => (Token.is_float, [op(Exp), op(Pat)])
  | LivelitName => (Token.is_livelit, [op(Exp), op(Pat)])
  | ProjectorInvoke => (
      Token.is_projector_invoke,
      [op(Exp), op(Pat), op(Typ), op(TPat)],
    )
  | BoolLit => (Token.is_bool, [op(Exp), op(Pat)])
  | UndefinedLit => (Token.is_undefined, [op(Exp), op(Pat)])
  | EmptyList => (Token.is_empty_list, [op(Exp), op(Pat), op(Drv(Exp))])
  | EmptyTuple => (
      Token.is_empty_tuple,
      [op(Exp), op(Pat), op(Typ), op(Drv(Exp))],
    )
  | Deferral => (Token.is_wild, [op(Exp)])
  | TyVar => (Token.is_typ_var, [op(Typ)])
  | TyVarP => (Token.is_typ_var, [op(TPat)])
  | Ctr => (Token.is_ctr, [op(Exp), op(Pat)])
  | Type => (Token.is_base_typ, [op(Typ)])
  | DrvVar => (
      Token.is_typ_var,
      [op(Drv(Exp)), op(Drv(Pat)), op(Drv(Typ)), op(Drv(TPat))],
    );

module Molds = {
  let atomics: list((Token.t => bool, list(Mold.t))) =
    List.map(get_atomic_form, all_of_atomic_form);

  let compounds: list((Label.t, list(Mold.t))) =
    forms
    |> List.fold_left(
         (acc, (_, {label, mold, _}: t)) => {
           let molds =
             switch (List.assoc_opt(label, acc)) {
             | Some(old_molds) => old_molds @ [mold]
             | None => [mold]
             };
           List.cons((label, molds), List.remove_assoc(label, acc));
         },
         [],
       );

  let atomic: Token.t => list(Mold.t) =
    (t: Token.t) =>
      List.concat_map(((p, molds)) => p(t) ? molds : [], atomics);

  let compound = (label: Label.t): option(list(Mold.t)) =>
    List.assoc_opt(label, compounds);

  let get = (label: Label.t): list(Mold.t) =>
    switch (label, compound(label)) {
    | ([t], Some(molds)) when atomic(t) != [] => atomic(t) @ molds
    | ([t], None) when atomic(t) != [] => atomic(t)
    | (_, Some(molds)) => molds
    /* For tokens which are not assigned molds by the language definition,
       we assign a default 'Any' mold, which is either convex or concave.
       This is half-ass at the moment as we don't have a rigorous lexing
       policy, but is somewhat load-bearing in that remolding as one is
       typing in a multi-character operator can cause jank, which is
       alleviated if we correctly guess that it will become an operator. */
    | ([t], None)
        when Token.is_potential_operator(t) && !Token.is_potential_operand(t) => [
        Mold.mk_bin(Precedence.max, Any, []),
      ]
    | (_, None) => [Mold.mk_op(Any, [])]
    };
};

module Expansion = {
  let expanding_of = ({expansion, label, _}: t): option(expansions) =>
    switch (expansion, label) {
    | (L, [hd, ..._]) => Some([(hd, (label, Direction.Left))])
    | (LT, [hd, ..._]) =>
      Some([(hd, (label, Left)), (ListUtil.last(label), (label, Right))])
    | _ => None
    };

  let expansions: expansions =
    List.filter_map(((_, form: t)) => expanding_of(form), forms)
    |> List.flatten
    |> List.sort_uniq(compare);

  let get = (t: Token.t): (Label.t, Direction.t) =>
    switch (List.assoc_opt(t, expansions)) {
    | Some(expansion) => expansion
    | None => ([t], Right)
    };

  let will = kw => List.length(get(kw) |> fst) > 1;
};
