echo "/* Auto-generated by Version_autogenerator.sh during build */"
echo let branch = \"`git rev-parse --abbrev-ref HEAD`\"\;
echo let commit_hash_short = \"`git rev-parse --short HEAD`\"\;
echo let commit_time = \"`git log -1 --format=%at | xargs -I{} date -d @{} +%m/%d/%y\ %H:%M`\"\;