(include_subdirs unqualified)

(library
 (name testgen)
 (modules
  (:standard \ Main))
 (libraries sexplib ppx_deriving haz3lmenhir base bignum z3)
 (preprocess
  (pps
   ppx_let
   ppx_sexp_conv
   ppx_deriving.show
   ppx_deriving.eq
   ppx_enumerate
   ppx_yojson_conv)))

(executables
 (names Main)
 (modules Main)
 (libraries haz3lmenhir base sexplib bignum z3 testgen)
 (preprocess
  (pps
   ppx_let
   ppx_sexp_conv
   ppx_deriving.show
   ppx_deriving.eq
   ppx_enumerate
   ppx_yojson_conv)))
